### PR TITLE
Load articles and featured shows on the client side

### PR DESCRIPTION
**Pull request by yuki24**
The Featured Shows and Featured Shows sections are located at the bottom of the page, so they do not have to be loaded on the server side. 

By moving the server-side calls/render to the client-side we could improve the server response time by `150ms` (median: `463ms` vs `317ms`, tested locally with redis cache enabled).

### Before:

```
$ ab -n 100 -c 1 "http://localhost:5000/"
...

Document Path:          /
Document Length:        61039 bytes

Concurrency Level:      1
Time taken for tests:   48.805 seconds
Complete requests:      100
Failed requests:        97
   (Connect: 0, Receive: 0, Length: 97, Exceptions: 0)
Total transferred:      6195732 bytes
HTML transferred:       6102671 bytes
Requests per second:    2.05 [#/sec] (mean)
Time per request:       488.051 [ms] (mean)
Time per request:       488.051 [ms] (mean, across all concurrent requests)
Transfer rate:          123.97 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:   409  488  92.0    463     841
Waiting:      409  488  92.0    463     840
Total:        410  488  92.0    463     841

Percentage of the requests served within a certain time (ms)
  50%    463
  66%    483
  75%    498
  80%    511
  90%    563
  95%    802
  98%    816
  99%    841
 100%    841 (longest request)
```
 
### After:
 
```
$ ab -n 100 -c 1 "http://localhost:5000/"
...

Document Path:          /
Document Length:        51373 bytes

Concurrency Level:      1
Time taken for tests:   34.969 seconds
Complete requests:      100
Failed requests:        97
   (Connect: 0, Receive: 0, Length: 97, Exceptions: 0)
Total transferred:      5231734 bytes
HTML transferred:       5138602 bytes
Requests per second:    2.86 [#/sec] (mean)
Time per request:       349.695 [ms] (mean)
Time per request:       349.695 [ms] (mean, across all concurrent requests)
Transfer rate:          146.10 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:   285  349  95.2    317     725
Waiting:      285  349  95.2    317     725
Total:        285  350  95.2    318     725

Percentage of the requests served within a certain time (ms)
  50%    318
  66%    327
  75%    341
  80%    348
  90%    414
  95%    624
  98%    659
  99%    725
 100%    725 (longest request)
```

### Before:

```
$ ab -n 100 -c 3 "http://localhost:5000/"
...

Document Path:          /
Document Length:        61020 bytes

Concurrency Level:      3
Time taken for tests:   40.447 seconds
Complete requests:      100
Failed requests:        92
   (Connect: 0, Receive: 0, Length: 92, Exceptions: 0)
Total transferred:      6195740 bytes
HTML transferred:       6102640 bytes
Requests per second:    2.47 [#/sec] (mean)
Time per request:       1213.419 [ms] (mean)
Time per request:       404.473 [ms] (mean, across all concurrent requests)
Transfer rate:          149.59 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:   487 1202 436.0   1161    2113
Waiting:      487 1191 424.0   1161    2113
Total:        487 1202 436.0   1161    2113

Percentage of the requests served within a certain time (ms)
  50%   1161
  66%   1408
  75%   1454
  80%   1505
  90%   1745
  95%   1999
  98%   2079
  99%   2113
 100%   2113 (longest request)
```

### After:

```
$ ab -n 100 -c 3 "http://localhost:5000/"
...

Document Path:          /
Document Length:        51375 bytes

Concurrency Level:      3
Time taken for tests:   27.278 seconds
Complete requests:      100
Failed requests:        98
   (Connect: 0, Receive: 0, Length: 98, Exceptions: 0)
Total transferred:      5231485 bytes
HTML transferred:       5138416 bytes
Requests per second:    3.67 [#/sec] (mean)
Time per request:       818.330 [ms] (mean)
Time per request:       272.777 [ms] (mean, across all concurrent requests)
Transfer rate:          187.29 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:   296  804 271.2    755    1530
Waiting:      296  745 249.0    747    1306
Total:        296  804 271.2    755    1530

Percentage of the requests served within a certain time (ms)
  50%    755
  66%    796
  75%    980
  80%   1096
  90%   1171
  95%   1231
  98%   1522
  99%   1530
 100%   1530 (longest request)
```

### CODE REVIEW

**Comment by mzikherman** [comment]
Great thinking! Yea, I guess those sections at the bottom of a bunch of other stuff (whether you are logged in or out), can move to client-side, for sure 👍 

Does this have any pre-rendering/SEO implications? Might be worth checking there's any Reflection impact or something? That's the only thing I can think of when moving server -> client-side.

Looks like some legit ❌ 

Awesome work!

**Comment by mzikherman** [comment]
Cool, merge at will!

**Comment by yuki24** [comment]
I've added a `meta( name="fragment", content="!" )`. It seems like this is the key necessary to have Reflection enable Javascript and render the entire page properly. I'll merge and see what it generates next time.

**Comment by joeyAghion** [comment]
To be clear, Reflection will crawl and pre-render all the pages it knows about via sitemaps (including `/`). It's [Google's bot](https://developers.google.com/webmasters/ajax-crawling/docs/specification) that looks for the meta tag and makes a second request (with `?_escaped_fragment_=` appended) for the pre-rendered HTML.

**Comment by yuki24** [comment]
Got it. Thanks for the context!

**Pull request merged**
