### PR TITLE
Article2

### PR DESCRIPTION
**Pull request by dzucconi**
OK, this puts enough on the bones to merge. I'll follow this up with a an epic and tickets for the remaining work.

Here's a few different article layouts:

https://user-images.githubusercontent.com/112297/150176970-0d04de27-8cac-4a03-9239-023cdbcec649.mov

https://user-images.githubusercontent.com/112297/150176995-dc711075-d993-4fbc-bf8e-d5468bedb92f.mov

https://user-images.githubusercontent.com/112297/150177022-b192d7df-c174-4112-9d69-ccf20fbf3fa9.mov

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Routes added to `routes.tsx` should have a corresponding cypress.js smoke test. See the `cypress/integration` folder for examples.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3a97bb35418f0acdf8e694fe28770b54aca6d0d5
</p>

**Comment by damassi** [comment]
On earth time this PR is like months of work... All very straightforward so far 👍  I'm sure you're already thinking about it but we should keep in mind the infinite scroll

**Comment by dzucconi** [comment]
Yeah; here's the TODO I've identified so far:

**Comment by damassi** [comment]
Again, many many thanks hustling here ⭐

**Pull request merged**
