### PR TITLE
fix(CX-3129): Cleanup Inquiry flow

### PR DESCRIPTION
**Pull request by MrSltun**
The type of this PR is: **Fix**

This PR solves [CX-3129]

### Description
This PR updates the Inquiry flow by removing a few steps that collect information that are not being used in the Collector Resume

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3129]: https://artsyproduct.atlassian.net/browse/CX-3129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dzucconi** [comment]
RIP

**Review by lordkiz — APPROVED** [review]
🧹 Thank you

**Comment by MounirDhahri** [comment]
Hell yeah!

**Review by MounirDhahri — APPROVED** [review]
LGTM, let's keep an eye on this to make sure no Integrity tests fail because of it

**Comment by dzucconi** [comment]
Good call @MounirDhahri — see: https://github.com/artsy/integrity/blob/main/cypress/e2e/marketplace/inquireOnArtwork.cy.ts

**Comment by MounirDhahri** [comment]
@MrSltun let's then not merge this until next week to avoid Friday panic 😄

**Pull request merged**
