### PR TITLE
Onboarding PR 

### PR DESCRIPTION
**Pull request by damassi**
WIP

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a PR summary</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please assign someone to your PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by damassi** [comment]
@alloy - @yuki24 and I have found the issue: See https://artsy.slack.com/archives/C2TQ4PT8R/p1519235362000559?thread_ts=1519232921.000605&cid=C2TQ4PT8R

Looks like this is more of a general problem with pathing as it relates to compilation output -- since `src` is unlikely to remain present once compilation output moves to, say, `dist`. Not sure how to approach this ATM.

**Comment by yuki24** [comment]
We just updated this PR and should be able to merge once the build is 🍏.

**Comment by yuki24** [comment]
Alright, now that we have 🍏so I'm merging this PR!

**Pull request merged**
