### PR TITLE
feat: Add hide upcoming auction results filter

### PR DESCRIPTION
**Pull request by olerichter00**
Addresses [CX-3221]

## Description

Add "hide upcoming auction results" filter.

Screenshot 2023-01-11 at 16 15 28

[CX-3221]: https://artsyproduct.atlassian.net/browse/CX-3221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
LGTM - nice PR Ole 👏 
No feedback from me apart from maybe hiding this behind a feature flag and also adding a video/screenshot (probably you're already doing that now since I am reviewing this as soon as you opened the PR). Otherwise, please feel free to merge

**Comment by olerichter00** [comment]
@MounirDhahri I've put the changes behind a feature flag. Thanks for the reminder 🙏

**Comment by MounirDhahri** [comment]
niiice

**Review by dariakoko — COMMENTED** [review]
niceee

**Pull request merged**
