### PR TITLE
feat: Added Android download link to footer on desktop

### PR DESCRIPTION
**Pull request by anastasiapyzhik**
https://artsyproduct.atlassian.net/browse/GRO-340

**Before**
Screen Shot 2021-05-28 at 11 40 43 AM

**After**
Screen Shot 2021-05-28 at 11 40 59 AM

### CODE REVIEW

**Review by damassi — APPROVED** [review]
If there's already a `Footer.jest` file can we add a test ensuring these two new links are there?

Otherwise LGTM (once conflicts, etc are fixed) 👍

**Comment by anastasiapyzhik** [comment]
Didn't notice CI failure and merged PR, that's my bad. I needed to merge this PR to update tests here https://github.com/artsy/force/pull/7671

This is the reason of failure
Screen Shot 2021-06-01 at 1 13 50 PM
I've fixed it in https://github.com/artsy/force/pull/7671 so once it's merged everything should be fine.

**Comment by damassi** [comment]
@anastasiapyzhik - after a git push, will want to wait ~30 seconds to see all of our CI jobs running, and github will block one from merging if there's an error. However, if you git push and then the button us green for a sec. We'll want to avoid that and make sure that all checks look like this:

gh

**Comment by anastasiapyzhik** [comment]
@damassi sorry for that. I'll be more attentive from now on

**Comment by jonallured** [comment]
OMG I totally made this mistake yesterday on a Gravity PR! 😂

**Comment by damassi** [comment]
I've done it a lot... Thinking like "wow, someone really fixed our CI time!" Only to then realized that it was only warming up

**Pull request merged**
