### PR TITLE
fix [CX-2690]: Update My Collection banner style

### PR DESCRIPTION
**Pull request by MrSltun**
The type of this PR is: **Bugfix**

This PR solves [CX-2690]

### Description
Updates My Collection banner style

image

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2690]: https://artsyproduct.atlassian.net/browse/CX-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
🙏

**Review by olerichter00 — COMMENTED** [review]
not quite sure about the banner style 🤔

**Comment by MounirDhahri** [comment]
@olerichter00 I think design wants it to be blue100

**Comment by MounirDhahri** [comment]
I am in a all with Dasha, i will check

**Comment by MounirDhahri** [comment]
Dasha said it's good this wa

**Review by olerichter00 — APPROVED** [review]
Then let's merge. I just haven't seen this style anywhere in the app before 🤷

**Pull request merged**
