### PR TITLE
@oxaudo => Update edition set display on artwork page for availabilities

### PR DESCRIPTION
**Pull request by mzikherman**
Currently on staging: 

screen shot 2017-11-21 at 6 29 41 pm

With using the new field in https://github.com/artsy/metaphysics/pull/825

screen shot 2017-11-21 at 6 21 01 pm

Closes https://github.com/artsy/collector-experience/issues/341

### CODE REVIEW

**Comment by alloy** [comment]
This looks good to me and innocuous enough, so I’ll merge this in case @oxaudo is OOO for thanks giving.

**Comment by mzikherman** [comment]
@alloy mind checking out the metaphysics pr as well? It's linked above.

**Comment by oxaudo** [comment]
👍 Thanks for taking care of that @mzikherman and @alloy

**Comment by alloy** [comment]
Oops, hadn’t noticed that that link in between the screenshots was a MP PR link, my bad and thanks @oxaudo!

**Pull request merged**
