### PR TITLE
feat(MOPLAT-261): Sentence case on placeholder 

### PR DESCRIPTION
**Pull request by patrinoua**
The type of this PR is: **feat**

This PR resolves [MOPLAT-261](https://artsyproduct.atlassian.net/browse/MOPLAT-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)

### Description

Data entry field placeholder copy will be changed from Title Case to Sentence Case, as agreed by Brand and Design stakeholders. 

**Sentence Case is defined as:**
*First letter of first word is capitalized.* No other words in phrase or sentence are capitalized, with the exception of proper nouns, acronyms and feature names (e.g. Baltimore, NFT, My Collection).*

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by AlicanAkyuz** [comment]
one suggestion I have is to update Palette's input element (whatever case is passed to it as placeholder, it'll transform the string to correct case). This way, the placeholder will be consistent across the board and it'll be easier to update it again should the opinion about casing changes in the future.

**Comment by patrinoua** [comment]
@damassi @AlicanAkyuz is it ok if we merge this and perhaps add another PR with more changes like that?

**Comment by damassi** [comment]
Yup, totally cool to merge and iterate 👍

**Comment by patrinoua** [comment]
🚀

**Pull request merged**
