### PR TITLE
@eessex => Meta Tag Updates for Distribution Channels

### PR DESCRIPTION
**Pull request by kanaabe**
Closes https://github.com/artsy/force/issues/467

### CODE REVIEW

**Comment by kanaabe** [comment]
Oops don't merge this yet. Need to update title

**Comment by kanaabe** [comment]
Ok 👍

**Comment by eessex** [comment]
@kanaabe looks good - - there were some unrelated tests failing so I haven't merged. I wonder if we should look at adding meta field to the EOY project as well?

**Comment by kanaabe** [comment]
@eessex goooood call! will add + fix tests

**Comment by kanaabe** [comment]
Merging this!

**Pull request merged**
