### PR TITLE
chore: Code Cleanup

### PR DESCRIPTION
**Pull request by icirellik**
Simple code cleanup, one commit per change:

[review app](novo.artsy.net)

- Remove unused: desktop/components/smooth_scroll
- Remove unused: desktop/components/side_tabs
- Remove unused: desktop/components/save_button
- Remove unused: desktop/components/reveal
- Remove unused: desktop/components/related_shows
- Remove unused: desktop/components/related_articles
- Remove unused: desktop/components/partner_profile_cover
- Remove unused: desktop/components/partner_phone_number
- Remove unused: desktop/components/partner_locations
- Remove unused: desktop/components/map_modal
- Remove unused: desktop/components/mailcheck
- Remove unused: desktop/components/info_menu
- Remove unused: desktop/components/error_handler
- Remove unused: desktop/components/embedly
- Remove unused: desktop/components/auction_lots
- Remove unused: desktop/components/auction_artwork_brick
- Remove unused: desktop/components/artwork_masonry_4_column
- Remove unused: desktop/components/artwork_masonry
- Remove unused: desktop/components/artwork_brick_rail
- Remove unused: desktop/components/artsypedia
- Remove unused locals in tests
- Remove another unused collection: desktop/collections/featured_links.coffee
- Remove unused models
- Remove unused collections

### CODE REVIEW

**Review by damassi — APPROVED** [review]
Screen Shot 2021-07-28 at 11 29 45 AM

gracias 👍

**Review by dzucconi — APPROVED** [review]

**Review by joeyAghion — APPROVED** [review]
Brought to you

**Comment by icirellik** [comment]
@damassi that +21 still bothers me, even knowing that it was only some decaffeination cleanup to delete unused `returns`.

**Review by mc-jones — APPROVED** [review]

**Comment by dzucconi** [comment]
So, turns out error_handler is still in use.

**Comment by icirellik** [comment]
@dzucconi Oh no!

**Pull request merged**
