### PR TITLE
Possibly unused code?

### PR DESCRIPTION
**Pull request by yuki24**
It seems that the `Following#followAll` and `Following#unfollowAll` functions have never been used since they were added on 1295a3b4c. There are no references to these functions, and when I tried to use the `#followAll` function, I received the following error:

screen shot 2017-05-11 at 11 49 29

There is [an API in Gravity that accepts multiple profiles](https://github.com/artsy/gravity/blob/c4934d6/app/api/v1/me_follow_profiles_endpoint.rb#L37-L56), but I'm not sure if `FollowProfile` is the same resource as `FollowArtist`. It is possible that they were added for future use cases, but have never actually been used.

### CODE REVIEW

**Comment by craigspaeth** [comment]
These definitely smell like simply dead code that hasn't been used in 3+ years. LGTM, thanks for the cleanup!

**Comment by yuki24** [comment]
Builds are being flaky and I needed to rebuild twice. Let's see how the third one goes...

**Comment by craigspaeth** [comment]
😕  feel free to pend the sporadic test if it fails again (especially if it's an acceptance test).

**Comment by craigspaeth** [comment]
😞  there it goes again... not sure why these timeout on CI (deja-vu). Feel free to turn [this line](https://github.com/artsy/force/blob/master/test/acceptance/auth.js#L16) into an `xit` to pend it.

**Comment by yuki24** [comment]
Ok, it's finally green👍🏻

**Pull request merged**
