### PR TITLE
@alloy => Remove unneeded server-side fetches, and remove `assign`

### PR DESCRIPTION
**Pull request by mzikherman**
Removes the now redundant server-side fetches (and a bit of cleanup).

### CODE REVIEW

**Comment by alloy** [comment]
Sweet 👌 

Those CI failures are legit, though. Feel free to merge on green.

**Comment by mzikherman** [comment]
Sigh, I just spent half an hour trying to get the tests passing.

It uses 3+ year old libraries (stubbing Backbone sync, mocha, there's a double `_.defer` going on..... 😢 ), and honestly I don't think the test really does much.

I'll try for a little bit longer and then I'll just pend them for now.

cc @craigspaeth if he's up for some pairing! He is the master of these tests.

**Comment by craigspaeth** [comment]
I'm down @mzikherman feel free to put w/e is on the calendar. In the future when someone touches this kind of old backbone/coffeescript code should consider taking the extra effort to decaffinate the file and attempt to use async/await + metaphysics—too optimisitic maybe, but thatd simplify the stubbing madness quite a bit.

**Comment by mzikherman** [comment]
Ah good call @craigspaeth yea, that might be nice. I'll hunt around for some examples.

I'll make that a follow-up issue and pend for now, as working on the filters for Relay Modern basically got creeped to do a full rebuild of the gene + tag pages! 😅

**Comment by alloy** [comment]
I’m going to assume that you verified that the things the test tried to verify actually still work and merge 👍

**Pull request merged**
