### PR TITLE
feat(FX-4067): add countdown timer to lot card in "Works By Artists You Follow" rail on Sail/Auction page

### PR DESCRIPTION
**Pull request by dimatretyak**
The type of this PR is: **Feature**

This PR solves [FX-4067]

Review app: https://countdown-timer.artsy.net/

### Demo
| Before | After |
| ------------- | ------------- |
| before | after |

#### Different states
| Closes on | Closes in | Closed |
| ------------- | ------------- | ------------- |
| after | after-2 | after-3 |

### Acceptance Criteria
* Display the countdown timer for artworks in "Works By Artists You Follow" rail on Sail/Auction page
* Display only the countdown timer (without the lot number)
* The countdown timer timer should be displayed above the artist name similar to the artwork grid

[FX-4067]: https://artsyproduct.atlassian.net/browse/FX-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nickskalkin** [comment]
*question*: I am wondering if we should apply same changes to this page: https://countdown-timer.artsy.net/works-for-you/ Currently there is a countdown, but it overlays an image (overlaying an artwork with anything is a sin at Artsy, right? 😄 )

**Review by nickskalkin — APPROVED** [review]
👍

**Comment by dimatretyak** [comment]
> _question_: I am wondering if we should apply same changes to this page: https://countdown-timer.artsy.net/works-for-you/ Currently there is a countdown, but it overlays an image (overlaying an artwork with anything is a sin at Artsy, right? 😄 ) 

Hmm, good question. I will clarify this point with the designers

**Comment by dimatretyak** [comment]
> > _question_: I am wondering if we should apply same changes to this page: https://countdown-timer.artsy.net/works-for-you/ Currently there is a countdown, but it overlays an image
> 
> Hmm, good question. I will clarify this point with the designers

[Discussed](https://artsy.slack.com/archives/C9SATFLUU/p1659105548009059) this point and decided to leave everything as it is for now (I [created a task](https://artsyproduct.atlassian.net/browse/FX-4118) in the backlog and maybe this behavior will be fixed in the future)

**Pull request merged**
