### PR TITLE
@anadaroop preserve ordering of multiple buckets in partner rails

### PR DESCRIPTION
**Pull request by 1aurabrown**
fixes https://github.com/artsy/force/issues/855

The issue was, we already had code in place to allow for the rails on the gallery pages to be populated by multiple fetches (id, one fetch with parameters to return only current shows, another for upcoming). The intent was for the results from the first fetch to precede the results from the second. However there was a race condition between multiple fetches performed in parallel, and whichever results were returned first would be displayed at the beginning of the carousel. I modified things to preserve the ordering of the results _after_ all parallel fetches are complete.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
see here: https://github.com/1aurabrown/force/blob/59299a11ab6befecbf636ecc62372147fff4925a/apps/partner2/client/overview_layout_factory.coffee#L109-L112

**Comment by anandaroop** [comment]
Aha, nice fix. And thanks for picking this up @1aurabrown !

I'm a little unclear on the CI situation now, I think the Semaphore error is real and the Travis passing is spurious because tests [aren't actually being run](https://github.com/artsy/force/pull/869) on Travis [at the moment](https://travis-ci.org/artsy/force/builds/202605424)?

**Comment by mzikherman** [comment]
Yea, Travis only runs Danger, and Semaphore does the builds/deploys (currently).

**Comment by anandaroop** [comment]
Thanks! merging...

**Pull request merged**
