### PR TITLE
@kanaabe => Team channel home

### PR DESCRIPTION
**Pull request by eessex**
Following up on https://github.com/artsy/force/issues/628
- Adds new max width to home pages for team-channels
- Footer menu matches width of team channels, and displays mobile menu 

It looks like the mobile footer defaults to display: none everywhere, do you know why this might be?  I enabled it for team-channel pages only.

### CODE REVIEW

**Comment by kanaabe** [comment]
Looks great! 

I don't know about the mobile footer, but it looks like this was initially added [here](https://github.com/artsy/force-private/commit/29519f41874acb302a5cc63083ff8b6c218811a0#diff-3225b381eb5a0475d077d2ed4c249a63R75) by @craigspaeth -- craig, can we remove this rule to omit the footer from being displayed on <600px screens? It was done before we had a responsive footer, so it's probably ok to allow this now.

**Comment by kanaabe** [comment]
@eessex I think it's safe to remove the `display: none` rule for the default now that we have a <600px look for it.

**Comment by eessex** [comment]
@kanaabe - <600px is now removed

**Comment by kanaabe** [comment]
👏 💯  Awesome! Great work.

**Pull request merged**
