### PR TITLE
@kanaabe => [WIP] Session id for users

### PR DESCRIPTION
**Pull request by eessex**
cc: @nicholassewitz 

Adds a `force-session-id` cookie to anonymous and logged in users. 

We need to pass the param as a cookie in order to bypass Marketo requirements, where fields called 'session_id' are not accepted for anonymous users.

### CODE REVIEW

**Comment by nicholassewitz** [comment]
yay!!!!!!! 

cc @anipetrov 

we are adding session_id on form submittal. The field can be found on the lead, contact, or application object moving forward in Salesforce.

**Comment by anipetrov** [comment]
we will need to also add this same `session_id` on the event level, possibly as part of the `identify` event

**Comment by nicholassewitz** [comment]
@anipetrov We send the session_id on all identify calls as well as the tracking call when the embedded form is submitted. Is that enough?

https://github.com/artsy/force/blob/master/desktop/analytics/partner_application.js

https://cl.ly/0w2l1B380k37

**Comment by anipetrov** [comment]
if i am not mistaken if we add that `session_id` to the identify event, it will automatically be a field on any event sent by that user. i do have questions about the assigning and expiration conditions for that force_session_id cookie tho, how exactly does it work?

**Comment by eessex** [comment]
The problem is that marketo wouldn't accept the session_id's from that event for anonymous users. 
Adding this cookie allows us another method to grab ids for the logged out users.

**Comment by anipetrov** [comment]
do you mean that marketo does not accept the segment generated cookie which lives under `anonymous_id` or are you talking about another `session_id`

**Comment by nicholassewitz** [comment]
adding onto Eve's comment in my research it seems like we send `session_id` with pretty much any analytics event we call.  

Eve and I tried researching how and when `session_id` is set and expired, but we had not luck in figuring it out. In this implementation however we do guaruntee that the `session_id` passed in the analytics call will always match the `session_id` passed in the cookie

Marketo does not accept segment's `anonymous_id` if the user is anonymous

**Comment by anipetrov** [comment]
sounds good, thanks both of you for the context!

**Comment by kanaabe** [comment]
👍  Thanks for moving out of global and the rename. Looks like you have a ❌  but the rest looks good.

**Comment by eessex** [comment]
heads up @nicholassewitz, we've moved this into the partnerships app and the cookie is now called 'marketo-session-id'

**Comment by nicholassewitz** [comment]
is there a reason we are calling it marketo-session-id. it seems like that
could cause confusion since it is actually the force `session_id`?

**Comment by nicholassewitz** [comment]
i also sort of already implemented the changes on like 12 marketo forms but
np if there is a good reason to change it back.

**Comment by eessex** [comment]
@kanaabe recommended that we not use a global cookie, and only set and reset them on pages where they are used.

**Comment by nicholassewitz** [comment]
hmm im not disputing moving them to specific page just the naming of the cookie being slightly confusing since it is not a unique `session_id` for marketo, but IS the force `session_id`.  @kanaabe  what do you think?

**Comment by kanaabe** [comment]
@eessex a cookie is "global" in the sense that it will remain on the user's browser from page to page unless you expire them immediately after -- which seems like a bad use case for a cookie. I'm looking at our cookies again tho, and how come we can't use `force-NODE_ENV.session` @eessex? Isn't it the same thing?

@nicholassewitz if we only add cookie logic/refreshes to a specific page, it means that we can't guarantee that the cookie will be up to date on every page. If another developer comes along and sees `force_session_id` they might assume it's an accurate session id when it might not be. If on the other hand we _were_ to set the session id on each page load, i would call it something like `force_session_id`. Lmk if I'm not making sense -- basically i can just see someone assuming it's an id that's ok to use when it's actually not. Also tangent: I'm curious how the Marketo form gets the cookie details?

**Comment by eessex** [comment]
@kanaabe, we can't use the force-NODE_ENV.session because it doesn't match the actual session ID -- seems to be hashed.  Looking at the browser now my force-production.session is 
"eyJpbk1lcmdlZEZvcmNlIjpmYWxzZSwicGFzc3BvcnQiOnt9LCJpZCI6ImUyZTUxMjIwLTBiNGQtMTFlNy05MzYzLTI3N2ZkNjA2ZDE1ZCIsImZsYXNoIjp7fX0"

The sd.SESSION_ID is "e2e51220-0b4d-11e7-9363-277fd606d15d"

**Comment by kanaabe** [comment]
Ah i didn't know the session was encrypted -- well that leads me down another path of, why? It's probably encrypted for a good reason, right? I'm going to guess it's related to session hijacking. We use HTTPS on our site so sniffing will not be a problem but what's the risk in not encrypting the id? Do you mind looking into this and determining if it's safe for us to pass the raw id through a cookie?

**Comment by nicholassewitz** [comment]
so it seems like passing the `session_id` to a cookie is a bad idea....https://en.wikipedia.org/wiki/Session_hijacking

**Comment by eessex** [comment]
Ok I am going to close this for now, sounds like the strategy needs reevaluated.

**Comment by nicholassewitz** [comment]
@eessex @kanaabe do you think we will run into the same issues of security if we pass the session id as a utm_param?

**Pull request closed without merging**
