### PR TITLE
feat: Track user interactions in new checkout flow - order review page [PX-4617]

### PR DESCRIPTION
**Pull request by pepopowitz**
Partially addresses [PX-4617]

Collaboration with @annacarey, @ansor4, and @jpotts244 

@brendamanganelli the only event **from the order review page events** not included in this PR is `clickedOnSubmitOrder` -- we skipped this one because [we're already tracking something for that event](https://github.com/artsy/force/blob/5afd5f6f6e3de5d87dfa70d34058e23f3a41dd14/src/v2/Apps/Order/Routes/Review/index.tsx#L54-L66). Let us know if we need to make changes to the existing tracked event, or if it's something you can use on your end without changes.

## follow-up work
- There is a TODO to move an OwnerType constant to cohesion, but we're hoping to launch shipping tomorrow and we plan to do that after launch.
- Tests!

[PX-4617]: https://artsyproduct.atlassian.net/browse/PX-4617

### CODE REVIEW

**Review by jpotts244 — APPROVED** [review]
Not super knowledgeable in this area but here if you nee help shipping/testing

**Review by annacarey — APPROVED** [review]
Nice work on this!

**Comment by brendamanganelli** [comment]
Great job - and thank you! We would need to move all existing events to Cohesion at some point, but it's not a launch blocker - so let's skip it for now.

**Comment by chr-tatu** [comment]
> Great job - and thank you! We would need to move all existing events to Cohesion at some point, but it's not a launch blocker - so let's skip it for now.

@brendamanganelli : If there's no ticket for moving them to Cohesion, could you create it, so we don't forget about it?

**Review by ansor4 — APPROVED** [review]

**Pull request merged**
