### PR TITLE
@mzikherman : add click tracking to homepage recommendations

### PR DESCRIPTION
**Pull request by cavvia**
Adds click tracking on recommendations as it's a KPI (along with inquiries) for upcoming recs experiments.

I also need the mobile app equivalent - @alloy, any idea about click tracking on recommendations in eigen? Is that something we currently have or could add?

### CODE REVIEW

**Comment by alloy** [comment]
We could, yeah. @mennenia is working on overhauling analytics on mobile atm, so a great time to put in the request: https://github.com/artsy/collector-experience/issues/63

**Comment by anipetrov** [comment]
hey @cavvia, we actually have a [card](https://trello.com/c/2HSvKCD3/941-2-develop-better-tracking-to-understand-how-users-are-interacting-with-their-personalized-feed-in-ios) in our sprint to provide a schema for tracking clicks on recommendation rails that would be enriched with properties, so we can differentiate which exact rail you clicked on. do you think that's still needed?

**Comment by cavvia** [comment]
@anipetrov This click tracker is only for a specific rail on the homepage ('Recommended Works for You') and I've not added any structured data around the click (such as the artwork ID). It sounds like you have a more systematic plan to click track all the rails - in which case that would supersede this. So yes, I think your work is still needed after this if the goal is to analyse interactions with all the rails on the personalized homepage on force/eigen.

**Comment by mennenia** [comment]
@cavvia we can definitely do this - it will be part of adding analytics to our React Native views. I'm currently mapping out the scope of the project, but will add it to the list of events :).

**Comment by cavvia** [comment]
Thanks a lot @mennenia!

**Pull request merged**
