### PR TITLE
chore(art taste quiz): Add INTL to Welcome Screen

### PR DESCRIPTION
**Pull request by JanaeHijaz**
The type of this PR is: Chore

This PR solves [GRO-1317]

### Description

Adds useTranslation and t function to Welcome Screen and copy text to translation.json file. 

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1317]: https://artsyproduct.atlassian.net/browse/GRO-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jonallured — APPROVED** [review]
LGTM!! 🎉

**Comment by TMcMeans** [comment]
LGTM 👍🏾 🥇 looks like an unrelated test is failing on CI though, you might have to run a yarn install or do a  rebase on this pr to get it passing again. Let me know if you have questions about that!

**Review by TMcMeans — APPROVED** [review]

**Comment by TMcMeans** [comment]
Looks like re-running Circle CI test is what was needed to get the test to pass, so feel free to merge when you're ready 👍🏾

**Comment by TMcMeans** [comment]
Gonna merge it in!

**Pull request merged**
