### PR TITLE
Add alert for force master test failures

### PR DESCRIPTION
**Pull request by zephraph**
This adds a slack message that gets sent to our alerts channel if a force test fails on master.

### CODE REVIEW

**Comment by zephraph** [comment]
Because I didn't know about it 😄

**Comment by joeyAghion** [comment]
😆 happy to be of service.

The #alerts channel should be reserved for incidents-worthy events (ideally), so I think this would be more appropriate to one of the more informational channels like #platform-machines or #front-end-notifs.

**Comment by zephraph** [comment]
@joeyAghion I think there _is_ a reason. Because it only sends alerts when _master_ fails (and there are no alerts when it stops failing)

**Comment by starsirius** [comment]
Nice! Didn't know it's now supported via orbs! I remembered notifications in CircleCI 2.0 was undocumented. 💯

The existing CircleCI app was not flexible because we cannot limit notifications on certain branches. To achieve similar goal here, I ended up using hacky/indirect [email forwarding](https://artsy.slack.com/archives/C9ZJYFDNF/p1558562415181000) for Volt to only notify successful and failed builds on _master_ and _release_ branches.

**Comment by starsirius** [comment]
Hmm looks like this orb only supports [one single specific branch](https://github.com/CircleCI-Public/slack-orb#status). Not sure if it's possible to notify on both master and release branches. The opposite kind of limitation. 😅

**Comment by zephraph** [comment]
@starsirius I don't see why not. Just do it in two separate steps.

**Comment by zephraph** [comment]
cc @starsirius 

```yaml
- slack/status:
          fail_only: "true"
          failure_message: "Tests have failed for a Force staging build"
          only_for_branch: staging
- slack/status:
          fail_only: "true"
          failure_message: "Tests have failed for a Force release build"
          only_for_branch: release
```

**Comment by starsirius** [comment]
@zephraph That's a good idea! I had that impression because it [said](https://github.com/CircleCI-Public/slack-orb#status)
> This must be the last step in a job
But indeed test and deploy are different jobs, and we can add it to the last step of those jobs. Going to give it a try for Volt at some point! So excited to retire my email filters! 👍

**Comment by zephraph** [comment]
Looking at the source it should would just fine with both in the same job too. I think why they say that is it reports the status of the job _to that point_. So if you put the status step earlier in the workflow and something failed after it it'd still seem like it passed. 

It uses the [when](https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute) property to do that.

**Comment by damassi** [comment]
@zephraph / @eessex - this good to merge?

**Comment by starsirius** [comment]
@dleve123 and I are trying out system-specific channels (e.g. #deploys-pulse for Pulse). If that's useful, we can follow similar protocol for Force. More discussion in https://artsy.slack.com/archives/CA3D02SDN/p1569247787179400.

**Comment by dleve123** [comment]
If force master is broken, it seems more likely than not that every product team should be aware of it (almost all teams change force). I'd encourage us (perhaps a bit controversially) to post master build failures to `#dev` and iterate from there. IMHO, that we be a marginal improvement over current state.

**Comment by damassi** [comment]
Going to close this to clear out some PR noise; feel free to reopen when work resumes.

**Pull request closed without merging**
