### PR TITLE
[CI] Don’t cache build artefacts and silence progress formatter.

### PR DESCRIPTION
**Pull request by alloy**
🐌

### CODE REVIEW

**Comment by alloy** [comment]
Errr. The CI env var doesn’t seem to be set? Or maybe a different value…

https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by orta** [comment]
It could be running in Hokusai @alloy

**Comment by alloy** [comment]
@orta Good call!

**Comment by alloy** [comment]
I wrongly thought that builds previously took ~3 min, but I now see that these long ones always take ~10 min… Ok, then it’s a very very very tiny optimisation. The progress formatter is still a good change, so I’ll leave this as-is.

**Comment by zephraph** [comment]
The road to faster builds is paved by a series of small improvements. LGTM.

**Pull request merged**
