### PR TITLE
@craigspaeth: Launch new gallery partnerships signup page

### PR DESCRIPTION
**Pull request by xtina-starr**
This PR makes the switch to launch the new Gallery Partnership Signup page.

cc: @yuki24 @remyferber

### CODE REVIEW

**Comment by craigspaeth** [comment]
👏  very exciting! LGTM! Feel free to merge when 💚

**Comment by xtina-starr** [comment]
@craigspaeth the failing spec is due to the old gallery partnership signup page which is no longer relevant in this app. I'm wondering if you have any objections to me removing the template tests for now so that this is not blocking for @remyferber and going back later today or tomorrow to add coverage for the auction signup page template?

**Comment by craigspaeth** [comment]
No objections at all—if this is like an AB test and we plan to there's a chacne we'll revert back, then just pend it with `xit` otherwise feel free to remove all the old tests and code (there's always version control to bring it back).

**Comment by remyferber** [comment]
Thanks, @xtina-starr

**Comment by yuki24** [comment]
I'm usually against removing tests unless there's a strong reason to do so (e.g. removing actual features, over-testing) since people tend not to follow up after removing (just because you could doesn't mean you actually will). If it only takes less than 5min, I would rather update it to test what it should test.

**Comment by xtina-starr** [comment]
@yuki24 in this case it would count as removing a feature as we have removed the gallery partnerships aspect of this app into its own app. I would be going back to add coverage to code that is not currently covered (not removing existing code coverage). Since it is additional coverage, I didn't think it needed to block the release.

**Comment by yuki24** [comment]
We just have a conversation offline and I was misunderstanding what @xtina-starr meant. I think we are good to go!

**Pull request merged**
