### PR TITLE
Optimizing moment packages

### PR DESCRIPTION
**Pull request by mdole**
Currently, Force's common.js bundle ends up with two versions of moment and two versions of moment-timezone due to mismatched versions in the lockfile. This PR updates both to match with other dependencies+resolutions, saving an estimated 52 KB (after GZIP) on page load.

Tests all passing with the exception of an infiniteScroll test that fails even with the previously declared versions of moment/moment-timezone.

### CODE REVIEW

**Comment by zephraph** [comment]
@mdole could you post a before and after size of the common bundle?

**Comment by mdole** [comment]
Sure! Wow it's actually over 100Kb savings after GZip 🤔 

Before:
screen shot 2019-02-13 at 2 40 24 pm

After:
screen shot 2019-02-13 at 2 56 34 pm

**Comment by damassi** [comment]
Nice, so the new bundle duplicate plugin is already paying off 🎉

**Comment by zephraph** [comment]
This is huge man! Thanks for tackling.

**Pull request merged**
