### PR TITLE
@alloy: onboarding code review

### PR DESCRIPTION
**Pull request by xtina-starr**
So I'm going back and forth on whether we should be able to just create new react components for the new onboarding UI changes. I think it's possible, but it would be pretty hacky and would eventually end up being throw away code.

### CODE REVIEW

**Comment by yuki24** [comment]
My personal preference is to go with a new app (as in `desktop/apps`) and assign a new path to it. It is possible that if we decided to go with building a fully react-based flow from scratch, we may have to re-build much more than we'd expect. On the other hand, the benefit of just changing the existing backbone-based models is we may be able to save time by re-using the common parts in these two. However, because of the following reasons, it may not be as smooth as we would expect:

 * They depend on globally available variables like jQuery, and this may not work well with a locally scoped react component.
 * We may break the old flow by accident.
 * Because of the paradigm difference between Backbone and React, we may see an edge case where things are hard to track down. One case that I see is `Backbone.View`'s `events` method. I'm not sure how and when it attaches events to elements rendered by React.
 * It'd make it harder to remove the old on-boarding code when we were ready to switch to the new one.

**Comment by xtina-starr** [comment]
Another reason for a separate app is that makes implementing the A/B test a lot simpler.

**Comment by mzikherman** [comment]
It's tough to say....I do think if we rebuild the whole app in React, there'll be a lot more things involved than we might realize now (as was the case with loyalty), and at the very least, things like a state machine, re-onboarding, client-side routing, analytics, will need to be implemented. It's quite likely that, even if there's some glue code here and there, we'll be able to hook into the existing ecosystem for these in onboarding.

For instance, the Backbone router that programmatically launches the correct view for the current step, could instead instantiate a React component for that screen (hooking into analytics).

If the React components were built with props coming from direct Gravity access, those can also be easily saved in the React view: `user = new Backbone.Model(this.props, url: '/api/v1/me').save()`.

On the other hand, rebuilding it might not be so bad, and would also undoubtedly be an improvement and a great chance to refactor.

I do think there's value to both approaches.

**Comment by damassi** [comment]
In our auctions work we plan on eventually refactoring out Backbone but for the time being this is how we've been doing it (via a Redux selector that injects props into a component): https://github.com/artsy/force/blob/master/desktop/apps/auction/components/artwork_browser/main/ArtworkDisplay.js#L144.  In time these call sites will be replaced by Relay queries where appropriate.

**Comment by alloy** [comment]
> However, because of the following reasons, it may not be as smooth as we would expect:

@yuki24 I agree with your points that would make the process less smooth, but that’s kind of a given with fitting a new system on top of an old one, it just requires due diligence.

> Another reason for a separate app is that makes implementing the A/B test a lot simpler.

@xtina-starr It may be obvious to some, but not to me, so can you please elaborate on _why_ that’s simpler?

> On the other hand, rebuilding it might not be so bad, and would also undoubtedly be an improvement and a great chance to refactor.

I think we pretty much all agree on this, which is why we’ll still be doing the full project regardless!

The questions _I’d_ like to see answered is:
1. How much time do we need to spend now to make it work on top of the old system?
2. How much of that code would be thrown away afterwards?
3. Will that approach allow product to perform their test substantially sooner than writing the new app now?

Granted, it’s gonna be hard to estimate accurately, but you could make a prototype by taking the first step (if it’s not substantially less complicated than other steps) and replace the existing view with a bare bones (ugly) react view. This shouldn’t need to take longer than 1 day and should give you a good idea of the parts included and allow you to better estimate the complexity.

**Comment by alloy** [comment]
FWIW My gut feeling is that, as @mzikherman points out, our experience with doing the full thing immediately takes substantially longer.

**Comment by alloy** [comment]
Also, if you’re gonna write a little prototype, be sure to talk to @damassi to answer some of the Backbone + React unknowns.

**Comment by xtina-starr** [comment]
@alloy making a prototype sounds like a good suggestion. In the commit of this PR, I made comments where I think we might need to make changes in the existing codebase in order to be able to bring in a new react components. @yuki24 and I can work on creating a pretty plain component for the first question and see how that fits in. I think we could better answer the questions you mentions after the prototype.

re: the A/B test, if we went with creating a new app, we'd likely only need one conditional to determine what path to send the user down based on which test group they were in. It would either be the old personalize app or the new app we create. If we build on top of the existing code, we would have to liter the existing code with a lot more conditionals.

**Comment by alloy** [comment]
> If we build on top of the existing code, we would have to liter the existing code with a lot more conditionals.

Ah, I see. I wonder if, from a completely naive perspective, it would be feasible to simply _copy_ the existing code and alter that for the new views, leading to actually have 2 apps, and if that would make it easier to do the test?

**Comment by xtina-starr** [comment]
**Reason for not building the new onboarding flow in the existing codebase with new backbone views:**

Because the UI along with the functionality is significantly different, we don’t get to reuse any of the current views and need to create new ones in addition to refactor the `State` class which powers how a user progresses through the onboarding steps.

The ways that the UI and functionality is different:
- The new UI displays the items (collector intent, artists to follow, categories, etc) in a list while it’s displayed in a grid in the existing flow.
- The new flow introduces a next button while the existing flow automatically transitions to the next step after certain actions are taken (i.e. follows a certain number of artists, clicks skip, makes budget selection, etc.)
- The existing flow uses hard-coded order sets in order to display suggested artists and categories and the new flow will use different endpoints to display the suggestions.

As mentioned, in order to fit in the new flow a refactor of the state class is required. This will not only take time but because the codebase presently is tightly coupled and intertwined the necessary refactor introduces more complexity making this area more fragile and bug prone.

It’s also worth noting that I’ve been looking through this codebase pretty often and still don’t fully understand all of it. For the sake easily being able to make changes and share knowledge it might prove fruitful to move away from this pattern. This is just my personal opinion of course.

**Estimation:**
- Refactoring the `State` class - **4-6hrs**
- Intent View: **8hrs**
- Artist View: **16hrs**
- Categories View: **16hrs**
- Budget View: **8hrs**
- Refactoring the `redirectLocation()` functionality: **3-4hrs**
- Test coverage: **20hrs**  
**Total: 78hrs**

cc: @alloy @l2succes @yuki24

**Comment by xtina-starr** [comment]
We've also considered pursuing creating react component views and evaluating the feasibility of injecting those into the existing codebase. After building out majority of the collector intent view as a react component @l2succes and I time boxed rendering it in the existing codebase. While doing so  we run into a few issues. One being that there is a bit more infrastructure that would need to be setup to make this work which extends the time estimate and complexity. This approach doesn't save us any time and adds additional liability because of the refactor required.

The new proposed approach is to build out the complete new onboarding flow in react. Progress has already been made in regards to this and we are still on track to completing the collector intent view within this sprint. @l2succes will be providing estimate for this work and I can add more context with regards to his estimate.

**Comment by alloy** [comment]
@xtina-starr This looks really good 👏 Can you move this to https://github.com/artsy/collector-experience/issues/503 and a summary that links to it on https://github.com/artsy/collector-experience/issues/510?

**Pull request closed without merging**
