### PR TITLE
@kanaabe => [Newsfeed] News articles are supported for AMP

### PR DESCRIPTION
**Pull request by eessex**
For [GROW-391](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-391)

- Adds route `/news/:slug/amp`
- Adds 'news' layout to AMP supported articles
- Adds social_embed section to AMP templates

This does not yet include news source, waiting for design on any further AMP changes for news article.

news-amp-embeds

news-amp

### CODE REVIEW

**Comment by kanaabe** [comment]
I forgot to add `source` in the acceptance criteria for that ticket -- can you add that as a subtask separately? Not worth holding this PR back for it. Please also assign owen to it! 

Finally, I think some screenshots here would be nice, since we're making some hard-coded choices on the heights/widths of those social components.

**Comment by eessex** [comment]
Yes just added some screenshots -- Will add source as another ticket.   The social components seem to resize automatically from the `responsive` widths despite having hard coded sizes (width and height are required to render).

**Comment by kanaabe** [comment]
Ah yeah we should introduce Unica eventually with the blockquotes as well -- @owendodd see screenshots above. We probably can't fit it in this sprint, but a general overhaul of AMP would be nice to prioritize soon. I believe we have a ticket for that already!

**Comment by eessex** [comment]
Ticket for amp updates: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-434

**Pull request merged**
