### PR TITLE
[CI] Add type-check job to circle config

### PR DESCRIPTION
**Pull request by damassi**
Noticed that there was some confusion today around type-checking and yarn linking and looking closer noticed that we're not type-checking our PRs in CI. This adds that job to our flow.

### CODE REVIEW

**Comment by damassi** [comment]
@briansw - noticed there's still some failures in master, but at least they're now being triggered in CI 😄 

Feel free to merge this when things are ready.

**Comment by zephraph** [comment]
Wow...

Good catch.

**Comment by zephraph** [comment]
(Sorry for the over eager MOG 😬)

**Comment by brainbicycle** [comment]
@damassi Sorry again for the trouble and thanks for following up 🙏. I owe you one. Type errors should be resolved in master now with latest version of reaction.

**Pull request merged**
