### PR TITLE
Revert "Refactor: convert AddressForm to functional component to and add v3 styles"

### PR DESCRIPTION
**Pull request by starsirius**
Reverts artsy/force#8387

https://artsy.slack.com/archives/C9YNS4X32/p1632408694257600

### CODE REVIEW

**Comment by dzucconi** [comment]
I will patiently wait for green before merging 😬

**Comment by olerichter00** [comment]
> I will patiently wait for green before merging 😬

No #squashongreeen?

**Review by olerichter00 — APPROVED** [review]

**Comment by dzucconi** [comment]
@olerichter00 that's the problem that led to this being merged: peril has been prematurely merging non-green prs

**Comment by starsirius** [comment]
No Peril merge for now. 😅

**Comment by AlicanAkyuz** [comment]
GREEN!

**Pull request merged**
