### PR TITLE
feat(materials filter): add Materials facet to artwork grids

### PR DESCRIPTION
**Pull request by anandaroop**
https://artsyproduct.atlassian.net/browse/FX-2631
↳ https://artsyproduct.atlassian.net/browse/FX-2742

- Creates a `MaterialsFilter` facet that renders the aggregation as multiple-select checkboxes
- Adds it to the following artwork grids:
  - [x] `/artist/:id`
  - [x] `/artist-series/:id`
  - [ ] ~~`/collect`~~ (none of the aggregation-based filters are showing up here 🤔)
  - [x] `/collection/:id`
  - [x] `/fair/:id`
  - [x] `/show/:id`
  - [x] `/search?term=:term`
- Updates the `Apply (n)` button logic on mobile

## Mobile

(btw noticed while updating ⬆️ that Apply button on mobile that we don't consistently do that with all the new facets. I'll PR something, hopefully with tests that make it easier to catch.)

### CODE REVIEW

**Comment by mzikherman** [comment]
Curious if the filtering here 'just works', without needing to modify the GraphQL query.

**Comment by anandaroop** [comment]
Yeah I just pushed up an update after rebasing — basically all I did was accept your changes instead of mine in the two relevant files — then `yarn relay` — then all good ✨

**Comment by anandaroop** [comment]
Filtering just worked as expected. Very nice! 👌🏽

**Comment by anandaroop** [comment]
I think this is good to now 🕺🏽

**Comment by mzikherman** [comment]
I think there's one other place the filter appears (artist series). Should this filter be added there as well?

**Comment by anandaroop** [comment]
Oh yes, good catch! One sec...

**Comment by anandaroop** [comment]
Thanks, 🍏 again

**Comment by mzikherman** [comment]
Nice!

**Pull request merged**
