### PR TITLE
@sweir27 => Hello Categories App

### PR DESCRIPTION
**Pull request by gnilekaw**
@anandaroop and I paired on this first pass at standing up a React app in Force. 

The `categories2` redesign is a [hack-a-thon project that we're resurrecting](https://github.com/artsy/force/pull/159) as a good place to start building our know-how, so we can eventually refactor other partners apps. 

Nothing too clever here. One thing to note, however, is that we added a Jest command to `yarn test`. This caused a lot of noise in `yarn.lock`. We weren't sure if we should be concerned by this, and if Yarn can be trusted to make so many updates.

For now, we'll be working on this feature branch to keep things separate from the staging/production pipeline.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please assign someone to your PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by anandaroop** [comment]
We're standing on the shoulders of giants here — thanks @sweir27 and @damassi for your work on setting up these patterns in `auctions2`.

Adding Jest into the project is our [small contribution](https://github.com/artsy/force/pull/1084/commits/64a23a3057cec7b09a12f279ba7196b0a18681a2) so far.

**Comment by damassi** [comment]
Nice! Jest snapshots are such a dream 🎉

**Comment by damassi** [comment]
@anandaroop and @gnilekaw - One thing I want to mention is this issue: https://github.com/artsy/ezel-assets/issues/25. When deploying to prod we're not building a "production" version of React, which has a slight perf impact. For our case this is probably imperceptible (aside from the console warning), however.

I don't have enough experience with Force's production compilation pipeline to dive into this, but we should bring up with @craigspaeth once he gets back from vacation.

**Comment by anandaroop** [comment]
Oh nice, thanks for that heads up @damassi very good to know.

Another thing I just noticed is that the Jest specs aren't being run in CI. Looks like the Circle configuration [has been customized](https://github.com/artsy/force/blob/master/circle.yml#L43) and will need to be updated (similar to the [change](https://github.com/artsy/force/pull/1084/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11) we made) to pick up our new specs @gnilekaw

**Comment by sweir27** [comment]
This is so cool!! Excited to see where it goes. And jest is an _awesome_ small improvement 😄 I am happy to merge, but did you want to get CI working first?

adventure_party

**Comment by anandaroop** [comment]
Thanks @sweir27 — just pushed up a commit for CI and Jest seems to be running fine there. Good to merge I think!

**Comment by sweir27** [comment]
Nice! Good work team :D

**Comment by gnilekaw** [comment]
Thanks Roop! (Sarah, this gif made my day.)

**Comment by anandaroop** [comment]
Btw, @kanaabe just kicked off an interesting convo in web standup about the difference between:

-  the approach here, which evolves the sub-app pattern and thereby brings Babel / ES6 / React (and now Jest) into Force

- the approach in react-formation, where for example @l2succes is building up [an entirely separate app](https://github.com/artsy/reaction-force/tree/master/src/apps/loyalty) that will be distributed as an npm module and then get mounted into Express over here. This allows their tooling (TypeScript, Fusebox, etc) to remain independent of Force

**Comment by damassi** [comment]
Very interesting -- what was the outcome of the discussion?

**Comment by sweir27** [comment]
Ah! Would be interested in seeing more on that convo! @craigspaeth mentioned that when he gets back he wants to get us all in a room to talk about this too. 

We went with this approach initially because it allowed us to incrementally introduce these future technologies (i.e. our first iteration just had one react component, the next few introduced redux etc.) while keeping with the existing architecture (one new thing!). @damassi has some ideas too around how to integrate react w/ backbone in an incremental way.

**Comment by anandaroop** [comment]
Yeah, I think the outcome was just a consensus that it _would_ be great to get everyone in a room to talk about this, and the pros/cons of each approach, and whether we'd want to standardize, or whether we let a thousand flowers bloom (well, maybe three flowers).

Looking forward to that convo!

**Comment by l2succes** [comment]
@anadaroop @damassi @sweir27 and anyone else interested.

I actually just merged the PR that mounts the loyalty program app from reaction-force as a separate sub app in force if you guys wanna check it out. https://github.com/artsy/force/pull/1059/files

I will be publishing `reaction-force` to our newly made org on npm shortly so the force package.json will change slightly.
https://www.npmjs.com/org/artsy

**Comment by anandaroop** [comment]
Nice, thanks for that reference @l2succes, looks impressively straightforward!

The npmjs link is erroring for me tho, does the artsy org need to be published or something?

**Comment by damassi** [comment]
@anandaroop - would love to listen in. @l2succes - This is nice!

**Comment by damassi** [comment]
@l2succes - All of our accounts need to be linked to that org to be able to see, right?

**Comment by l2succes** [comment]
@anandaroop Ha sorry for not noticing, you have to be logged in to see the page. If you create an account on npm I can add you to the org. 

@damassi I just added you to the org

**Comment by damassi** [comment]
I'm psyched that this org has been set up! Will make navigating all of our NPM stuff much more straightforward.

**Pull request merged**
