### PR TITLE
@xtina-starr => Fix margins on articles

### PR DESCRIPTION
**Pull request by eessex**
Retains full width layout for articles list, keeps CTAs at full bleed.
https://github.com/artsy/force/issues/1538

### CODE REVIEW

**Comment by eessex** [comment]
We are already overriding the #main-layout-container margins in articles, but needed an extra selector to override the new styles you added.

Before:
screen shot 2017-06-12 at 1 49 06 pm

After:
screen shot 2017-06-12 at 1 49 24 pm

**Comment by xtina-starr** [comment]
Oh okay, so adding the additional class makes this more specific and outweighs the split test's style rules?

**Comment by eessex** [comment]
yep, exactly

**Comment by xtina-starr** [comment]
Got it. LGTM...mergin'

**Pull request merged**
