### PR TITLE
[Feat]: SWA-51/Trim email address

### PR DESCRIPTION
**Pull request by AlicanAkyuz**
### Description 

Ticket: [SWA-51](https://artsyproduct.atlassian.net/browse/SWA-51)

This PR handles the case where user types spaces in contact information step's email input. The spaces are simply trimmed before pushed to formik's event handler. 

### Videos (updated after trim moved to validation)
https://user-images.githubusercontent.com/42584148/140296986-81d23465-7c45-4b91-b0dd-2c5cabe9c1af.mov

### CODE REVIEW

**Comment by AlicanAkyuz** [comment]
@Serge0n I left out testing this trimming, since there's a ticket for unit testing assigned to you.

**Comment by Serge0n** [comment]
I thought that this ticket is to change `validation` and use `trim()` before saving data to session storage. But I'm not sure... Let's ask @kiryl-zubarau and @iskounen

**Comment by kiryl-zubarau** [comment]
I would say yes, let's add `trim` to validation, and before saving the form. I suppose here we should not restrict users to enter spaces. 
Let's also add such behavior for the name and phone number fields.

**Comment by Serge0n** [comment]
Also, you forgot to trim values before saving form data to session storage. Like here:
https://github.com/artsy/force/blob/9b22244da128622d760ad28a270d3edc47e81798/src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx#L40

and to put trimmed values into saveSubmission() like here:
https://github.com/artsy/force/blob/9b22244da128622d760ad28a270d3edc47e81798/src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx#L48

**Comment by AlicanAkyuz** [comment]
oh thanks for catching this @Serge0n, having a look 👀

**Comment by Serge0n** [comment]
> oh thanks for catching this @Serge0n, having a look 👀

No problem) And we should trim all values in the form (phone and name too)

**Review by kiryl-zubarau — APPROVED** [review]
LGTM!

**Pull request merged**
