### PR TITLE
Address problematic tests

### PR DESCRIPTION
**Pull request by eessex**
Attempts to fix up more tests that have consistently been failing master builds.
Also makes jest searching work outside of the `__test__` directory structure, now looking files anywhere with a `.jest` extension.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The staging version of Metaphysics has breaking changes, this might not affect your build, but could mean your queries don't work the way you expect. See below for breaking changes:</td>
    </tr>
  </tbody>
</table>


- :warning: Type 'AnalyticsArtworksPublishedTimeSeriesStats' was removed
- :warning: Field 'AnalyticsArtworksPublishedStats.timeSeries' changed type from '[AnalyticsArtworksPublishedTimeSeriesStats!]' to '[AnalyticsPartnerTimeSeriesStats!]!'
- :warning: 'AnalyticsPartnerTimeSeriesStats' kind changed from 'InterfaceTypeDefinition' to 'ObjectTypeDefinition'
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 44ed1b7e38f2a159b0fbf639dcec3c07b838f4a5
</p>

**Comment by eessex** [comment]
This PR has run 5 time without any failures, so I'm feeling hopeful. We are no longer seeing `[bluebird-Q] Unhandled rejection reasons` or `UnhandledPromiseRejectionWarning` which seem to be the culprits of the random failures.

**Comment by zephraph** [comment]
I'll dig in shortly

**Comment by zephraph** [comment]
👍

**Pull request merged**
