### PR TITLE
WIP:bug:ensure image in partner artist rail is scoped to partner

### PR DESCRIPTION
**Pull request by nspinazz89**
The type of this PR is: Fix

This PR solves [:px-5309]
### Description

This PR reverts back to the old way we had the artist rail because the recent change was no longer scoping to specific Partner. 

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dzucconi** [comment]
We don't want to do this

**Review by dzucconi — CHANGES_REQUESTED** [review]
We don't want to use this UI. The only issue is the href? If so that's fine we can support a custom href in the Cell

**Comment by dzucconi** [comment]
In fact you barely need to do anything here: `Cell` supports the `to` attr — so just use it.

**Comment by nspinazz89** [comment]
> We don't want to use this UI. The only issue is the href? If so that's fine we can support a custom href in the Cell

The issue isn't just the href, it's that the large square image shown for an artist in a rail isn't scoped to a partner artist. As an example, the gallery Robin Rile Fine, currently if you were to visit, https://staging.artsy.net/partner/robin-rile-fine-art and scroll down to Banksy you would see the the "Kissing Coppers" image which is not a work that this gallery has. 
image
vs my local branch after reverting back to the way we had previously had it.
image

I think the problem is with the graphql query itself, but was hesitant to change the query directly in the CellArtist component as I had assumed it was a more general component that was being used elsewhere....but having double checked that I don't see it being imported anywhere else so I will go and change that component directly now.

**Comment by dzucconi** [comment]
OH — alright I see. In which case we'll want to make a new Cell component. Say: `CellPartnerArtist` following the patterns laid out in `CellArtist`

**Comment by nspinazz89** [comment]
> OH — alright I see. In which case we'll want to make a new Cell component. Say: `CellPartnerArtist` following the patterns laid out in `CellArtist`

Sounds good! Also I had found the ticket for the original design specified that small circular image, but that is removed by CellArtist. Was that a conscious/more recent design change? If so I will follow that convention.

**Comment by nspinazz89** [comment]
Closing this PR in favor of https://github.com/artsy/force/pull/11462 which takes a better approach via new CellPartnerArtist Component.

**Pull request closed without merging**
