### PR TITLE
feat:redirect to conversation when user click submit in Review

### PR DESCRIPTION
**Pull request by alexj105**
When a user has gone through the checkout flow and clicked submit on the Review page they are redirected back to the message conversation screen. 
https://artsyproduct.atlassian.net/browse/PURCHASE-2715

### CODE REVIEW

**Comment by damassi** [comment]
@alexj105 If this PR is ready to review, mind adding a description, a link to the associated JIRA ticket, and assign to someone for review? If _not_ ready for review then we generally update the PR title and body with `WIP` so that folks know things are still in flux.

**Comment by alexj105** [comment]
> @alexj105 If this PR is ready, mind adding a description, a link to the associated JIRA ticket, and assign to someone for review? If _not_ ready for review then we generally update the PR title and body with `WIP` so that folks know things are still in flux. 

No, just create fo myself to check files, that  were changed

**Comment by damassi** [comment]
This LGTM but will reassign to someone on the purchase team to merge 👍 cc @lilyfromseattle

**Review by xtina-starr — APPROVED** [review]
This looks good to me 👍  I will go ahead and merge.

**Pull request merged**
