### PR TITLE
[GRO-734] use graphql query for artwork to render artwork rail 

### PR DESCRIPTION
**Pull request by TMcMeans**
PR is still a WIP, but also I need to clean up the commit history because its pulling commits from my other PR in. Still figuring out how to split PRs from branches that are created from another branch with separate code from the same file. Thanks for being so confusing, git! 

Update: PR is no longer a draft and ready to be merged

### CODE REVIEW

**Comment by TMcMeans** [comment]
I know the commit history is a mess and some of the commits are duplicated from my other PR... I have to look at it again in the morning.

**Comment by TMcMeans** [comment]
okay, all ready to merge once the tests pass!

**Review by damassi — DISMISSED** [review]
Looks good! 🚢

**Comment by TMcMeans** [comment]
`detect-secrets `is hating me today... it thinks the artwork ids I passed in shouldn't be merged.

**Pull request merged**
