### PR TITLE
GRO-548: [Mobile] Trending Artists on Artsy - CTA link is wrapping

### PR DESCRIPTION
**Pull request by The-Beez-Kneez**
Current Behavior:
Screen Shot 2021-12-06 at 2 00 43 PM

New Behavior:
https://user-images.githubusercontent.com/30025439/145096403-cea9fa79-f3bf-456a-80a9-866d00eda3f3.mov

### CODE REVIEW

**Comment by The-Beez-Kneez** [comment]
@dzucconi would love to clarify if this was what Jonathan was referring to.

**Review by dzucconi — CHANGES_REQUESTED** [review]
So you're going to want to find the `viewAllLabel` text inside of the `RailHeader` and text align that. Replicate by viewing the component at a mobile viewport.

**Comment by dzucconi** [comment]
You want to replicate by forcing that line of text to break. So either artificially increase the title to check or really size down your viewport.

**Comment by The-Beez-Kneez** [comment]
Updated and also included a screen recording of the functionality for the `View All` text wrapping with right alignment.

**Comment by dzucconi** [comment]
It's still wrapping with left alignment — let's pair on the solution.

**Review by dzucconi — COMMENTED** [review]
`HomeFeaturedMarketNewsContainer` also has an `Explore Editorial` string that needs the alignment updated

**Comment by The-Beez-Kneez** [comment]
@dzucconi updated following our pairing and discussion.

**Review by dzucconi — APPROVED** [review]

**Pull request merged**
