### PR TITLE
feat(performance): Add experimental support for "prefetch on viewport enter" 

### PR DESCRIPTION
**Pull request by damassi**
- Gated behind `diamond_prefetch-on-enter` FF

### Description

This adds support for prefetching links on viewport enter. Right now this only applies to links wrapped in RouterLink. 

**Conditions**:
- `diamond_prefetch-on-enter` flag is enabled
- Link is in viewport 
- User is **not logged in** (part of the aim is to generate more cache hit coverage) 

**Behavior**: 
- Once intersection observer executes, its detached, and we don't attempt to prefetch again (via `once` prop on hook)

As discussed below, with logged in users + lazy-loaded artwork grids, things don't feel quite right. Pages transition instantly, yet there's still always this glaring fetch of the grid on key pages. 

For logged out, there's enough cache entries (and soon to be more) to where this doesn't matter as much, but when logged in, where we're still required to fetch a lot of content, it feels like too much gray. We need to either prefetch the grids as well, or remove the lazy loaded grids before we enable for logged in. 

But when we do, logged in starts to feel like the fully-cached logged out exp (assuming MP server doesn't start going crazy!) We're going to monitor. 

cc @artsy/diamond-devs

### CODE REVIEW

**Comment by mzikherman** [comment]
This seems pretty chill w/ not much here(!) - assuming we want to go this route. I'm 👍 for at least running this in prod (maaaybe behind an ENV var/feature flag so we can turn off) to see how metrics (esp backend look).

@joeyAghion probably has thoughts on any backend perf implications (we are gonna be sending _more_ requests there, but it's probably hard to estimate how many more and how it'll look when in prod).

Either way, it feels like an even broader layer than the 'prefetch on hover' which works quite well, so I'm very much down for merging this in (_perhaps_ guarded by a flag/on a trial basis, but whatever).

**Comment by damassi** [comment]
Yah this could be crazy, it'd be interesting to do a brief test to see what happens. Site is already feeling fast as it is, but the logged in aspects of this might make it worth it. 

I'm a bit intrigued tho about our images and investigating that a bit. If there's some loading states having images load too doesn't feel bad, but when we're dealing with largely instant states like we are here, the time it takes for the images to appear is conspicuous.

**Comment by damassi** [comment]
Actually, i just realized what it is. 

I keep needing to remember that we're logged-in. There's still a lazy fetch going on on the grids, which will always take a second to render, because those aren't prefetched with the route. That's whats going on. 

Ugh! I guess its a good problem to have. 

Logging out, grids and images (cached from network) all load totally fine (and instant).

**Comment by mzikherman** [comment]
(discussed in Slack - let's add a feature flag for this and just do it for logged-out visitors, then we can merge)

**Review by mzikherman — APPROVED** [review]

**Pull request merged**
