### PR TITLE
Update copy on bidder registration form

### PR DESCRIPTION
**Pull request by dblandin**
Update copy used during bidder registration.

While we're working on the new components in artsy/reaction, this updates copy for the registration form within Force.

zeplin spec :lock:: https://zpl.io/Vx64vA3

cc/ @dleve123 @williardx 

## Before

screenshot 1565024218
screenshot 1565024207

## After

screenshot 1565033272

screenshot 1565024193

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The staging version of Metaphysics has breaking changes, this might not affect your build, but could mean your queries don't work the way you expect. See below for breaking changes:</td>
    </tr>
  </tbody>
</table>


- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOrder.lastApprovedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOrder.lastSubmittedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOrder.stateExpiresAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOrder.stateUpdatedAt'
- :warning: Field 'CommerceLineItem.createdAt' changed type from 'CommerceDateTime!' to 'String!'
- :warning: Field 'CommerceLineItem.updatedAt' changed type from 'CommerceDateTime!' to 'String!'
- :warning: Field 'CommerceFulfillment.createdAt' changed type from 'CommerceDateTime!' to 'String!'
- :warning: Field 'CommerceFulfillment.estimatedDelivery' changed type from 'CommerceDate' to 'String'
- :warning: Field 'CommerceFulfillment.updatedAt' changed type from 'CommerceDateTime!' to 'String!'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceBuyOrder.lastApprovedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceBuyOrder.lastSubmittedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceBuyOrder.stateExpiresAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceBuyOrder.stateUpdatedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOffer.submittedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOfferOrder.lastApprovedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOfferOrder.lastSubmittedAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOfferOrder.stateExpiresAt'
- :warning: Argument 'convert_to_utc: Boolean' was removed from field 'CommerceOfferOrder.stateUpdatedAt'
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e661af76f10437bb4cbfbd26800c7750b7b6c6b2
</p>

**Comment by dleve123** [comment]
@dblandin In this screenshot 

screenshot 1565024176

There are 2 periods after "win". Is that still the case? Doesn't seem like that should be present after reviewing the code.

**Comment by dblandin** [comment]
> There are 2 periods after "win". Is that still the case? Doesn't seem like that should be present after reviewing the code.

@dleve123 No, that's no longer the case. Just updated the screenshot :+1:

**Comment by yuki24** [comment]
LGTM 👍

**Pull request merged**
