### PR TITLE
Upgrades reaction-force and remounts the loyalty app

### PR DESCRIPTION
**Pull request by l2succes**
Updated reaction-force and remounts the loyalty program app

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a PR summary</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by alloy** [comment]
Electron?? Why do we have that in our deps?

**Comment by l2succes** [comment]
I was wondering that too, I think it's for the integration tests but not 100% sure.

**Comment by alloy** [comment]
Ah yeah, indeed https://github.com/artsy/force/blob/ffc278d9ece45480635dde73601dbc67323637b8/yarn.lock#L4865

**Pull request merged**
