### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by kanaabe**
cc @gnilekaw @l2succes @nicholassewitz @eessex @sweir27 @damassi @cavvia

### CODE REVIEW

**Comment by craigspaeth** [comment]
Yay! Just a heads up—this includes a [change to the asset pipeline](https://github.com/artsy/force/pull/1311) that seems to have worked fine for staging, but probably good to keep an eye on this deploy regardless.

**Comment by ArtsyOpenSource** [comment]
### This deploy contains the following PRs:

- Rethinking Marketo Analytics PR:2 Fix Gallery Insights Tracking *round 2 ([#1321](https://github.com/artsy/force/pull/1321) by @nicholassewitz)
- @damassi => only load redux logger in dev and staging ([#1314](https://github.com/artsy/force/pull/1314) by @sweir27)
- @kanaabe => [Venice] Completed video cover ([#1318](https://github.com/artsy/force/pull/1318) by @eessex)
- @sweir27 : search static pages in global search ([#1313](https://github.com/artsy/force/pull/1313) by @cavvia)
- @eessex => [Venice] Video close, ready, adaptive streaming, smooth scrubbing ([#1317](https://github.com/artsy/force/pull/1317) by @kanaabe)
- Update circle script with new assets script ([#1316](https://github.com/artsy/force/pull/1316) by @craigspaeth)
- @craigspaeth => Update CONTRIBUTING.md  ([#1315](https://github.com/artsy/force/pull/1315) by @damassi)
- @damassi: Add bundle splitting via factor-bundle ([#1311](https://github.com/artsy/force/pull/1311) by @craigspaeth)
- @craigspaeth => [Venice] Fixes test and onbeforeunload tracking ([#1310](https://github.com/artsy/force/pull/1310) by @kanaabe)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by kanaabe** [comment]
@craigspaeth Hmm, I've rebuilt this twice and it keeps getting stuck on a heroku staging deploy. Not sure if a staging deploy should even be happen on this build but do you have any idea?

**Comment by craigspaeth** [comment]
The staging build happens on [merges to master](https://circleci.com/gh/artsy/force/1142) so this build just runs tests. You can even feel free to just merge these PRs without waiting for the build b/c the latest build would have already run tests in the last PR that was merged _and_ it will run again before deploying.

**Pull request merged**
