### PR TITLE
@kannabe => Team Channel QA

### PR DESCRIPTION
**Pull request by eessex**
Header was causing a width scrollbar to appear in staging, this fixes it from overflowing.

### CODE REVIEW

**Comment by kanaabe** [comment]
Hm looks like semaphore needs to be kicked here

**Comment by eessex** [comment]
Getting a weird error, "This pull request is not mergeable, so Semaphore cannot build it. Please check your pull request to resolve conflicts."

Have you experienced this one before?

**Comment by kanaabe** [comment]
Hmm usually if you add another commit or rebase and force push, it will kick it. Hopefully that works!

**Comment by eessex** [comment]
Thanks, a new commit did the trick :green_heart:

**Pull request merged**
