### PR TITLE
Use styled components

### PR DESCRIPTION
**Pull request by gnilekaw**
This PR switches out Stylus for styled-components, collapses columns for mobile, and does some minor housekeeping.

apr-07-2017 08-25-12

### CODE REVIEW

**Comment by oxaudo** [comment]
Looks and works great!

Below, not really affecting this pr my random thoughts while reading the code here:

- I'm still trying to understand the advantage of Styled Components here vs the plane old css that we had before. I personally find that it's much harder for me to grasp how things relate to each other on the page when styles for them scattered all over multiple files. But that might not be the case once this page gets more complex and it would make sense that each component is independent visually and it does not really care much how it relates to other things on the page.

- The other issue that I'm wondering - how would this deal with the changes while the look of the page is so much in flax. For example: We've created `<StyledH2>` to represent `<h2>` in the html in one case and `<Heading>` which is defined as `styled.h3` in the other case. So in the page html we'll have tags like `<StyledH2>` and `<Heading>` in some order. There is no easy way to recognize/realize that those are `<h2>` and `<h3>` tags respectively and they play `artsy-intro-heading` and `gene-family-heading` roles respectfully. I guess I'm a bit confused how we are mixing html names with the roles that they play on the page here. And if the structure of the page changes and we want to introduce another let's say `genome-project-heading` which should take the `h3` tag and `Heading` will become and `h4` tag - would we need to change the name of component + styles instead of just reassigning the class name?
Also this seems to go a bit against suggestions here: https://en.bem.info/methodology/quick-start/ or I'm not really understanding those properly:(

But maybe all my questions are a bit pointless here and things will fall into places for me once I start using it more. Thanks for reading all this musings:) Will be happy to hear your thoughts on the above @gnilekaw and @anandaroop.

**Comment by oxaudo** [comment]
It does look/play much better - so merging it now. I believe we'll discuss css approaches/best practices much more separately from this anyways.

**Comment by anandaroop** [comment]
@oxaudo these are all very good questions...

> still trying to understand the advantage of Styled Components here vs the plane old css 

Styled components will give us a guarantee that our css won't have side effects anywhere else, because of the way it generates unique class names for the DOM and the generated styles.

It will also give us the ability to use props and real JS inside of style definitions which helps with dynamic styles and generating style variations. (Bonus: no new Stylus/Sass/Compass/PostCSS syntax to learn; *it's just Javascript*&trade;)

Also gives us a nice and very useful subset of the features you get from other css frameworks: vendor prefixing, nested style definitions, e.g.

I think it will all become clearer as we see more examples.

> much harder for me to grasp how things relate to each other on the page when styles for them scattered all over multiple files 

Yeah I totally get that. I think we'll have to find a balance between keeping together styles which makes sense together — e.g those describing the general layout structure of a page — versus those that can be safely tucked away with their (small, focused) components. In the latter case, I'm actually finding it refreshing _not_ to be confronted with those styles until and unless I actually care about changing them.

> that might not be the case once this page gets more complex and it would make sense that each component is independent visually

I think that's exactly right. 

As for the second bullet point — @gnilekaw and I had a chat today and will be substantially revising the styled components implementation in this PR. I think the new version will address some of your concerns. Also re: BEM — it's a good convention to follow if we are using Stylus, but it is one of the things we can (probably) forget about with Styled Components 🎉 .

**Comment by mxstbr** [comment]
:tada:

This is awesome! If you have any questions or issues, feel free to ping me and I'll happily answer anything. Let me know how it goes, too :blush:

**Pull request merged**
