### PR TITLE
Renamed browse page.

### PR DESCRIPTION
**Pull request by dblock**
The Browse title is probably the least desirable SEO-wise, renamed to Collect.
Closes https://github.com/artsy/force/issues/1182.

cc: @christine-artsy

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please assign someone to your PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mzikherman** [comment]
Works for me!

**Comment by NicoletteChao** [comment]
@dblock and @mzikherman thanks for handling this!

Collect Art & Design Online | Artsy would probably be the best title tag since it makes the most use out of the real estate.  Collect | Artsy is a definite improvement from "Browse" though. Either are acceptable!

As for the meta description, "find art" I think is totally fine, in fact "find art" gets more search volume than "collect art", although it may be a little off-brand.

**Comment by dblock** [comment]
I'm a little worried that renaming it to "Collect Art & Design Online" will take over or sound duplicate in comparison with our homepage, which is "Artsy - Discover, Research, and Collect the World's Best Art Online". Lets try just Collect for now and see whether there's any impact on Google's result for "Collect Art & Design Online" in a few. @mzikherman merge at will

**Comment by NicoletteChao** [comment]
Ah right, that makes sense. Thanks!

**Pull request merged**
