### PR TITLE
Feat(CX-3373): Collector Profile breadcrumb in Settings

### PR DESCRIPTION
**Pull request by lordkiz**
The type of this PR is: **Feat**

This PR solves [CX-3373]

### Description
- Replaces the Settings Heading with a collector profile breadcrumb.
- 

Screenshot 2023-02-06 at 18 47 52
Screenshot 2023-02-06 at 18 47 29

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3373]: https://artsyproduct.atlassian.net/browse/CX-3373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dariakoko — APPROVED** [review]
Thanks Kizito!
Just one question: is the spacing correct? according to the design it should be 6 under the Back link (4 is the spacer and 2 is mt of the tab)
image

**Review by olerichter00 — DISMISSED** [review]

**Comment by lordkiz** [comment]
> Thanks Kizito! Just one question: is the spacing correct? according to the design it should be 6 under the Back link (4 is the spacer and 2 is mt of the tab) image

@dariakoko There is paddingVertical of 2 on the breadcrumb container making it a total of 6 I suppose. Do you mean 6 including the margin on the tab?

**Comment by dariakoko** [comment]
@lordkiz looks like there should be also paddingTop of 2 for the tabs or we could use <Spacer y={6} /> instead of <Spacer y={4} /> 👀

**Comment by lordkiz** [comment]
> @lordkiz looks like there should be also paddingTop of 2 for the tabs or we could use instead of 👀

Ahh. Ok. You recommend I reduce the Spacing below by 2?

**Comment by dariakoko** [comment]
Always forget i can't add a line of code without "add the code" formatting...
I mean:
Looks like there should be also paddingTop of 2 for the tabs or we could use `<Spacer y={6} />` instead of  `<Spacer y={4} />`👀

**Comment by MounirDhahri** [comment]
@lordkiz would you mind updating the Integrity e2e test as well

**Comment by lordkiz** [comment]
@MounirDhahri Sure

**Pull request merged**
