### PR TITLE
@xtina-starr => Deprecate Professional Buyer program

### PR DESCRIPTION
**Pull request by kanaabe**
Closes: https://artsyproduct.atlassian.net/browse/GROW-752

### CODE REVIEW

**Comment by joeyAghion** [comment]
🥂 for deprecating and removing!

@mzikherman I recall there being some back-end work around this program. What else might need clean-up?

**Comment by mzikherman** [comment]
Yea! There's some timestamp fields on `User` (time they applied/confirmed for the prof buyer), I _think_ a Torque checkbox for them to be confirmed? Also we ping Sailthru when someone applies/confirms with a little email (the email lives wholly in sailthru, our ping is more like 'send this email').

**Comment by kanaabe** [comment]
Ah thanks @mzikherman!

**Comment by xtina-starr** [comment]
This looks 👌

**Comment by xtina-starr** [comment]
I believe this is all that's needed on the force side so I'm going to go ahead and merge.

**Pull request merged**
