### PR TITLE
[artwork2] Make client side markup match server side rendered results

### PR DESCRIPTION
**Pull request by alloy**
We really need to get rid of these containers, but for now just need to make sure to match on the client what we render on the server.

### CODE REVIEW

**Comment by oxaudo** [comment]
Not sure I understand how only the banner rendering was messed up by not having the container around the app originally, but the change looks reasonable.

@damassi - cool to merge you think?

**Comment by damassi** [comment]
If it fixes the issue i'm 👍 

@alloy curious if you have any theories on why things are becoming more sensitive reconciler-wise? I know we're doing more (that could be the answer :) but we never used to run into elements switching spots and so on.

**Comment by alloy** [comment]
Hard to say what exactly led up to this rehydration issue, but I assume it’s a combination of us not rendering large parts of the page at all on the server previously combined with us purposefully _not_ rendering inactive breakpoints at all on the client.

I wish I had a more satisfying answer, but the reality is probably that because we’re exercising the rehydration code much more nowadays it’s more prone to little errors in markup, such as this issue, leading to layout failures. I don’t think we need React to be relaxed with such errors.

There’s also the issue that because we’re retrofitting all of this work it suddenly unearths issues in places that nobody is actively working on. Going forward I expect people to run into errors as soon as they write them and better know how to fix, just as with any other error.

**Comment by damassi** [comment]
👍 ty

**Pull request merged**
