### PR TITLE
toolchain: Add object keys sort lint autofixer

### PR DESCRIPTION
**Pull request by damassi**
Follow-up to cohesion PR. Updated our ESlint config with an auto-fixer for sorting object keys: 
- [object keys](https://www.npmjs.com/package/eslint-plugin-sort-keys-fix)

### CODE REVIEW

**Review by icirellik — COMMENTED** [review]
(blocking) I was wondering if there was any reason you favor the `eslint-plugin-simple-import-sort` plugin over the much more popular and feature rich `eslint-plugin-import`, I plan on adding the latter to enforce default export standards when we can.

**Comment by damassi** [comment]
> favor the eslint-plugin-simple-import-sort

No reason other than that's what I've used before. Can swap it out 👍

**Comment by damassi** [comment]
Have removed `eslint-plugin-simple-import-sort` for now and reduced scope of PR to just object key sorting

**Review by icirellik — APPROVED** [review]

**Comment by icirellik** [comment]
Thanks, I was originally going to ask to have them broken out into separate PRs. It seemed like a lot of effort for something so simple. Are you aware of any reason why eslints builtin object key sort doesn't have an autofix?

**Comment by damassi** [comment]
> Are you aware of any reason why eslints builtin object key sort doesn't have an autofix

Not too sure after looking around, but seems like it should, right? Maybe it was a conscious decision because object keys can be deliberately ordered by hand, though I've never seen that done with intention before.

**Pull request merged**
