### PR TITLE
@alloy - Fix /tag page on logged out and upgrade reaction-force

### PR DESCRIPTION
**Pull request by broskoski**
Closes https://github.com/artsy/reaction-force/issues/153

Was actually bad logic that caused the code not to work on when the user is logged out, not a weird rewire thing!

### CODE REVIEW

**Comment by broskoski** [comment]
artwork-filter-save

**Comment by alloy** [comment]
Oh I see why I got confused, we got ourselves a little duplication going on 'ey?

Can't you import the network layer function from `reaction-force/dist/relay/config`

**Comment by broskoski** [comment]
Good call

**Comment by alloy** [comment]
Looks perfetto 👌

Merge at will.

**Pull request merged**
