### PR TITLE
Fix deployment failure due to "An unexpected error occurred: "Invalid protocol: git:"."

### PR DESCRIPTION
**Pull request by yuki24**
I just followed [the suggestion here](https://github.com/yarnpkg/yarn/issues/1625#issuecomment-314615392). I'm not sure if it fixes the issue, but I think it's worth giving it a try.

### CODE REVIEW

**Comment by damassi** [comment]
@yuki24 - which package did you end up upgrading? All that have `git://`?

**Comment by yuki24** [comment]
@damassi It's `artsy-xapp`. I manually commented out the `artsy-xapp@^1.0.4, "artsy-xapp@git://github.com/artsy/artsy-xapp.git":` block and ran `yarn upgrade artsy-xapp`.

**Comment by damassi** [comment]
🤞

**Comment by yuki24** [comment]
Thanks! Let's see how the deploy goes...

**Pull request merged**
