### PR TITLE
feat: use react-stickynode and refactor Sticky component

### PR DESCRIPTION
**Pull request by dimatretyak**
Type: **Enhancement**

### Description
Use `react-stickynode ` dependency to implement sticky component instead of custom implementation

#### Fair
staging: https://staging.artsy.net/fair/one-x-artsy
review app: https://sticky.artsy.net/fair/one-x-artsy

#### Categories
staging: https://staging.artsy.net/categories
review app: https://sticky.artsy.net/categories

#### Partner
staging: https://staging.artsy.net/partner/konig-galerie
review app: https://sticky.artsy.net/partner/konig-galerie

#### Alert
Example with sticky/unsticky behavior
review app: https://sticky.artsy.net/user/alerts

https://user-images.githubusercontent.com/3513494/152988102-63616338-6601-46e1-b389-6b322097b844.mp4

### CODE REVIEW

**Comment by dzucconi** [comment]
I think this looks pretty good and is the way to go forward.

But, take a look at one instance where things are visibly different.

https://staging.artsy.net/partner/konig-galerie/works vs https://sticky.artsy.net/partner/konig-galerie/works on mobile. Which is an instance of stacking. I'd also make sure the stacking story looks correct: https://force-storybook.artsy.net/?path=/story/components-sticky--example

------

I don't _love_ adding a dependency obviously but the bulk of this is corejs and lodash which should already be in the application anyway.



I'd still like to revive my dream to implement the full range of sticky using intersection observers... was pretty close to finishing that, actually.

-------

Ideally we just switch this to use native code once `overflow: clip` lands in Safari/mobile Safari and it reaches a majority of our users. Falling back to static positioning in older browsers isn't such a big deal.

**Comment by dimatretyak** [comment]
> https://staging.artsy.net/partner/konig-galerie/works vs https://sticky.artsy.net/partner/konig-galerie/works on mobile. Which is an instance of stacking

My bad. Fixed

**Review by dzucconi — APPROVED** [review]
Great! Thanks for seeing this through.

**Comment by dimatretyak** [comment]
> I'd also make sure the stacking story looks correct: https://force-storybook.artsy.net/?path=/story/components-sticky--example
Here is a small demo

### Mobile
https://user-images.githubusercontent.com/3513494/153032886-ab170e83-1d49-4ff3-8c36-00b9f731de34.mp4

### Desktop
https://user-images.githubusercontent.com/3513494/153032924-4c86895c-ba04-4aab-9a5c-68069122da88.mp4

**Comment by dzucconi** [comment]
Looks fine but note you can also just run the story locally with `yarn storybook`

**Comment by dimatretyak** [comment]
> Looks fine but note you can also just run the story locally with `yarn storybook`

Ooo, thanks for the advice, didn't know about it

https://user-images.githubusercontent.com/3513494/153034566-ec124f56-0178-469e-ba7c-b7da168f2835.mp4

**Comment by dzucconi** [comment]
👌

**Pull request merged**
