### PR TITLE
chore(FX-4527): updated the logic of displaying the "contact gallery" button for the partner

### PR DESCRIPTION
**Pull request by dimatretyak**
The type of this PR is: **Chore**

This PR solves [FX-4527]

Slack thread: https://artsy.slack.com/archives/C9SATFLUU/p1671572593811379

Review app: [contact-gallery-button](https://contact-gallery-button.artsy.net/)

#### Cases when "Contact Gallery" should be displayed
* [54a0c3707261692d00270f00](https://contact-gallery-button.artsy.net/artwork/54a0c3707261692d00270f00)
* [54b15f687261695ec5d00600](https://contact-gallery-button.artsy.net/artwork/54b15f687261695ec5d00600)
* [54d35d017261693e67980a00](https://contact-gallery-button.artsy.net/artwork/54d35d017261693e67980a00)
* [54a0c3f47261692e08980400](https://contact-gallery-button.artsy.net/artwork/54a0c3f47261692e08980400)
* [54b14a4d72616959e5bb0600](https://contact-gallery-button.artsy.net/artwork/54b14a4d72616959e5bb0600)

#### Cases when "Contact Gallery" should NOT be displayed
* [5c05a7426238c108b3fe18e9](https://contact-gallery-button.artsy.net/artwork/5c05a7426238c108b3fe18e9)
* [54a0e0487261692e35250e00](https://contact-gallery-button.artsy.net/artwork/54a0e0487261692e35250e00)
* [54a567ad7261693b03600300](https://contact-gallery-button.artsy.net/artwork/54a567ad7261693b03600300)
* [54a56c5b7261692b45200000](https://contact-gallery-button.artsy.net/artwork/54a56c5b7261692b45200000)

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-4527]: https://artsyproduct.atlassian.net/browse/FX-4527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by joeyAghion — APPROVED** [review]
Thanks for the fix!

The purpose of all those `isInquireable`, `isAcquireable`, `isOfferable`, … properties was to save clients the trouble of applying their own logic (and to ensure the logic was consistent and correct). If there is new view logic that can’t rely on those directly, maybe we need a new back-end/Metaphysics property, to prevent this type of bug in the future?

**Review by anandaroop — APPROVED** [review]
🙏🏽

**Comment by dimatretyak** [comment]
> The purpose of all those `isInquireable`, `isAcquireable`, `isOfferable`, … properties was to save clients the trouble of applying their own logic (and to ensure the logic was consistent and correct). If there is new view logic that can’t rely on those directly, maybe we need a new back-end/Metaphysics property, to prevent this type of bug in the future?

I think we can add a new field for artwork on Metaphysics and then use this field on the frontend side. What do you think about this?

#### Metaphysics
```javascript
export const ArtworkType = new GraphQLObjectType<any, ResolverContext>({
  ...
  fields: () => {
    return {
      ...
      canDisplayContactGalleryButton: {
        type: new GraphQLNonNull(GraphQLBoolean),
        resolve: ({ acquireable, inquireable, offerable }) => {
          return !inquireable && (acquireable || offerable)
        },
      },
      ...
    }
  },
})
```

### Frontend
```javascript
{isCBNEnabled && canDisplayContactGalleryButton && (
  <Button size="small" variant="secondaryBlack" onClick={handleInquiry}>
    {t("artworkPage.sidebar.partner.contactGalleryCta")}
  </Button>
)
```

**Comment by anandaroop** [comment]
In theory, no objection from me (dropping the auction condition was intentional I assume?)

But I agree that having these computed on the backend and using that as a single source of truth is probably preferable, so that we  don't have to e.g. repeat this in Eigen or make sure it stays in sync with changes in Gravity.

**Comment by dimatretyak** [comment]
Go ahead and merge this PR. if we need to add fixes/additions, then I will address it in another PR

**Pull request merged**
