### PR TITLE
[DONTMERGE] Switch to shows from partner_shows

### PR DESCRIPTION
**Pull request by ashkan18**
# Problem
We want to switch to MP's `shows` from deprecated `partner_shows`.

# Solution
Change the query to use `shows`! am i missing anything here?

### CODE REVIEW

**Comment by mzikherman** [comment]
It looks like the root-level server side query as well for a show page: https://github.com/artsy/force/blob/b2128d69d3f856a76d8ce87c4f860bcf2327f844/src/desktop/apps/show/routes.coffee#L10

I would just go thru the query on the show page and make sure its using `Show` not `PartnerShow`, and then if the page still renders- we're good!

**Comment by ashkan18** [comment]
Updated that query to also use `show` instead of `partner_show` but im getting error when going to show page, my guess is something is not moved over to `show`

**Comment by mzikherman** [comment]
Let me know if you need help! It _might_ be the case that things aren't in `Show`, but `Show` started as a copy of `PartnerShow`, and then we've been adding to it (and to `PartnerShow`) so it should have everything.

**Comment by eessex** [comment]
We use `partner_shows` in positron as well, should I be updating to use the new field name?

**Comment by ashkan18** [comment]
@mzikherman im going to close this since haven't had a chance to look at the failure :(

**Pull request closed without merging**
