### PR TITLE
push update asset config for k8s on deploy

### PR DESCRIPTION
**Pull request by saolsen**
update ASSET_MANIFEST on k8s

### CODE REVIEW

**Comment by joeyAghion** [comment]
Is this script guaranteed to run before the hokusai deploy/promote? It's frustratingly difficult to tell this from the `.circleci/config.yml` workflow definitions.

**Comment by saolsen** [comment]
Right now it runs as part of the heroku deploy which runs concurrently with the k8s deploy. We could make it so the heroku one always runs first or take it further and factor it out into it's own step.

**Comment by joeyAghion** [comment]
Whichever is easier! I'd fear the current approach would break a noticeable proportion of the time.

Making it a separate asset task simplifies the later transition away from Heroku, but at that point we might want to combine it with the single deploy step anyway. Maybe assets should be built and configured in _both_ tasks for now.

**Comment by joeyAghion** [comment]
As discussed, will merge as-is for now. I recommend an update to make this strictly-ordered before switching staging DNS.

**Pull request merged**
