### PR TITLE
chore: deletes personalize app (onboarding)

### PR DESCRIPTION
**Pull request by dzucconi**
This PR deletes the personalize app + routes. I've included redirects to the homepage on the off chance something else is linking to them.

I suspect some integrity specs will fail here as well. Will convert off draft after I have a PR fixing those.

### CODE REVIEW

**Comment by dzucconi** [comment]
There's some peripheral clean up here to do too. Like how Cohesion requires an `onboarding` flag for it's `CreatedAccount` event:

**Comment by dzucconi** [comment]
https://github.com/artsy/integrity/pull/323

**Comment by The-Beez-Kneez** [comment]
https://media.giphy.com/media/gg2VBE0zVrMGUutcwy/giphy.gif

**Comment by jonallured** [comment]
Pretty funny to think of this as a chore haha - let's do it!

**Pull request merged**
