### PR TITLE
DISCO-629: Remove unused MarketInsights components for Artwork page

### PR DESCRIPTION
**Pull request by dblandin**
This pull request removes a reference to a Market Insights component in reaction directly inserted via Force.

This component does not seem to be in-use currently. Instead, it looks like we're inserting a newer Market Insights component which is part of the new Responsive Artwork Page in artsy/reaction.

This also unblocks removal of the older component in artsy/reaction.

ticket: https://artsyproduct.atlassian.net/browse/DISCO-629 :lock:

### CODE REVIEW

**Comment by damassi** [comment]
@dblandin - This is actually the same component from Reaction that's currently used in the new pages. Normally we use stitch to inject these things but this basically does the same thing.

**Comment by dblandin** [comment]
@damassi I'm still a little confused.

It looks like the new responsive Artist page [renders](https://github.com/artsy/reaction/blob/9d487f1848ba0b17e866251e42e55d26f8597963/src/Apps/Artist/Routes/Overview/index.tsx#L16) the [Styleguide/Components/MarketInsights.tsx](https://github.com/artsy/reaction/blob/master/src/Styleguide/Components/MarketInsights.tsx) component and [uses just one exported function](https://github.com/artsy/reaction/blob/9d487f1848ba0b17e866251e42e55d26f8597963/src/Apps/Artist/Routes/Overview/index.tsx#L7) from the [Components/Artist/MarketInsights/MarketInsights.tsx](https://github.com/artsy/reaction/blob/master/src/Components/Artist/MarketInsights/MarketInsights.tsx) component (referenced in this PR).

The component referenced in this diff doesn't seem to be rendered anymore. I can't find the mount element id format referenced in any Force template.

Running this diff locally, the current version of Artist insights still show up, leading me to believe that the rendering is now handled within reaction and isn't needed here.

**Comment by damassi** [comment]
Ah, you are indeed correct -- looks like this is now a part of the ArtistInfo component, which is rendered in its entirety [into the old page](https://github.com/damassi/force/blob/9f1f6e8203b891897ffb153e22a02da1c1f4bf21/src/desktop/apps/artwork/components/artists/index.jade#L3) via stitch. Carry on :)

**Comment by oxaudo** [comment]
Oh, sorry for delay notice here. You are absolutely right. That was before we rendered the whole thing from reaction.

In fact I think there might be 2 market insights implementations in Reaction itself where one of those is unused any more. We probably need to find some time to go through components in reaction and try to clean up unused ones.

**Pull request merged**
