### PR TITLE
@alloy [MERGE AND DEPLOY JAN 31] remove all references to eoy

### PR DESCRIPTION
**Pull request by 1aurabrown**
closes https://github.com/artsy/collector-experience/issues/80

this is definitely all the occurrences of `eoy`, in some cases dependencies like Q were introduced to handle the additional request, i think i got them all out if they became unnecessary after removing the EOY code.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
actually, i didn't think to clarify this: do we want to remove the EOY editorial itself, or only links to it? if not then i'll change this.

**Comment by kanaabe** [comment]
@1aurabrown definitely just those promotional headers on the home page! and maybe the artist page callouts? the feature itself will live 4eaeae. also please don't remove analytics related to the feature!

**Comment by alloy** [comment]
We just want to remove the code we added as part of https://github.com/artsy/collector-experience/issues/69 (see the issues linked from there)

That’s basically:
* The list of featured artists on the `/artists` page
* The “this artist is featured in the EOY article” banner on each individual artist page

**Comment by alloy** [comment]
Also, funny, I’m actually travelling back to the Netherlands on the 31st, so I’ll re-assign this to @broskoski.

**Comment by 1aurabrown** [comment]
@kanaabe @tayapage6 indicated that it should be removed from the artists page and individual artist pages. i should then remove the corresponding analytics to those specific pages, i take it? https://github.com/artsy/collector-experience/issues/80

**Comment by 1aurabrown** [comment]
i reverted everything except the inclusion of EOY components on the artists and artist pages! this should be good to go on the 31st now.

**Comment by broskoski** [comment]
Mergin!

**Pull request merged**
