### PR TITLE
Removes "Text Me a Download Link" from About page

### PR DESCRIPTION
**Pull request by ashleyjelks**
https://artsyproduct.atlassian.net/browse/FX-1483

After:
Screen Shot 2020-03-20 at 2 05 32 PM

Before:
Screen Shot 2020-03-20 at 2 42 48 PM

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The staging version of Metaphysics has breaking changes, this might not affect your build, but could mean your queries don't work the way you expect. See below for breaking changes:</td>
    </tr>
  </tbody>
</table>


- :warning: Type 'ConsignmentSubmissionEdge' was removed
- :warning: Type 'SubmissionCategoryAggregation' was removed
- :warning: Type 'SubmissionDimensionAggregation' was removed
- :warning: Type 'SubmissionStateAggregation' was removed
- :warning: Field 'consignmentSubmissionsConnection' was removed from object type 'Me'
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3ff71939887f9035a4b9980896eca7f9bf4ff023
</p>

**Comment by sweir27** [comment]
Looks good to me!

**Comment by joeyAghion** [comment]
Are there any other uses of this functionality in Force? I'd hope the `/about/sms` route could be cleaned up too, as well as the supporting configs like `IPHONE_APP_COPY`. If there aren't other SMS uses within Force, the `TWILIO_...` configs and `twilio` dependency could also be cleaned up.

**Comment by ashleyjelks** [comment]
> Are there any other uses of this functionality in Force? I'd hope the `/about/sms` route could be cleaned up too, as well as the supporting configs like `IPHONE_APP_COPY`. If there aren't other SMS uses within Force, the `TWILIO_...` configs and `twilio` dependency could also be cleaned up.

Yes, we are using it on one of the Venice Biennial pages: https://github.com/artsy/force/blob/9a5301403f9bf0e4abddaa82114437188c5e0b43/src/desktop/apps/editorial_features/components/venice_2017/client/index.coffee#L165

**Comment by joeyAghion** [comment]
The `/about/sms` route and `IPHONE_APP_COPY` config still seem unused to me.

**Comment by ashleyjelks** [comment]
> The `/about/sms` route and `IPHONE_APP_COPY` config still seem unused to me.

Got it, ok I'll make a ticket to track this work and follow up with a PR. Thanks for looking into this @joeyAghion !

**Comment by eessex** [comment]
We use twilio on the Venice 360 editorial feature, this component could be removed too.

**Pull request merged**
