### PR TITLE
Redirect users to login on purchase routes

### PR DESCRIPTION
**Pull request by jpotts244**
Co-authored-by: The-Beez-Kneez <sutherlandanalisa@gmail.com>

### CODE REVIEW

**Comment by jpotts244** [comment]
@The-Beez-Kneez congrats on your first PR! 🎉 

Awesome work here and nice test case.

For tracking purposes, it might be nice to add a little description about the functionality you fixed in this PR and a link to the JIRA ticket! So we can use the PR as a little bit of documentation too!
Here's a nice example from our friend Matt in the Volt repo: https://github.com/artsy/volt/pull/4798

**Comment by The-Beez-Kneez** [comment]
This PR introduces a redirect to the login page whenever a user navigates to the path `/user/purchases` and is not signed in.

Jira ticket: https://artsyproduct.atlassian.net/browse/PURCHASE-2213

**Review by mdole — APPROVED** [review]
LGTM! Nice work

**Comment by The-Beez-Kneez** [comment]
Merging this because @jpotts244 is out sick.

**Pull request merged**
