### PR TITLE
Add yarn start:ssr command

### PR DESCRIPTION
**Pull request by damassi**
Adds a new command `yarn start:ssr` as well as some docs that allows us to get around the `yarn link` issue + styled-components 4. This approach is pretty naive. (If anyone has any suggestions for a better approach please send them over!)

### CODE REVIEW

**Comment by zephraph** [comment]
Actually, I have a suggestion that I _think_ may work. What if we put a [webpack alias](https://webpack.js.org/configuration/resolve/#resolvealias) in force for styled-components that always resolved to a single location? That would ensure that webpack always resolves that import to the proper place. A babel plugin could potentially be used too if we needed it to work for node. The ultimate idea being that it's always resolved to the version we want instead of potentially the version in reaction.

**Comment by damassi** [comment]
>  What if we put a webpack alias in force for styled-components that always resolved to a single location?

This would work if we didn't JIT compile server-side content but alas.

**Comment by zephraph** [comment]
babel plugin to replace the import with an absolute path? `styled-components` -> `/home/user/force/node_moduels/styled-components`... where the path is actually correct, ha.

**Comment by damassi** [comment]
That could work! Trying to trace this stuff through deps and sub deps + how babel will pick up other .babelrc's is so mind melting.

**Comment by pepopowitz** [comment]
For the record, this `start:ssr` command doesn't work for me. I still get a blank /collect page when running it. I'll follow up via slack to see if we can pair on it some time.

**Comment by damassi** [comment]
@pepopowitz - odd! I was testing this on /collect page (and other pages). Yeah let's SH when i'm back in office, wonder what's going on.

**Pull request merged**
