### PR TITLE
chore: delete legacy a-b test code

### PR DESCRIPTION
**Pull request by mc-jones**
The type of this PR is: Clean Up

This PR solves [PLATFORM-3995]

### Description

Having run a successful [a-b test](https://artsy.slack.com/archives/C9SATFLUU/p1650395367671049), we are comfortable using `unleash` (unleash.artsy.net) for future experiments. This PR simply cleans up the legacy a-b testing implementation which is no longer needed. 

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLATFORM-3995]: https://artsyproduct.atlassian.net/browse/PLATFORM-3995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dimatretyak — DISMISSED** [review]
Nice, thank you for these changes 👍

**Comment by dimatretyak** [comment]
quick q: should we remove [this code](https://github.com/artsy/force/blob/2a44fca2fdb5363a207d582ee4390c2e9b52fbb0/src/v2/System/Analytics/trackingMiddleware.ts#L121-L131) too?

**Review by jacobherrington — APPROVED** [review]
Quickly peeked through Force and saw only the snippet @dimatretyak called out!

**Comment by mc-jones** [comment]
@dimatretyak Absolutely. Nice catch!

**Pull request merged**
