### PR TITLE
toolchain: Add React fast-refresh for hot reloading

### PR DESCRIPTION
**Pull request by damassi**
This upgrades React to 17 and adds [React fast-refresh](https://github.com/pmmmwh/react-refresh-webpack-plugin) for hot reloading. 

It is indeed fast: 

Screen Shot 2021-03-25 at 4 56 15 PM

### CODE REVIEW

**Comment by damassi** [comment]
@mzikherman @dzucconi - please keep a look out for that weird hot reload cache issue y'all were seeing...

**Comment by iskounen** [comment]
@damassi I'm seeing the following type errors after pulling the latest from `master` :

```
src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx:323:5 - error TS2345: Argument of type 'DateTimeFormatOptions' is not assignable to parameter of type 'LocaleOptions & DateTimeFormatOptions'.
  Type 'DateTimeFormatOptions' is not assignable to type 'LocaleOptions'.
    Types of property 'numberingSystem' are incompatible.
      Type 'string' is not assignable to type 'NumberingSystem'.

323     DateTime.DATE_MED
        ~~~~~~~~~~~~~~~~~

src/v2/Apps/Purchase/Components/OrderRow.tsx:94:44 - error TS2345: Argument of type 'DateTimeFormatOptions' is not assignable to parameter of type 'LocaleOptions & DateTimeFormatOptions'.
  Type 'DateTimeFormatOptions' is not assignable to type 'LocaleOptions'.

94             {orderCreatedAt.toLocaleString(DateTime.DATE_SHORT)}
                                              ~~~~~~~~~~~~~~~~~~~

src/v2/Apps/Purchase/Components/OrderRow.tsx:160:42 - error TS2345: Argument of type 'DateTimeFormatOptions' is not assignable to parameter of type 'LocaleOptions & DateTimeFormatOptions'.
  Type 'DateTimeFormatOptions' is not assignable to type 'LocaleOptions'.

160           {orderCreatedAt.toLocaleString(DateTime.DATE_MED)}
                                             ~~~~~~~~~~~~~~~~~


Found 3 errors.
```

I ran `yarn type-check` on the last coupe of commits to where it was introduced, and it seems to be in commit 0477657, but I can't figure out what change would affect this. Do you have any ideas?

**Comment by damassi** [comment]
Fixed in https://github.com/artsy/force/pull/7240, sorry bout that!

**Comment by iskounen** [comment]
Thank you! 🙌

**Pull request merged**
