### PR TITLE
Update production keepalive/header timeouts to avoid hung connections to ELB

### PR DESCRIPTION
**Pull request by zephraph**
This is related to https://github.com/nodejs/node/issues/27363

Background:

Somewhere after Node 10.13 a security fix for the slow mo attack was added to node. This caused us to see an elevated rate of 502s due to some timeout connections between the node processes and the ELB. (I won't pretend to understand all the specifics). @mzikherman updated node for force and added the these settings for staging in https://github.com/artsy/force/pull/5022, but that we never updated production... which seems important? 

I'm also going through this song and dance for metaphysics via https://github.com/artsy/metaphysics/pull/2358

### CODE REVIEW

**Comment by zephraph** [comment]
Historical context: https://github.com/artsy/force/pull/3568#issuecomment-465144230

**Comment by zephraph** [comment]
Given that production isn't currently having issues, let's hold on this.

**Comment by damassi** [comment]
@zephraph can this be closed?

**Comment by zephraph** [comment]
Oh, definitely yes.

**Pull request closed without merging**
