### PR TITLE
@sweir27 => [Feature] Add reset filters button to /auction/:id

### PR DESCRIPTION
**Pull request by damassi**
This PR adds a little `Reset Filters` button to the sidebar component that when clicked resets filter state. 

screen shot 2017-05-13 at 6 13 47 pm

**TODO:**
- [ ] Write tests

@katarinabatina - I winged it with this design; thoughts? 
cc @devangt

### CODE REVIEW

**Comment by katarinabatina** [comment]
@damassi thanks for the contribution here, to ensure continuity with other filtering on the site I'd like to think about this issue a bit more before shipping it. Mind if we park this for the moment?

**Comment by damassi** [comment]
@katarinabatina - sure thing, but note that we've had a few requests for this feature in the last week.

**Comment by katarinabatina** [comment]
@damassi good to know, in the future if you wanna make a ticket and mark it as needs design ping me and @devangt we'll get it prioritized.

**Comment by damassi** [comment]
@katarinabatina - will open ticket now. 

@sweir27 - Re /collect pages, there's no reset button that I could find, otherwise I would have piggybacked on that.

**Comment by damassi** [comment]
Closing this until CE UI revisit completes.

**Pull request closed without merging**
