### PR TITLE
Some final copy changes

### PR DESCRIPTION
**Pull request by jonallured**
This is just some final copy changes from @mdole putting the final polish on this new set password interaction. 💪

### CODE REVIEW

**Comment by sweir27** [comment]
(dare I ask) but would it be possible to add tests confirming some of the logic?

**Comment by jonallured** [comment]
Yeah, good question! Can you point me towards where these tests would go? I just took a look here:

```
src/desktop/components/auth_modal/test/view.coffee
```

But that file seems to be unit tests around the `AuthModalView` view. There was also a file for eigen in there, but that didn't seem to make sense either. I couldn't really figure out if/how this is already tested.

I'm certainly interested in improving testing here, just need a nudge in the right direction! 😀

**Comment by sweir27** [comment]
It's possible that there aren't already tests for this, but if you want to just verify the template you can add a new test file and follow an approach similar to here: https://github.com/artsy/force/blob/master/src/desktop/apps/order/test/templates.coffee

**Comment by jonallured** [comment]
Cool, thanks for the example, that helped a lot! I took a stab at this with a781b87 - how does that look to you?

**Comment by sweir27** [comment]
🙌 looks great!

**Pull request merged**
