### PR TITLE
some qa items for marketing modal

### PR DESCRIPTION
**Pull request by 1aurabrown**
Fixes responsive layout issues in https://github.com/artsy/collector-experience/issues/148

Some tweaks to accomplish the three responsive styles outlined in https://cloud.githubusercontent.com/assets/1022172/22787136/42f6904c-eea9-11e6-8482-406488163e9b.jpg

screen shot 2017-02-13 at 7 31 52 pm
screen shot 2017-02-13 at 7 31 41 pm
screen shot 2017-02-13 at 7 31 33 pm

### CODE REVIEW

**Comment by xtina-starr** [comment]
I don't think the failing spec was related to this work so I hit rebuild.

**Comment by 1aurabrown** [comment]
@craigspaeth reassigning to you because christina is ooo, but you guys are both welcome to chime in

**Comment by 1aurabrown** [comment]
when force is loaded on mobile (no change, but to confirm it still works):
screen shot 2017-02-13 at 8 21 36 pm

**Comment by craigspaeth** [comment]
👍  code looks good. Weird failure—I kicked it again. Maybe make sure to pull the latest upstream code in case it's from someone else's old PR.

**Pull request merged**
