### PR TITLE
@mzikherman - Launch new homepage

### PR DESCRIPTION
**Pull request by broskoski**
This launches the new homepage to 100% of users :)

### CODE REVIEW

**Comment by mzikherman** [comment]
No semaphore :(

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a PR summary</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by broskoski** [comment]
Hold a sec!

**Comment by mzikherman** [comment]
k

**Pull request merged**
