### PR TITLE
Adds read more cap to 'about more' artwork descriptions

### LINKED ISSUE #201: implement read more cap for about artwork descriptions on artwork pages
image

@sweir27 we've got some pretty long descriptions for phillips, think we could make these adjustments?

### PR DESCRIPTION
**Pull request by l2succes**
Closes #201 

screen shot 2017-01-05 at 12 11 40 pm

### CODE REVIEW

**Comment by craigspaeth** [comment]
Congrats on the first PR Luc! 👏  🎉  Weclome!

**Comment by alloy** [comment]
@craigspaeth It’s actually already his second https://github.com/artsy/force/pull/630. I was going to keep that a surprise for the announcement email ;)

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please assign someone to your PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by alloy** [comment]
Guess the CI fail was a phase of the :moon: bug 😞 

Code and visual result look good to me 👍 🎉

**Comment by l2succes** [comment]
Thanks @craigspaeth!

**Pull request merged**
