### PR TITLE
[PURCHASE-2130] follow up on addressing eslint no-console rules

### PR DESCRIPTION
**Pull request by xtina-starr**
Addresses: [PURCHASE-2130](https://artsyproduct.atlassian.net/browse/PURCHASE-2130)

Follow up to https://github.com/artsy/force/pull/6285/files/c37df7d74f4e60b9dc0e008761fa38793dfa47a4

### CODE REVIEW

**Comment by zephraph** [comment]
Looks great!

Thank you for saving us from more forgetful selves 😄

**Review by jpotts244 — APPROVED** [review]
🏅 !

**Comment by xtina-starr** [comment]
I'm going to go ahead and merge this if you're okay with that @zephraph.

**Comment by zephraph** [comment]
Merge away!

**Pull request merged**
