### PR TITLE
add readinessProbe to hokusai config for prod and staging

### PR DESCRIPTION
**Pull request by mbilokonsky**
As per @joeyAghion's suggestion I modeled this on the way [metaphysics does it](https://github.com/artsy/metaphysics/blob/e27355ffed06e40c4b9ec7bda8d461452647b403/hokusai/staging.yml#L46).

I'm not sure how to test this, though? Do we have some sort of Hokusai mock environment?

### CODE REVIEW

**Comment by joeyAghion** [comment]
👍 
The way to test is to run `hokusai staging update` with this change locally. You should be able to see the staging pods start and successfully serve traffic.

**Comment by mbilokonsky** [comment]
Excellent, I was able to do a `hokusai staging update` and everything went down and came back up with this stuff in the config file. I confirm that https://staging.artsy.net works after the change, so at a minimum we're not catching false positive.

I also changed the url here to a non-existent endpoint and confirmed that the pod was in a 'pending' state with a warning about readiness. (But I could still hit staging.artsy.net - I assume it won't deprecate the previous pod until the new one is initialized?)

**Comment by mbilokonsky** [comment]
@joeyAghion merge when ready!

**Comment by joeyAghion** [comment]
Thanks for the extra thoroughness.

As discussed, this will eventually need a `hokusai production update` to apply there.

**Pull request merged**
