### PR TITLE
@1aurabrown: Swap links order in press page

### PR DESCRIPTION
**Pull request by craigspaeth**
Simple request from [Anna](https://team.artsy.net/anna.carey).

image

### CODE REVIEW

**Comment by alloy** [comment]
Dat commit message 🙈

😛

**Comment by broskoski** [comment]
I think I speak on behalf of @1aurabrown when I say that this PR is A-OK.

**Comment by alloy** [comment]
Going to take this, as @1aurabrown is still out for another week.

**Comment by broskoski** [comment]
No, me @alloy

**Comment by alloy** [comment]
Too late, @broskoski! In this day and age you should just take, not be polite.

**Comment by broskoski** [comment]
I tried, I tried.

**Pull request merged**
