### PR TITLE
Revert "chore(deps): update dep typescript from 4.3.5 to v4.4.3"

### PR DESCRIPTION
**Pull request by dzucconi**
Reverts artsy/force#8281

### CODE REVIEW

**Comment by damassi** [comment]
@dzucconi - can you update the PR description with details about why we had to revert? Then we'll know later when it inevitably fails 🔮

**Comment by dzucconi** [comment]
https://github.com/artsy/force/pull/8281 was automatically merged despite not passing type-check

**Comment by damassi** [comment]
oh no, so this is still happening?

**Comment by dzucconi** [comment]
in this case it appears it was Renovate that merged not Peril. 🤖 uprising?

**Comment by damassi** [comment]
😓

**Pull request merged**
