### PR TITLE
Use orb to upload coverage

### PR DESCRIPTION
**Pull request by eessex**
Removes `codecov` package in favor of their orb. This change allows us to start using the `hokusai/test` command in CI. I've simplified the test script and removed the parallelism so that all tests run in the same command/container.

This definitely makes our tests run slower (mostly from building in a docker container but also removed parallelism). However I think it is a better, simplified system, one that is closer to what we use in other apps.

I've also restored the stored test results, which broke at some point over the last few months.

### CODE REVIEW

**Comment by joeyAghion** [comment]
Definitely simpler. How much slower?

**Comment by eessex** [comment]
Workflows are around 14min, it looks like we are somewhere around 5 min now.  I think anything that uses `hokusai` and docker to build is going to be slower than what we currently have, so I wonder if we can look for other ways to optimize speed (like moving some tests out of mocha or trying to find tests for old backbone code that we can 🔪 )

**Comment by joeyAghion** [comment]
I defer to you on whether the trade-off is worth it. It doesn't really affect _me_, but since Force frequently gets automatic PRs for Reaction, etc., its build time _is_ a big component in our overall shipping lag and even the speed at which we can ship timely production fixes when they occasionally become necessary.

**Comment by eessex** [comment]
My guess is that because so many of the PRs on this repo are automatic it will be noticed less than a similar change in more active repos. I'd like to try it for now and see how it goes. 

If we get any friction we can look at moving out of docker and back to yarn relatively easily. In my memory we had introduced parallelism not because of speed but because our mocha tests were too flaky to run in the same command as jest. I haven't seen this flake yet in the docker-based runs.

**Pull request merged**
