### PR TITLE
chore(alerts): clean up `onyx_artwork_alert_modal_v2` flag and dead code

### PR DESCRIPTION
**Pull request by anandaroop**
The type of this PR is: **Chore**

This PR solves [ONYX-680]

Review app: https://onyx-680.artsy.net

### Description

Now that v2 alerts have been out in the wild for a while, we are starting to clean up feature flags and dead code.

This PR starts that process with the `onyx_artwork_alert_modal_v2` feature flag.

Tests are passing; but for extra confidence that this does not introduce any regressions feel free to try out https://onyx-680.artsy.net

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-680]: https://artsyproduct.atlassian.net/browse/ONYX-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(h/t @tam-kis for pairing on the test fixes!)

### CODE REVIEW

**Review by nickskalkin — APPROVED** [review]
looks good to me! Also tested on review app briefly and all seems working

**Review by dariakoko — APPROVED** [review]
⭐⭐⭐

**Review by dariakoko — APPROVED** [review]
⭐⭐⭐

**Comment by dariakoko** [comment]
Too good to be approved once 😄

**Comment by anandaroop** [comment]
Haha thanks! I'll rebase and merge now.

**Pull request merged**
