### PR TITLE
fix: apply new fair redirection logic to mobile fair app

### PR DESCRIPTION
**Pull request by dblandin**
Follow-up to https://github.com/artsy/force/pull/6373

Resolves [FX-2384]

[FX-2384]: https://artsyproduct.atlassian.net/browse/FX-2384

### CODE REVIEW

**Comment by oxaudo** [comment]
@mdole - do you think this makes the other change https://github.com/artsy/force/pull/6502 obsolete? I'm a bit unclear how those 2 will interact.

**Comment by mdole** [comment]
@oxaudo good q - I think it would make #6502 unnecessary for fairs that redirect to the new fair pages, but not other fairs. [redirectFairRequests](https://github.com/artsy/force/blob/3a2c12a503c963fb8a5713308c61c08f508cdcd6/src/desktop/apps/fair/fairRedirection.ts#L4) effectively checks if we want to redirect to new fairs experience (which I assume is not yet true for 100% of fairs) and then if not just moves on

**Review by anandaroop — APPROVED** [review]
Ouch another mWeb oversight — thanks for the quick fix @dblandin  🙏

**Comment by dblandin** [comment]
> which I assume is not yet true for 100% of fairs

@mdole W enabled the new fair page for all fairs except those which had already started at the time of the rollout.

You can see a list of the excluded fairs in Slack [here](https://artsy.slack.com/archives/C01CAM2QS3U/p1603122709047300). There are only 5 and we plan to move them over to the new experience once the fairs close.

**Comment by mdole** [comment]
ooo neat! ok then I guess that might effectively eliminate the need for #6502 - I can follow up tomorrow to confirm

**Pull request merged**
