### PR TITLE
chore(CX-3530): hide parts of the page

### PR DESCRIPTION
**Pull request by dariakoko**
The type of this PR is: **Chore**

This PR solves [CX-3530]

### Description

To test: https://swa-lp-redesign.artsy.net/sell

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3530]: https://artsyproduct.atlassian.net/browse/CX-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
LGTM - i think we need to adjust the e2e test though as well

**Comment by MounirDhahri** [comment]
I see you already did it here - https://github.com/artsy/integrity/pull/469 thanks

**Comment by dariakoko** [comment]
I'll merge it then

**Comment by MounirDhahri** [comment]
sounds good - I would always suggest rebasing first though because you never know what breaks meanwhile.

**Pull request merged**
