### PR TITLE
@damassi: Removed flash middleware and loosened up memory flags

### PR DESCRIPTION
**Pull request by craigspaeth**
Monkey patching with flash middleware caused [`No default engine was specified`](https://papertrailapp.com/systems/force-production/events?focus=789344138062610480&selected=789344138062610480) errors—not causing any serious issues, but we were only using it after personalize so I figured we might as well take it out. I'm also taking off the memory flags except for `max_old_space_size` (which tells Node to stay under the 1gb Heroku limit) now that we've determined what the resource issues in Force were. Finally, I'm adding [forever](https://github.com/foreverjs/forever) to the start script for good measure. I'm hoping the latter of these two changes should help the sudden timeout + crash issues we saw in the last minute and a half of Waddingtons.

### CODE REVIEW

**Comment by damassi** [comment]
LGTM, but I would probably ask someone else on the team about Forever and other similar server-side techniques for keeping long-running processes alive. It seems a bit sensitive and I haven't ever had to deal with this problem!

**Comment by craigspaeth** [comment]
We've put forever in place in the past on Force. It band-aided over some issues with uncaught error crashes we were encountering. That said, it's been a while since I took the time to investigate what exactly this means with Heroku's routing mesh behavior—so I'll take some time to research that and see if there's not a better solution.

I believe the difference with using forever vs. letting Heroku restart the app is instead of putting up a Heroku error page for everyone like we saw at the last minute of Waddingtons—the app would close its open connections (showing the Heroku error page to that handful of users), and further requests would see a page loading as Heroku's router starts sending requests to a booting up Force. Seeing a page loading is better than the app appearing crashed, however, I wonder if by using Forever we miss out on Heroku's router being smart about sending requests to healthy, already booted, dynos—in which case it might be better to just scale up dynos for enough redundancy... 🤔

**Comment by damassi** [comment]
Heh, yeah, that's what I mean! I'm a little hesitant to press the green button (but do agree that seeing the page load is much better than the Heroku "app not available" screen :) 

What if you pop that Forever commit off for now and I'll merge the other stuff in while you think through the different restart paths?

**Comment by damassi** [comment]
Will merge on 🍏

**Comment by damassi** [comment]
Damn @craigspaeth - this thing just doesn't want to pass 🤕

**Comment by craigspaeth** [comment]
So a quick read into Heroku's docs seems to tell me that Forever is probably preferable to have.

It appears that things haven't changed since I last remember, and Heroku's routing is pretty random. From what I understand Heroku will blindly route to a dyno and if it doesn't respond in 5 seconds it will route to another dyno until one responds—retrying with incremental backoff until it surfaces an error page. With Forever we should expect similar behavior, except potentially Heroku wouldn't surface an error page as often as Forever wouldn't bubble up the 1 exit code.

That said, what might be even better is to [look into clustering](https://devcenter.heroku.com/articles/node-concurrency) for better resilience _and_ performance.

See [dyno connection behavior](https://devcenter.heroku.com/articles/http-routing#dyno-connection-behavior).

**Comment by damassi** [comment]
Thank you for the links 👍

**Pull request merged**
