### PR TITLE
feat(TX-1061): Provenance and artwork condition for PS orders

### PR DESCRIPTION
**Pull request by AlicanAkyuz**
The type of this PR is: **Feat**

This PR solves [TX-1061]

### Description

This PR updates the payment and review steps for private sale orders in the checkout flow, to display artwork provenance and condition from artwork version. 

#### Image
Screenshot 2023-03-09 at 13 31 57

[TX-1061]: https://artsyproduct.atlassian.net/browse/TX-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rquartararo** [comment]
Do we have a Figma design for this?

**Comment by AlicanAkyuz** [comment]
@rquartararo there's a slight mention to provenance here: https://www.figma.com/file/l9sDsFTGxGA1JlCxGYJDYY/Private-Sales-Checkout?node-id=2574-27298&t=7xGvbON7tLe8LosD-0 

but I'll viviana's eyes on this today.

**Review by rquartararo — DISMISSED** [review]
Looks good 👍  Just wanted to double-check the design bc I don't think the fields look distinct enough, but looks like you're on that.

**Comment by rquartararo** [comment]
> @rquartararo there's a slight mention to provenance here: https://www.figma.com/file/l9sDsFTGxGA1JlCxGYJDYY/Private-Sales-Checkout?node-id=2574-27298&t=7xGvbON7tLe8LosD-0
> 

Yeah I think that design was based on only having one text field to enter in info so it's outdated

**Pull request merged**
