### PR TITLE
[FX-1743] update artsy-eigen-web-association app

### PR DESCRIPTION
**Pull request by xtina-starr**
Addresses: [FX-1743](https://artsyproduct.atlassian.net/browse/FX-1743)

This updates the `artsy-eigen-web-association` app in force so that collection pages open in the iOS app for iPhone users with the app.

### CODE REVIEW

**Comment by sweir27** [comment]
Do you have any insight into the other changes to the yarn.lock file? They don't seem that risky, just want to make sure we feel confident.

**Comment by xtina-starr** [comment]
@sweir27 I don't but the command I ran was `yarn upgrade artsy-eigen-web-association`. Is it possible that those are dependencies of artsy-eigen-web-association because I don't see `proxy-addr` as a dependency in `package.json` file?

**Comment by ashfurrow** [comment]
@xtina-starr @sweir27 I left a note here about the additional changes: https://github.com/artsy/artsy-wwwify/pull/24#pullrequestreview-365038514 Maybe we could update the README in `artsy-eigen-web-association`?

**Comment by xtina-starr** [comment]
hey @sweir27, @ashfurrow added a bit more context on my related PR: https://github.com/artsy/artsy-wwwify/pull/24#pullrequestreview-365038514

**Comment by sweir27** [comment]
Oh nice! Thanks @ashfurrow 😄.

Going to merge this in.

**Pull request merged**
