### PR TITLE
@xtina-starr => add signupIntent to more auth points

### PR DESCRIPTION
**Pull request by erikdstock**
cc @katarinabatina @mzikherman @anipetrov 
This PR adds signup intent tracking to several CTAs throughout force. I paired with @xtina-starr on this.

_updated- per ani's requests [below]_
```
- fairs list: 'sign up to follow fairs'
- artist page cta from full page sign up modal: 'landing full page modal'
- fair popup modal (marekting_signup_modal): 'marketing modal'
- /collect sign up button cta: 'artists you follow filter'
- about sign up button: 'sign up to save works'
```

### CODE REVIEW

**Comment by xtina-starr** [comment]
Nice nice 👍 

Yeah @anipetrov I'd be interested to know if you have some sort of schema in mind for these user intents as we start use them more.

**Comment by anipetrov** [comment]
Hey! Took a look and wondering if would consider something more like:

```
- fairs list: 'sign up to follow fairs'
- artist page cta from full page sign up modal: 'landing full page modal'
- artist page cta from footer: 'landing footer'
- fair popup modal (marekting_signup_modal): 'marketing modal'
- /collect sign up button cta: 'artists you follow filter'
- about sign up button: 'sign up to save works'
```
i think we don't need to explicitly call out `cta` in any of these but i am afraid that with the specifics now these will not be iteration-prone. thoughts?

**Comment by erikdstock** [comment]
Updated per @anipetrov 's requests above- note the footer does not trigger any login action on its own but just exposes the full-page modal so I left that one out.

Tagging @mzikherman as well since in the process of doing this we realized that the artist_page_cta/view.coffee may need a quick pass to confirm redirects are happening correctly there as well.

**Comment by xtina-starr** [comment]
This looks good to me. I'm going to merge.

**Pull request merged**
