### PR TITLE
@kanaabe => Responsive main layout footer

### PR DESCRIPTION
**Pull request by eessex**
Closes https://github.com/artsy/force/issues/242

Main layout footer changes to mobile version at 600px, has anonymous and logged in states.

### CODE REVIEW

**Comment by eessex** [comment]
screen shot 2016-11-07 at 12 47 46 pm
screen shot 2016-11-07 at 12 50 42 pm

**Comment by kanaabe** [comment]
💯  so awesome! what does a signup/login look like with the mobile width? I'm assuming those will eventually have to be updated as well.

**Comment by eessex** [comment]
@kanaabe - not bad actually!  It is already responsive down to 400
screen shot 2016-11-07 at 4 40 51 pm

**Comment by kanaabe** [comment]
Great, merging

**Pull request merged**
