### PR TITLE
@mzikherman - Inquiry test QA

### LINKED ISSUE #191: QA A/B Test: Forced Signup to inquire
@anipetrov when you have a chance can you include analytics requirements?

@broskoski I still need to go through the pre-qual flow once it's up on staging and will need to go through /shows after issue below has been addressed.

#### QA
- [x] Include animation for the sign up screen
- [x] Check share followed artists, categories by default
- [ ] You can skip profession card if you haven't bought art before, but can't if you have
- [x] If I type in an email that exists, I can't type a new one: https://cl.ly/302b0r052D3d
- [x] Can submit form without any content: https://cl.ly/1V0c0F351P3r
- [x] css issues with modal on /shows
- [ ] Use google location api for profile location field

Original issue: https://github.com/artsy/force/issues/80

### PR DESCRIPTION
**Pull request by broskoski**
Close #191 

Leaving the last two things for later (as they were pre-existing and unrelated to this test).

inquiry-qa

### CODE REVIEW

**Comment by mzikherman** [comment]
real ❌ but looks great!

**Comment by broskoski** [comment]
💚

**Comment by broskoski** [comment]
Sigh

**Comment by mzikherman** [comment]
👌

**Pull request merged**
