### PR TITLE
adding analytics events for artwork suggested inventory rails

### PR DESCRIPTION
**Pull request by oxaudo**
First point in https://artsyproduct.atlassian.net/browse/EV-188

There is a lot of code repetition in those analytics events but I feel like it's actually good to be explicit here vs creating a helper functions that would be called on each event.

I'll add the rest of them first thing tomorrow.
cc @katarinabatina, @anipetrov

### CODE REVIEW

**Comment by anipetrov** [comment]
I think @katarinabatina had also added a `flow` parameter for all of these -- it would make it easy to bucket the click events that respond to the artwork rails. it should be the same everywhere, `flow: 'artwork suggested inventory rails'`

**Comment by oxaudo** [comment]
I'm still adding more events but as far as I can see there is no hard in merging this and starting to get those defined here.

**Comment by katarinabatina** [comment]
@oxaudo @alloy I'm good with us shipping them piece by piece, no need for them to all go out in one PR

**Comment by alloy** [comment]
Ace 👍

**Pull request merged**
