### PR TITLE
@alloy - Add middleware to block ip addresses

### PR DESCRIPTION
**Pull request by broskoski**
cc @craigspaeth

### CODE REVIEW

**Comment by joeyAghion** [comment]
For posterity: general site slowness was traced to super-aggressive crawling of `/sitemap-...` paths from a single AWS IP address. Logs included hundreds of lines per minute like the following, with the same IP address and useragent string:

```
2016-11-22T21:05:36.605689+00:00 app[web.2]: ::ffff:10.37.199.190 - - [22/Nov/2016:21:05:36 +0000] "GET /sitemap-artworks-4-2016-03-01.xml HTTP/1.1" - - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"
2016-11-22T21:05:36.560720+00:00 heroku[router]: at=info method=GET path="/sitemap-images-1-2016-08-01.xml" host=www.artsy.net request_id=9ce09c98-f1fd-4191-9a8c-585317052662 fwd="52.0.99.131" dyno=web.2 connect=0ms service=10245ms status=200 bytes=1982995
2016-11-22T21:05:36.561248+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/sitemap-artworks-4-2016-03-01.xml" host=www.artsy.net request_id=f3e2d9e2-186f-491c-9e10-b873f6d9044a fwd="52.0.99.131" dyno=web.2 connect=3ms service=30001ms status=503 bytes=0
```

**Comment by craigspaeth** [comment]
@broskoski @alloy we already had middleware to do this found here https://github.com/artsy/force/blob/master/lib/setup.coffee#L56 😛

**Comment by broskoski** [comment]
@craigspaeth :face_with_head_bandage:

**Comment by broskoski** [comment]
Will revert this then, already added the IP to the blacklist.

**Pull request merged**
