### PR TITLE
fix: revert using auctionDetailsFormattedStartDateTime in favor of formattedStartDateTime

### PR DESCRIPTION
**Pull request by mzikherman**
Reverts https://github.com/artsy/force/pull/9633 (the new MP field has some issues).

### CODE REVIEW

**Comment by dzucconi** [comment]
Hold off on merging this; I'm just PRing my client-side query renderer right now

**Comment by mzikherman** [comment]
cool will close

**Comment by mzikherman** [comment]
Superseded by https://github.com/artsy/force/pull/9663

**Comment by dzucconi** [comment]
@annacarey #9663 reverts this already

**Comment by annacarey** [comment]
Opened because I thought we still needed the fix but we don't so closing again.

**Pull request closed without merging**
