### PR TITLE
feat: support debugging active file

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **feat**

### Description

This PR enables debugging the active file on VSCode

https://user-images.githubusercontent.com/11945712/210609197-ca927acf-f387-4a3e-ab77-01b6751931b0.mov

### CODE REVIEW

**Comment by damassi** [comment]
whatttt

**Comment by damassi** [comment]
nice @MounirDhahri !

**Comment by damassi** [comment]
Can you broadcast this change in appropriate channels?

**Comment by MounirDhahri** [comment]
Of course

**Pull request merged**
