### PR TITLE
@mzikherman => Sets up Loyalty page

### PR DESCRIPTION
**Pull request by l2succes**
Depends on: https://github.com/artsy/reaction-force/pull/51

This adds reaction-force as dependency and mounts the loyalty page app as a sub-app in force.

### CODE REVIEW

**Comment by alloy** [comment]
Sweet, well done @l2succes ✨

**Comment by mzikherman** [comment]
This looks magical!

I'm totally fine merging this whenever, want to take the lead on self-merging whenever ready @l2succes ?

**Comment by l2succes** [comment]
@mzikherman Cool! Yeah, let's get the reaction-force PR merged in first then I'll merge that one.

**Comment by mzikherman** [comment]
This is ready to go!

**Comment by l2succes** [comment]
Ok, yup. it's good to go!

**Pull request merged**
