### PR TITLE
[MX-143] Updates Eigen deeplink config

### PR DESCRIPTION
**Pull request by ashfurrow**
This updates Force's Eigen deeplink config file, from this PR: https://github.com/artsy/artsy-eigen-web-association/pull/28

I ran `yarn upgrade artsy-eigen-web-association` and I'm not totally sure what the other changes are. Open to feedback if this is abnormal.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Got some insight on the unrelated changes – I will amend this PR with a more precise commit.

**Comment by zephraph** [comment]
artsy-eigen-web-association depends on express and it looks like there were some updates around that, but the ultimate versions present aren't actually different from what we have, they just show up in a different order. 

I'm good w/ this change 👍

**Comment by zephraph** [comment]
artsy-eigen-web-association depends on express and it looks like there were some updates around that, but the ultimate versions present aren't actually different from what we have, they just show up in a different order. 

I'm good w/ this change 👍

**Comment by ashfurrow** [comment]
@zephraph okay! Thanks – I learned the difference between `yarn add ...` and `yarn upgrade ...` today. Let's merge, then 👍

**Pull request merged**
