### PR TITLE
BUGFIX: Add missing info tip

### PR DESCRIPTION
**Pull request by damassi**
(Missed a label from https://github.com/artsy/force/pull/1631)

screen shot 2017-07-12 at 1 07 21 pm

### CODE REVIEW

**Comment by damassi** [comment]
cc @katarinabatina .

**Comment by katarinabatina** [comment]
@damassi if it's not too much of a bother to use the avant vs garamond 
image

will the user bid status come through in this change?

**Comment by damassi** [comment]
Yup, that was always there (meaning, was never an issue); you just have to be logged in otherwise it won't appear.

**Comment by damassi** [comment]
screen shot 2017-07-12 at 1 30 14 pm

**Comment by katarinabatina** [comment]
@damassi sweeeeeeeet! Looks great

**Pull request merged**
