### PR TITLE
fix: Navigate to My Collection artwork page on the Sell flow "Save & Exit"

### PR DESCRIPTION
**Pull request by olerichter00**
Resolves https://www.notion.so/artsy/When-submitting-a-MyC-artwork-should-Save-Exit-navigate-back-to-the-artwork-Currently-it-opens--ebdf272100c94666ba75b1c943097327?pvs=4

## Description

Navigate to My Collection artwork page on the "Save & Exit" when associated My Collection artwork is present.

Screenshot 2024-08-05 at 12 58 45

### CODE REVIEW

**Comment by olerichter00** [comment]
@MounirDhahri do we need the same adjustment in the app?

**Review by dariakoko — APPROVED** [review]
⭐

**Comment by dariakoko** [comment]
I don't think we need the same adjustment in the app, navigation there is built differently

**Comment by MounirDhahri** [comment]
@dariakoko is right, we simply dismiss the screen on app - so it should be fine. We don't need to "Save" the submission to global store though in that case

**Pull request merged**
