### PR TITLE
@xtina-starr Revert "@craigspaeth change marketo embedded form styling for last row 3 fields"

### PR DESCRIPTION
**Pull request by nicholassewitz**
Reverts artsy/force#119

### CODE REVIEW

**Comment by nicholassewitz** [comment]
There was some miscommunication and need to remove the phone field, reverting to two fields on that line

**Comment by xtina-starr** [comment]
This looks like a CSS change. That's all that's need to remove the field? @craigspaeth @nicholassewitz

**Comment by nicholassewitz** [comment]
Correct Christina. I have to remove the rest in Marketo.

N

**Comment by craigspaeth** [comment]
@xtina-starr yep yep—it's an awkward lockstep tango we have to play with Marketo embedded forms, but yeah that's all that's needed on Force's end.

**Pull request merged**
