### PR TITLE
fix: Scroll to top when entering next step in My Collection upload flow

### PR DESCRIPTION
**Pull request by olerichter00**
The type of this PR is: **Fix**

This PR solves [CX-3308]

### Description

Scroll to top when entering next step in My Collection upload flow.

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3308]: https://artsyproduct.atlassian.net/browse/CX-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
Good one

**Comment by MounirDhahri** [comment]
I would have also considered `scrollToTop` as part of a `useEffect` hook at the main wrapper component when the active screen changes

**Comment by MounirDhahri** [comment]
Please feel free to merge this - my comment is not blocking

**Comment by olerichter00** [comment]
> I would have also considered `scrollToTop` as part of a `useEffect` hook at the main wrapper component when the active screen changes

Great idea - much cleaner! Will implement and merge 🚢

**Comment by MounirDhahri** [comment]
Awesome - thanks Ole

**Pull request merged**
