### PR TITLE
@xtina-starr: Support markdown in hero unit template

### PR DESCRIPTION
**Pull request by craigspaeth**
I added [randomized homepage banners](https://github.com/artsy/force/pull/768) by refactoring them to use Metaphysics. Unfortunately, this introduced a [regression to markdown support](https://artsy.slack.com/archives/help/p1485531304000831)—so this adds it back with a test.

### CODE REVIEW

**Comment by mzikherman** [comment]
Is this something that should be implemented in Metaphysics?

ie- those `title` and `credit_line` fields in Metaphysics can include `args: markdown().args`, and then the resolver would take those into account with something like: `return formatMarkdownValue(credit_line, options.format);`.

Then the Force query would be:

```
{
  hero_units {
    credit_line(format: HTML)
  }
}
```

**Comment by xtina-starr** [comment]
I don't have a strong opinion of whether this should live in force or metaphysics. @craigspaeth, thoughts? I can go ahead and merge now to get the credit line and subtitle back and perhaps this could be moved to metaphysics later...?

**Comment by craigspaeth** [comment]
Hmm, not sure if I have a strong opinion about where this should live but happy to have it in MP. For now, it seems like this feature is somewhat blocking [Andrew](http://team.artsy.net/andrew) so I'm down with the plan of refactoring downstream later. Margin'

**Comment by mzikherman** [comment]
Yea, I guess it only matters if other clients need the same Markdown fix/ability, but if they're all fine as-is with just Force needing a fix this is a-ok 👍 

Sorry for being pedantic :)

**Comment by craigspaeth** [comment]
Not pedantic at all @mzikherman! You bring up a valid point—just wasn't sure what the best route was and didn't want to hold up the fix. As I understand it, this will probably only be needed on Force because we basically only use it introduce manual line breaks for long text on desktop—for mobile I'm pretty sure we'd want to ignore the markdown breaks and let it naturally break. So this might be a fine approach.

On the other hand, moving it to MP we can still optionally run it through markdown or not using GraphQL args—so generally speaking it probably is better to default to implementing in MP where each client can, for instance, avoid inconsistencies by leveraging the same markdown library in MP.

🤔  noted.

**Pull request merged**
