### PR TITLE
@mzikherman: explicitly provide the entire url instead of relative path

### PR DESCRIPTION
**Pull request by xtina-starr**
I suspect that the relative path here is causing an [error](https://github.com/artsy/microgravity/issues/11) when trying to login via the professional buyer page. This page is mobile responsive where the logic lives in force. When logging in on this page from a mobile device, the relative path attempts to log you into microgravity when it should log in to force and redirect back to microgravity after the professional buyer registration is complete. The only way to see if this work is to deploy the change to staging and manually test.

### CODE REVIEW

**Comment by broskoski** [comment]
Looks good but real ❌ , also don't forget to assign someone to the pr :)

**Comment by mzikherman** [comment]
Worth a shot, but if the page is responsive then aren't you on Force when you're on the prof buyer page on a mobile device? If so, isn't a relative path (or the full path) identical, and both _should_ be correct? I may be missing something here!

**Comment by xtina-starr** [comment]
Yeah that seems right and it's confusing trying to explain it, but when you make the request from mobile the url is `m.artsy.net/professional-buyer` and doesn't change. I believe that's because a proxy is actually doing it. However, `sd.APP_URL` is set to 'https://www.artsy.net'. The log in part should actually be made to `https://www.artsy.net/log_in` and not `https://m.artsy.net/log_in`. My guess is that you are never getting a `force.sess` cookie which would be need to create a valid `csrf token`. Does that make sense? This doesn't have to be merged today and we can chat about it more tomorrow with a demo. It's a confusing one lol.

**Comment by mzikherman** [comment]
I don't 100% follow..but I am down to try on staging? If it doesn't work maybe we can debug it together.

**Comment by xtina-starr** [comment]
Sounds good, thx!

**Pull request merged**
