### PR TITLE
Adds check for item

### PR DESCRIPTION
**Pull request by l2succes**
Fixes: https://sentry.io/artsynet/force-production/issues/690186056/?query=is:unresolved

### CODE REVIEW

**Comment by l2succes** [comment]
Going to merge this as it's affecting a # of our users.

**Comment by l2succes** [comment]
merge on green

**Comment by joeyAghion** [comment]
See also https://github.com/artsy/force/pull/2897
!

**Comment by oxaudo** [comment]
HA! One of those. Maybe @l2succes is more successful with Circle:)

But also I'm wondering why the data is off here. I guess the underlying issue is that this auction partner does not have profile properly set up.

**Comment by l2succes** [comment]
Oh didn't notice it! Since the tests failed on the other PR, i'll let this one run. Hopefully we're good here

**Pull request merged**
