### PR TITLE
feat: Activity list item design update

### PR DESCRIPTION
**Pull request by olerichter00**
Addresses [ONYX-657]

## Description

This PR updates the design of the Activity list items.

| Before | After |
| --- | --- |
|Screenshot 2024-01-25 at 16 55 31 | Screenshot 2024-01-25 at 16 54 37|

[ONYX-657]: https://artsyproduct.atlassian.net/browse/ONYX-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — DISMISSED** [review]
LGTM! thanks! do you mind if you ticket the placeholder work if you didn't already to make sure we don't forget about it.

**Comment by olerichter00** [comment]
> LGTM! thanks! do you mind if you ticket the placeholder work if you didn't already to make sure we don't forget about it.

Good call! I've committed an update to the placeholder in this PR 👍

**Comment by MounirDhahri** [comment]
Thanks!

**Comment by dariakoko** [comment]
Sorry, I reviewed, but didn't submit 🥴 
Looks great, thank you!

**Pull request merged**
