### PR TITLE
security: add detect-secrets

### PR DESCRIPTION
**Pull request by ovasdi**
https://artsyproduct.atlassian.net/browse/PLATFORM-3414
Guided by [detect-secrets playbook](https://www.notion.so/artsy/Detect-Secrets-cd11d994dabf45f6a3c18e07acb5431c).

- Add detect-secrets pre-commit hook to scan staged files
  - Execute the script as part of pre-commit hook (via husky)
- Add detect-secrets CI step to scan all files on dev branches

---

Force has a lot of lines that trigger the tool to detect violations. A large number of these live within tests. These lines have been recorded within the baseline or are being ignored via _pattern exclusions_ as well as explicit _inline exclusions_.

As far as _inline exclusions_ go, in most cases this form of "whitelisting" is used on lines that are marked by the tool as "secret keyword" e.g.: setting a password when writing a test is seen as a violation and should be handled via a global exclude or an inline one.

A number of exclusions have been baked into the baseline in an effort to keep the baseline size to a minimum and to cover certain cases **globally**. In cases where the tool is tripping up on lines that are not actual "secrets" e.g.: `passwordNextButton`,`trackForgotClick`,`true` we are using global exclusions. Common patterns such as `foo` and `secret`, used as "secret keywords", have also been globally excluded. For the full list of excluded patterns see [this filter](https://github.com/artsy/force/pull/8542/files#diff-d8447df0cd384602c76086081f13f27ad0b45902297c42da35a6fc51fdf1cec3R111).

I hope that this approach will help with keeping the secret scanning a smooth developer experience however I suspect that we _may_ see some initial friction with dev flow after this is merged, especially when modifying or writing tests. In most cases using the whitelisted patterns as well as inline exclusions should be enough but we may have to update/regenerate the baseline or expand global exclusions if this proves to be too disruptive.

### CODE REVIEW

**Review by joeyAghion — APPROVED** [review]
This seems fine to me given our experiences on other projects. I'm interested to hear from others who spend more time in Force.

**Comment by damassi** [comment]
How long does it take to run this command?

**Comment by ovasdi** [comment]
> How long does it take to run this command during pre-commit?

In my experience, usually it completes under a second but it will depend on the number of staged files and the size of those files. See examples below:

Smaller CL: _0.6s_
```
➜  force git:(detect-secrets-runtime) ✗ git status
On branch detect-secrets-runtime
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .circleci/config.yml
	modified:   .secrets.baseline
	modified:   src/desktop/apps/authentication/__tests__/helpers.jest.ts
	modified:   src/desktop/apps/authentication/__tests__/routes.jest.ts
	modified:   src/desktop/apps/consign/components/create_account/__tests__/CreateAccount.jest.tsx
	modified:   src/mobile/apps/user/models/password_edit.coffee
	modified:   src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
	modified:   src/v2/Components/Authentication/__tests__/fixtures.ts
	modified:   src/v2/Components/ConfirmPasswordModal/__tests__/ConfirmPasswordModal.jest.tsx

➜  force git:(detect-secrets-runtime) ✗ time detect-secrets-hook --baseline .secrets.baseline $(git diff --staged --name-only)
detect-secrets-hook --baseline .secrets.baseline   0.59s user 0.16s system 107% cpu 0.699 total
```

Large CL: _3.9s_
Note that in this example, one of the staged files is `yarn.lock` ~21k lines.
```
➜  force git:(detect-secrets-runtime) ✗ git status
On branch detect-secrets-runtime
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .circleci/config.yml
	new file:   .secrets.baseline
	modified:   data/schema.graphql
	modified:   package.json
	new file:   scripts/detect-secrets.sh
	modified:   src/desktop/apps/authentication/__tests__/helpers.jest.ts
	modified:   src/desktop/apps/authentication/__tests__/routes.jest.ts
	modified:   src/desktop/apps/consign/components/create_account/__tests__/CreateAccount.jest.tsx
	modified:   src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.jest.tsx
	new file:   src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
	new file:   src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
	new file:   src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
	new file:   src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
	new file:   src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
	modified:   src/v2/Apps/Consign/consignRoutes.tsx
	modified:   src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
	modified:   src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
	modified:   src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx
	modified:   src/v2/Apps/Home/HomeApp.tsx
	modified:   src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx
	modified:   src/v2/Apps/Shows/Components/ShowsCurrentShows.tsx
	modified:   src/v2/Apps/Shows/Components/ShowsHeader.tsx
	modified:   src/v2/Apps/Shows/Routes/ShowsCity.tsx
	modified:   src/v2/Apps/Shows/Routes/ShowsIndex.tsx
	modified:   src/v2/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx
	modified:   src/v2/Apps/Shows/showsRoutes.tsx
	modified:   src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
	modified:   src/v2/Components/Authentication/__tests__/fixtures.ts
	modified:   src/v2/Components/ConfirmPasswordModal/__tests__/ConfirmPasswordModal.jest.tsx
	modified:   src/v2/Components/Masonry.tsx
	modified:   src/v2/Components/NavBar/NavBar.tsx
	modified:   src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
	modified:   src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
	modified:   src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
	modified:   src/v2/System/Router/RouterLink.tsx
	new file:   src/v2/Utils/Hooks/__tests__/useDialog.jest.tsx
	new file:   src/v2/Utils/Hooks/__tests__/useLazyLoadComponent.jest.tsx
	new file:   src/v2/Utils/Hooks/useScrollTo.ts
	modified:   src/v2/Utils/scrollHelpers.ts
	new file:   src/v2/__generated__/ShowsCityQuery.graphql.ts
	modified:   src/v2/__generated__/ShowsCity_Test_Query.graphql.ts
	modified:   src/v2/__generated__/ShowsCity_city.graphql.ts
	modified:   src/v2/__generated__/ShowsCurrentShowsQuery.graphql.ts
	modified:   src/v2/__generated__/showsRoutes_ShowsCityQuery.graphql.ts
	modified:   yarn.lock

➜  force git:(detect-secrets-runtime) ✗ time detect-secrets-hook --baseline .secrets.baseline $(git diff --staged --name-only)
detect-secrets-hook --baseline .secrets.baseline   3.60s user 0.23s system 96% cpu 3.981 total
```

**Review by jacobherrington — COMMENTED** [review]
**question (non-blocking):** Is there a reason we are choosing to use Docker over the Brew package for detect-secrets?

I'm curious if something has changed; using the Brew package feels like less overhead and lowers adoption friction as it doesn't require Docker to be running.

**Comment by ovasdi** [comment]
> **question (non-blocking):** Is there a reason we are choosing to use Docker over the Brew package for detect-secrets?
> 
> I'm curious if something has changed; using the Brew package feels like less overhead and lowers adoption friction as it doesn't require Docker to be running.

@jacobherrington Is your question is CI specific?

Locally we execute the tool outside docker (as `pre-commit`) using the [CLI tool](https://github.com/artsy/force/pull/8542/files#diff-dfbcf346bfc26d4ea0e84fa1f0c584437d533fffab67e0c24ce5ad34cde06b15R21) installed via brew (or pip).
In CI we are using the image as it falls in line with how we execute a lot of jobs, by using the docker executor. IIRC running in CI via docker was not seen as a performance issue. We did not experiment with building our own orb however, with the tool baked into it. I do wonder how much more performant that would be.

**Comment by damassi** [comment]
Cool, half a second for for most PRs isn't so bad and don't think this will be too intrusive. Lets see how it feels in practice across the team :thumbsup:

**Comment by damassi** [comment]
@ovasdi - want to get your thoughts:

An alternative hook (which I would be more inclined to use) is pre-push, since a dev might do many commits in a local branch before pushing to a PR. However, if using pre-push, then failed checks will require a fix and a new commit. (Which i'm fine with since checking in secrets will likely be quite rare.)

**Comment by jonallured** [comment]
> devs can't skip that hook 

Periodic reminder that all project-specific git hooks can be easily skipped by setting the `hooksPath` like so:

https://github.com/jonallured/dotfiles/blob/main/rcm/gitconfig#L33

The approach of using git hooks is flawed from the start imho.

**Comment by damassi** [comment]
> The approach of using git hooks is flawed from the start imho.

For sensitive operations, I agree.

**Comment by ovasdi** [comment]
> @ovasdi - want to get your thoughts:
> 
> An alternative hook (which I would be more inclined to use) is pre-push, since a dev might do many commits in a local branch before pushing to a PR and we shouldn't need to run longish processes repeatedly; similarly, this is why we only run `yarn type-check` **only** before pushing up. However, if using pre-push, then failed checks will require a fix and a new commit and / or rebase (which I'm fine with since checking in secrets will likely be quite rare).
> 
> As long as this is also being run in CI I think we'll be safe since a dev won't be able to skip with `--no-verify`.


@damassi The problem with incorporating this check on pre-push instead of pre-commit is that it does not guard against secrets that may have made it into git history, hence the recommendation to wire this up on pre-commit, where this tool is most effective.

If a secret has made it into git history and then was removed in a later commit (assuming commits were not squashed before push), neither pre-push or CI would capture this however in all likelihood the tool would have raised a violation on a pre-commit when a secret was initially checked in. CI scan is just a fallback and not a great one as it doesn't take git history into account.

Seeing as this project has such high velocity and developer experience is paramount, we can give this a go for a couple of weeks and see how it affects dev flow. If it turns out to be too disruptive and we struggle to make it work without issues we shall revisit this and adjust accordingly.

**Comment by damassi** [comment]
Sounds good! Lets do it 👍

**Review by damassi — APPROVED** [review]

**Pull request merged**
