### PR TITLE
Deploy to production

### PR DESCRIPTION
**Pull request by yuki24**

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This deploy contains the following PRs:

- Add a border between artwork metadata and partner stub when it's not for sale ([#932](https://github.com/artsy/force/pull/932) by @yuki24)
- Do not attempt to switch a ruby version ([#937](https://github.com/artsy/force/pull/937) by @yuki24)
- @eessex: Add view helpers and client-side article view. ([#935](https://github.com/artsy/force/pull/935) by @craigspaeth)
- @joeyAghion: Split tests across 4 containers ([#931](https://github.com/artsy/force/pull/931) by @craigspaeth)
- @mzikherman: Fix Dangerfile PR link and add PR authors' names (fixes #922) ([#930](https://github.com/artsy/force/pull/930) by @joeyAghion)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by craigspaeth** [comment]
Congrats on the first deploy @yuki24 !!

**Comment by yuki24** [comment]
@craigspaeth Thanks!

**Comment by mzikherman** [comment]
Ah I forgot to merge! Merging...

**Pull request merged**
