### PR TITLE
remove custom criteo integration as we are moving it to segment

### PR DESCRIPTION
**Pull request by cavvia**
This removes our custom Criteo integration as we are moving it to Segment. All Criteo events will be forwarded on by Segment from now on.

Depends on https://github.com/artsy/reaction/pull/2169

### CODE REVIEW

**Comment by joeyAghion** [comment]
Nice!

Please unset the configs (there are 2 `CRITEO_*` ones in Force's production env) once possible as well.

**Comment by mzikherman** [comment]
Awesome! I'll wait for the Renovate bot to get Force updated with that latest published version of Reaction, and then I'll merge this.

**Comment by mzikherman** [comment]
Also, amazing! Not having this stuff go to Segment was the cause of some technical debt (criteo js, having this criteo analytics decoupled from app code), so I'm very glad the integration is working!

**Comment by joeyAghion** [comment]
BTW does Segment send data to Criteo on the back-end, or will it just pull Criteo's client-side js in anyway?

**Comment by cavvia** [comment]
I'm not sure yet @joeyAghion - some Segment integrations do pull in the JS for page view tracking but then forward on conversion events in the backend. In this case we will be mainly forwarding on events  rather than pageviews so I'm hoping not.

**Pull request merged**
