### PR TITLE
Delete unused auction_lots app

### PR DESCRIPTION
**Pull request by bhoggard**
Deletion! 🎉 

related ticket https://artsyproduct.atlassian.net/browse/AUCT-1079

Assigning @zephraph since Purchase is responsible for auction results.

### CODE REVIEW

**Comment by bhoggard** [comment]
I will set up a review app for us to test before merging.

**Comment by dleve123** [comment]
For the sake of moving forward on this PR (and considering that Justin is OOO), I'd recommend considering approval for this PR to be a review app that demonstrates that these routes are behaving as on staging/production, just to hedge against insufficient testing somewhere:

```
app.get '/artist/:artist_id/auction-result/:id', timeout('25s'), routes.detail	
app.get '/artwork/:id/auction-results', timeout('25s'), routes.artwork	
```

**Comment by bhoggard** [comment]
Review app: https://aca041048b64611ea976f123b14b93be-471778295.us-east-1.elb.amazonaws.com/

**Comment by bhoggard** [comment]
I confirmed that this is working:

https://aca041048b64611ea976f123b14b93be-471778295.us-east-1.elb.amazonaws.com/artist/kerry-james-marshall/auction-results

We don't show auction results on any individual artworks now. It redirects to the artwork page. I tested:

https://aca041048b64611ea976f123b14b93be-471778295.us-east-1.elb.amazonaws.com/artwork/kerry-james-marshall-portrait-of-a-curator-in-memory-of-beryl-wright/auction-results

and confirmed that it redirects back to the artwork.

**Comment by bhoggard** [comment]
@sepans and @GuillaumeDelg confirmed the review app is working, so merging.

**Pull request merged**
