### PR TITLE
Update node to 10.14

### PR DESCRIPTION
**Pull request by zephraph**
10.14 is a security update.

See the release notes: https://nodejs.org/en/blog/release/v10.14.0/

### CODE REVIEW

**Comment by zephraph** [comment]
Looks like the image might not be posted yet....

Hey @izakp, @joeyAghion, @dblandin...

What do you folks think about always pulling in the latest version of 10? If I loosened this to `FROM node:10` it'd always update when a new node docker image was published (right?... Isac, correct me if I'm wrong... maybe caching invalidates that assumption). 

Idk. I can enable renovate to create PRs to update the node version. It would create a new PR that would update the docker file and update the nvmrc (though pinning that to 10 would likely be fine, because requiring different dev versions across projects and keeping those in sync would be annoying). 

We can talk about it more in depth tomorrow...

**Comment by izakp** [comment]
@zephraph considering we get a cold Docker daemon on CircleCI I don't think we have to deal with caching but implicit cache busting when using a `latest` or no tag appears to be a [long standing issue](https://github.com/moby/moby/issues/13331) and the canonical way to ensure you get the latest image for that tag is still to do a `docker pull node:10` (using your example) _before_ attempting any other commands that may hit the local cache.

**Comment by joeyAghion** [comment]
I'm wary of the same `docker build` (or CI) operation employing different node versions depending on when it's run. A developer making a minor change may upgrade (without that being very visible) and have to debug any fallout. Personally I also like to wait a little while before bumping to the latest versions.

But, that's all based on my own experience. If these minor upgrades tend to be super-reliable, maybe it will save work.

**Comment by zephraph** [comment]
We're on LTS so in general one would hope node stays pretty stable between minor releases. The big thing here is that this is a security release. We _can_ wait, but should we?

I might close this for now though and approach the problem at a slightly different angle. Renovate can update the dockerfile w/ a specific node version via a PR which I think might be the better way to go here. I'll poke at it.

**Pull request closed without merging**
