### PR TITLE
chore: remove released collector profile and separate saves and follows ff

### PR DESCRIPTION
**Pull request by MounirDhahri**
The type of this PR is: **chore**

This PR solves [PROJECT-XX]

### Description

remove released collector profile and separate saves and follows ff

[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dzucconi** [comment]
🙏

**Comment by MounirDhahri** [comment]
CI tests are not running for some reason

**Review by MrSltun — APPROVED** [review]
Looks great!! 🙌  Thank you for this PR Mounir!! ✨ 
I have one concern about integrity tests breaking after merging this PR, since we have a different releasing strategy for `collector-profile-separating-saves-and-follows` on staging

I took a quick look and couldn't find any test for the saves and follows page, maybe we should also add some tests there as well!

**Review by olerichter00 — APPROVED** [review]
This is a huge PR! I tried to review every change but can't guarantee everything 🙃 

Thanks for cleaning up the feature flag 🧹

**Pull request merged**
