### PR TITLE
[package] cookies-js is a runtime dependency

### PR DESCRIPTION
**Pull request by alloy**
@craigspaeth Any idea why Force worked thus far with this being a dev dependency? Maybe it was a transitive dependency of a runtime dependency that we removed or it no longer depends on cookies-js?

### CODE REVIEW

**Comment by craigspaeth** [comment]
Because assets are packaged with dev dependencies and cookies js is only needed on the client side afaik.

**Comment by alloy** [comment]
But this is a recent change?

**Comment by craigspaeth** [comment]
I'm probably missing enough context to answer this well—but if it was moved from a prod > dev dependency then it may have been a cleanup effort to reduce the number of things that needed to be installed in production... based on the assumption that a client-side library like Cookies.js was accidentally missing the `--dev` flag when it was first `npm install`ed.

That said, 👍  to this as we should probably err on keeping things production dependencies as it could be easy to forget if a client-side module gets imported server-side.

**Comment by alloy** [comment]
Aight 👍

**Pull request merged**
