### PR TITLE
@mzikherman remove EOY from homepage

### PR DESCRIPTION
**Pull request by 1aurabrown**
fixes part 1 of https://github.com/artsy/collector-experience/issues/80
I saw that this issue exists but that EOY is still on the homepage.

### CODE REVIEW

**Comment by 1aurabrown** [comment]
@alloy oops i'll reassign to matt

**Comment by mzikherman** [comment]
Hmm, somehow semaphore didn't catch this, mind pushing an empty commit to kick Semaphore?

**Comment by broskoski** [comment]
Maybe good to delete the code here as well?

**Comment by mzikherman** [comment]
@broskoski I'll let you take the reigns on this, being that you're the only one to have touched this code before!

**Comment by broskoski** [comment]
🎩  just delete the components and routes and we are gtg!

**Comment by broskoski** [comment]
Ok just gonna marge this, I'll add an issue to remove the code as well.

**Comment by 1aurabrown** [comment]
@broskoski @mzikherman 
wait but isn't it supposed to remain up on other pages til the end of the month? that's why i didn't remove the components:

Artists landing: Jan 31
Individual artists: Jan 31

**Comment by broskoski** [comment]
Ah, cool, didn't realize that. Thanks!

**Pull request merged**
