### PR TITLE
Delete legacy order app

### PR DESCRIPTION
**Pull request by williardx**
Following up from the buy now launch, deletes the legacy order app from Force in favor of our new order app at `/orders`.  Resolves [PURCHASE-557](https://artsyproduct.atlassian.net/browse/PURCHASE-557).

### CODE REVIEW

**Comment by sweir27** [comment]
Also, at this point we could also remove the old order Backbone models:
https://github.com/artsy/force/blob/master/src/desktop/models/order.coffee
https://github.com/artsy/force/blob/master/src/desktop/models/pending_order.coffee
https://github.com/artsy/force/blob/master/src/mobile/models/order.coffee

**Comment by williardx** [comment]
Cool, I'll take out the old order models as well and rename `order2 -> order`.

**Comment by williardx** [comment]
I just went through and deleted the old order models, which ended up in lots of changes. I'm going to hold off on renaming `order2 -> order` until this is in since it's big enough already.

**Comment by sweir27** [comment]
@williardx that makes sense re: renaming! Thanks for the extra cleanup here.

**Pull request merged**
