### PR TITLE
feat(toolchain): Replace eslint and prettier with Biome, a unified Rust-based toolchain

### PR DESCRIPTION
**Pull request by damassi**
The type of this PR is: **Feat**

> Opening this up for feedback. Anyone have any objections? 

### Description

This was inspired by the dread of migrating our project from Eslint 8 to 9, which has a new and very confusing API and is in general very hard to configure / use. Lets simplify and migrate our app to use [Biome](https://biomejs.dev/).

Biome is a successor of sorts to Eslint and Prettier, and [claimed the 20k bounty](https://prettier.io/blog/2023/11/27/20k-bounty-was-claimed) from Prettier org to make a faster formatter in Rust. I ran it over our entire project and it autofixed thousands of files in just a few milliseconds! (Hence all of the changed files.)

To run:
- `yarn format-and-lint-project` 
- `yarn format-and-lint <files>`
- Though it also runs on precommit

### Devs using VSCode! Will need to install the VSCode plugin for auto-formatting: https://marketplace.visualstudio.com/items?itemName=biomejs.biome

For those who aren't using VSCode, see [here](https://biomejs.dev/guides/editors/third-party-extensions/).

There are lots of wins, but notably it sets us up well by 
- removing dependencies 
- unifying our toolchain
- improving perf of toolchain. 

There wasn't much that needed to change. To setup I simply ran 
-`yarn biome init`
- `yarn biome migrate eslint`
- `yarn biome migrate prettier` 

And it read all of our existing rules and applied them to the config. 

I think a next step would be to start removing rules and try to get it as close to zero-config as possible. 

Everything works exactly as you'd expect: 

Screenshot 2024-12-18 at 10 52 42 AM

cc @artsy/diamond-devs

### CODE REVIEW

**Comment by mzikherman** [comment]
My browser is struggling with the 'Review' dialog in the 'Files Changed' tab - 😅 

I'm cool with this 👍 . It seems like this is an improvement/faster (as we've seen with moving to Rsbuild) - and with the VSCode plugin, should remain seamless for devs - so it makes sense to me!

**Comment by anandaroop** [comment]
I like the speed improvement. 

My concerns would include: compatibility with the rules we've previously settled on (which _sounds_ like it was taken care of by the `migrate` steps — were there no gotchas here?) as well as the tooling ecosystem (easy for me since I use VSC extension, but wondering about others).

**Comment by damassi** [comment]
Yup, all the rules migrated! its meant to be a drop-in replacement for everything -- one tool to rule them all. 

I imagine there are other features coming for this down the pipeline, too.

**Comment by damassi** [comment]
Will def update @egdbear 👍

**Pull request merged**
