### PR TITLE
#migration restrict Force production ELB ingress to Cloudflare IPs

### PR DESCRIPTION
**Pull request by izakp**
IPv4 ranges taken from from https://www.cloudflare.com/ips-v4

See https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service for Kubernetes spec

## Migration

`hokusai production update`

### CODE REVIEW

**Comment by izakp** [comment]
Setting #donotmerge as we still need to filter out bot traffic when attempting to hit other routes such as /log_in

**Comment by izakp** [comment]
> Just one question for my understanding, is the ELB of our entire k8s cluster configured through the Force deployment?

@alloy the ELB for force-web is configured entirely by Kubernetes, and each application's ELB is configured separately as is the Kubernetes API ELB

**Comment by alloy** [comment]
Ahhh, separate ELBs per app.

**Comment by izakp** [comment]
@alloy I am also including a change to read the Nginx config from the `nginx-config` ConfigMap in production, so it can be managed out of source control securely.

**Comment by izakp** [comment]
> Setting #donotmerge as we still need to filter out bot traffic when attempting to hit other routes such as /log_in

Unsetting #donotmerge as we have some Nginx protection in place - we can follow up by migrating these rules to Cloudflare.

This should be good to merge.  Already applied in production.

**Pull request merged**
