### PR TITLE
[Artist/JSONLD] Artwork may not have an image.

### LINKED ISSUE #1418: TypeError: Cannot read property 'url' of null
https://sentry.io/artsynet/force-production/issues/271269109/

```
TypeError: Cannot read property 'url' of null
  File "/app/desktop/apps/artist/view_helpers.coffee", line 94, in Object.toJSONLD
    url: artwork.partner.url
  File "/app/desktop/apps/artist/routes.coffee", line 76, in null.<anonymous>
    variables:
...
(10 additional frame(s) were not displayed)

TypeError: Cannot read property 'url' of null
```

### PR DESCRIPTION
**Pull request by alloy**
Fixes #1418

### CODE REVIEW

**Comment by mzikherman** [comment]
Interestingly enough, what does it mean for an artwork not to have a partner?

The latest artwork with a `nil` for `partner_id` is from 2015. I'd also imagine that if a partner is actually removed from the system, that their artworks are unpublished or 'marked as deleted' or something? Can we tell which URL was causing the error? Looking at Sentry some of their sample URLs dont seem to be causing an error currently.

**Comment by alloy** [comment]
It happens when reflection queries. Here’s an example:

```
$ curl -I -H "User-Agent: PhantomJS" "https://www.artsy.net/artist/kristin-komar"
HTTP/1.1 500 Internal Server Error
```

**Comment by mzikherman** [comment]
Still confused...going to look at this locally. That artist doesn't even have any artworks? So how would the artwork JSONLD thing even be triggered on this page?

**Comment by mzikherman** [comment]
I don't believe the sourcemap in Sentry is correct. The failing lines are _not_ the artwork/partner/url one fixed here. It's just the artist url: https://github.com/artsy/force/blob/0f55f0d658fed1e4bf5b10f7b78fad144a607951/desktop/apps/artist/view_helpers.coffee#L73

This can be replicated locally with `PhantomJS` user-agent in the Chrome emulator.

So basically I think the issue is the line-number for the backtrace is not correct, but coincidentally pointed to a line with similar things going on, so it's definitely confusing!

But the correct fix is just `artist.image?.url` in that linked line, and not this partner stuff.

**Comment by mzikherman** [comment]
The reason it jumped out at me is because we do `artwork.partner..` kinda stuff everywhere, being defensive about a missing partner attached to an artwork is sort of a _very_ weird circumstance.

**Comment by alloy** [comment]
> I don't believe the sourcemap in Sentry is correct. 

Sigh. This doesn't surprise me one bit and I should have verified.

Good catches! I guess that also answers my question about an artwork not having an image :)

**Comment by cavvia** [comment]
Thanks for hunting that down @mzikherman. I started looking at partner deletion callbacks to see where this might arise from - we now have `PartnerArtist` and `PartnerArtwork` association models which we destroy, but no explicit cleanup on the actual Artwork model, at least not in our Gravity models or partner deletion API endpoint. I don't think partner deletion is something we really do - we have a `/partner/:id/unpublish_all_artworks` endpoint which is more likely what we do in those cases.

It's far more likely that an artwork doesn't have an image!

**Comment by alloy** [comment]
Updated 👍

**Comment by mzikherman** [comment]
Lol I still think this is incorrect. It's not the artwork's image...it's the _artist's_ image. In this line: https://github.com/artsy/force/blob/0f55f0d658fed1e4bf5b10f7b78fad144a607951/desktop/apps/artist/view_helpers.coffee#L73

This is b/c the artist image is either manually set by an admin, or auto-set based on artworks. So an artist with no artworks is unlikely to have an image.

**Comment by alloy** [comment]
I have definitely encountered artworks without images in the past. Should I just leave this guard in and add one for the artist too?

**Comment by cavvia** [comment]
I don't see how it could be harmful to have both guards.

**Comment by mzikherman** [comment]
I agree, can't hurt. It looks like the artworks in this context are coming from [here](https://github.com/artsy/force/blob/0f55f0d658fed1e4bf5b10f7b78fad144a607951/desktop/apps/artist/queries/jsonLD.coffee#L16).

It does seem 'not right' for a published for-sale artwork to _not_ have any image? But that's an issue frequently encountered (and we don't really enforce that in gravity anywhere), so I guess we should keep the guard for that too (might as well).

**Comment by alloy** [comment]
@mzikherman Alright, new round 👍

**Comment by cavvia** [comment]
This works assuming a blank string is handled fine by the template - I believe it would be an invalid `src` if included as is.

**Comment by cavvia** [comment]
I'll merge this in for now as that one question mark above is not a blocker.

**Comment by alloy** [comment]
@cavvia Yeah that’s an annoying thing with JS where an empty string is falsy and so I’m continuously confused about what people would expect.

@craigspaeth do you know what reflection would prefer in this case?

**Comment by craigspaeth** [comment]
I don't think Reflection necessarily cares about the data in json-ld tags—we actually [used to strip them out](https://github.com/artsy/reflection/pull/50). I guess the question is more would Google or whatever else is using our json-ld tags care if there's blank values in the data. 🤷‍♂️ Someone in [#seo](https://artsy.slack.com/messages/C02BDPZPC/) might know, but probably not worth spending too much time thinking about—this is fairly edge case.

**Pull request merged**
