### PR TITLE
@craigspaeth - Remove twitter sign-up option

### LINKED ISSUE #499: Remove Sign up with Twitter option
- **Remove** all twitter signup option on force and mg
- **Keep** all twitter sign in options on force and mg

screen shot 2016-12-09 at 1 30 58 pm

### PR DESCRIPTION
**Pull request by broskoski**
Partially closes #499 

This one is interesting, if we are leaving the "Log in with twitter" option, you actually can still sign up with twitter, as passport routes you through the same flow (hence, i left the "one last step" route and page). If we want to remove this ability completely, LMK!

### CODE REVIEW

**Comment by craigspaeth** [comment]
One of the many reasons I find auth as a service a neat approach. We could simply toggle on and off services via control panel with [Auth0](https://auth0.com/) for instance.

**Comment by mzikherman** [comment]
Woo!

I don't think we'd want to remove the 'Log in' functionality since there's probably a good slug of users who only have twitter logins (and would thus be stranded- i think @katarinabatina mentioned there are about ~4k of these).

But I'd be down to remove the 'One last step' (or whatever else to truly make it impossible to initiate a fresh sign up via Twitter).

**Comment by briansw** [comment]
@broskoski given that we still need to support login for users who signed up via twitter I think this is fine. Heads up @katarinabatina, technically, users will still be able to sign up via twitter, but only via the log in flow and there's not much we can do about it if we want to support login for existing twitter accts.

**Comment by broskoski** [comment]
@mzikherman yeah good point, I suppose we could remove the one last step page. I guess the proper thing to do would be to redirect back to the login page with a "User not found" error.

**Comment by katarinabatina** [comment]
@briansw yes thanks for the reminder. I hope that we might be able to rid ourselves of it entirely by somehow telling twitter auth users that they need to use their email/password and if they don't have one (?) to add this info to their accounts...as far as I understand though this isn't really possible but something to poke into more cc @tayapage6

**Comment by broskoski** [comment]
Ok with some guidance from @craigspaeth and @mzikherman we are now successfully stopping Twitter auth'd accounts getting signed-up if a user isn't found. Up next MG...

**Comment by broskoski** [comment]
🍏

**Comment by alloy** [comment]
@broskoski @mzikherman Why can’t users that used Twitter in the past use email to sign-in? Because they have no password? If that’s the case, I wonder if we can’t just have them use the password reset feature.

**Comment by craigspaeth** [comment]
@alloy Twitter's OAuth API doesn't give us their email so unfortunately that wouldn't work either :man_shrugging:

**Pull request merged**
