### PR TITLE
@mzikherman - Client side error

### PR DESCRIPTION
**Pull request by broskoski**
cc @joeyAghion 

Re #801 

This will send client-side errors (and specific errors from the inquiry page) to our trial Raygun service. I tested it out, already looks useful. Log in via Heroku.

screenshot 2017-02-01 18 02 26

### CODE REVIEW

**Comment by joeyAghion** [comment]
I know we've tried a number of client-side error-reporting tools before, so cc: @craigspaeth in case this is retracing any of our past steps.

Will this report errors that are "caught" at some level, such as failures during the inquiry questionnaire [that initiated this investigation]?

**Comment by broskoski** [comment]
@joeyAghion yes, this specifically targets errors that are caught during the inquiry questionnaire.

**Comment by craigspaeth** [comment]
👍  to this. In the past we have used services like Sentry and New Relic's browser-side monitoring. They worked fairly well and happy we're trying Raygun out. I guess some caveats to be aware of with client-side error tracking is it can get kinda noisy because older browsers have poor error reporting/stack traces, minified code also makes tracing the source of errors hard, and people can install browser extensions/ad-blockers/etc. that throw errors and increase noise. Browsers, JS, and the tools have gotten a lot better over the year though, so we might find it more successful these days.

**Comment by mzikherman** [comment]
Yay, this is awesome! Stoked to check it out.

Merge on 💚 there's some kind of crazy ❌

**Comment by broskoski** [comment]
Wow, that is a crazy ❌ . Investigating.

**Comment by broskoski** [comment]
Looks like the hand-edited shrink did the trick, there were a lot of changes when I wiped out my node modules and re-installed.

**Pull request merged**
