### PR TITLE
fix(GRO-509): Update homepage banner copy

### PR DESCRIPTION
**Pull request by jacobherrington**

### CODE REVIEW

**Review by dzucconi — APPROVED** [review]
😗👌

**Comment by dzucconi** [comment]
[https://danger.systems/js/](Danger) is complaining about not having a description. For something as simple as this maybe just a link to the JIRA ticket would be appropriate. Not sure what the other errors there are about. Merging! Thanks

**Comment by damassi** [comment]
> For something as simple as this maybe just a link to the JIRA ticket would be appropriate.

Even though this is simple, as a best practice we should avoid bare links to GH tickets as that makes our GH papertrail dependent on a 3rd party (which we could switch away from in the future), while additionally limiting search functionality.

**Comment by jacobherrington** [comment]
@damassi I agree. In this case, I think the commit message (PR title) conveys any information someone might need.

I tend to bias toward keeping as much information in the commits vs the PR for the same reason. I'll definitely keep this in mind as I do more feature development and work in Force.

**Pull request merged**
