### PR TITLE
@craigspaeth => Wrap client.js in fn

### PR DESCRIPTION
**Pull request by damassi**
Fixes mount issue

### CODE REVIEW

**Comment by craigspaeth** [comment]
Another point for figuring out a better way to deal with this crack between layers (along with the poor regex route matching that happens). 🤔 

Thanks for the quick fix!

**Comment by anandaroop** [comment]
Thanks for jumping on this, both of you! 🙏  🙏 

I confess I still don't quite see how this fixes the /gene page issue, since it's only related to the mounting on the /categories page, but I'll study this code while waiting on CI...

**Comment by damassi** [comment]
@anandaroop - its not just the Gene page! The issue is due to how code that is not wrapped is immediately executed just by being imported / statically analyized somewhere in the stack. The `export default () =>` guards against this.

**Comment by anandaroop** [comment]
Ok, thanks for that explanation. Gonna merge this.

So [this line](https://github.com/artsy/force/blob/master/desktop/assets/categories.coffee#L8)  relies on that default export you've added here, yes?

**Comment by damassi** [comment]
Yup, exactly. Since it was required it was immediately executed on mount, but now, with the `default`, while the file is executed the bit that matters is only called on route match.

**Comment by anandaroop** [comment]
Now that the fire is out, just wanted to recap for my understanding, and maybe someone else's:

- the /gene/:id, /tag/:id and /categories pages all share [the same client-side bundle](https://github.com/artsy/force/blob/master/desktop/assets/categories.coffee), which in turn `require`s client-side code for all three of those pages right away.

- because of that, the code in those three `require`s will get executed immediately. Therefore anything that is not meant to be run immediately should be wrapped in a function for deferred execution

- that deferred execution happens through our pattern of regex matching the current location and mapping it to one of the named or default exports in those three `require`d files

- because the new client.js didn't have the default exported function, the mounting code was being run immediately, and looking for a DOM element that didn't exist on the /gene and /tag pages, causing an error which presumably halted JS execution on those pages, thus the reported bug

- the issue of the missing `export default` was masked by the fact that the new /categories3 page had its _own_ js bundle right up until the apps were swapped out, i.e [this commit](https://github.com/artsy/force/commit/4079691cd4e4b94ccd44fea8c2adfb5304e4a510#diff-5d32c4d4a6217b93a26eca1cff2ff0b3), which is why it was not catchable earlier

I think that covers it.

I think one of the main factors here is having several disparate pages share the same client-side bundle. Given that they are each requiring their own client.js files, is there any savings here due to code-sharing — seems like no? I wonder if we could have better isolation and prevent bugs like this by having one bundle per subapp, strictly.

**Comment by damassi** [comment]
@anandaroop exactly correct. This will hopefully be mitigated in the future by our migration to Webpack which will allow us to take advantage of [dynamic imports](https://github.com/tc39/proposal-dynamic-import); this will result in safer bundle splitting.

**Comment by anandaroop** [comment]
That's awesome, thanks @damassi.

**Pull request merged**
