### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by alloy**

### CODE REVIEW

**Comment by alloy** [comment]
Well, I’m not even sure how important that Travis run is, so going for the merge.

**Comment by mzikherman** [comment]
That's the Danger run to post the comment :(

Is Travis just sometimes really slow on OSS projects? If so, that's yet another reason to move this functionality off of Danger, and onto just a self-hosted GitHub bot (a la the ones that make you sign a CLA, etc.).

**Comment by alloy** [comment]
> Is Travis just sometimes really slow on OSS projects?

Probably, yeah :/

**Comment by mzikherman** [comment]
Looks like it eventually ran `~17 minutes ago`, and since you opened this PR ~39 minutes ago, it seemed like it was queued/waiting in Travis for 20 minutes. :(

**Pull request merged**
