### PR TITLE
Updating staffing title changes + profile pic

### PR DESCRIPTION
**Pull request by pam-**
The type of this PR is: **Chore**

[GRO-1551]
[GRO-1476]

This PR updates titles + staffing changes in the editorial and specialists team pages.

[GRO-1551]: https://artsyproduct.atlassian.net/browse/GRO-1551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1476]: https://artsyproduct.atlassian.net/browse/GRO-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jonallured — APPROVED** [review]
LGTM!! 🎉

Note: I think the name of your branch caused the PR title to be a little goofy - might want to change to that something more reflective of the work here!

**Comment by damassi** [comment]
also @pam- titles that aren't in the semantic commit format, eg 
```
fix(context): Description
```
don't get picked up by velocity metrics

**Comment by pam-** [comment]
@damassi woops! finally updated and appeased peril 🥲

**Comment by damassi** [comment]
ha, I think peril will _still_ get mad at caps case 😆 but our pr tracker will pick it up np

**Pull request merged**
