### PR TITLE
@1aurabrown => Add click tracking for popular artists

### PR DESCRIPTION
**Pull request by mzikherman**
Closes https://github.com/artsy/collector-experience/issues/83

### CODE REVIEW

**Comment by mzikherman** [comment]
cc @anipetrov

**Comment by anipetrov** [comment]
Can we change the event name to `Click`? We are trying to remove the `clicked_on_...` events since Segment is creating separate tables for each of those and really clogging our system -- for any click that is not of top priority, we would rather have a catch-all `Click` event that is appropriately propertirized (since we already get things like `context_page_path` from segment, with proper `label` and `context_module` we should be able to differentiate between most unessential clicks easily enough).

**Comment by mzikherman** [comment]
> Can we change the event name to Click?

Will do- you actually noted that in the original issue!

**Comment by anipetrov** [comment]
Awesome, thanks @mzikherman!

**Pull request merged**
