### PR TITLE
feat(onboarding): blocks in initial img assets

### PR DESCRIPTION
**Pull request by dzucconi**
https://user-images.githubusercontent.com/112297/177420164-d9b0a3e3-9136-4225-8023-d2666911c85e.mov

The animated columns will be updated with crops that I don't have yet.

### CODE REVIEW

**Comment by dzucconi** [comment]
Also just made those copy updates.

**Comment by TMcMeans** [comment]
are these the new approved copy changes?

**Comment by dzucconi** [comment]
Pull them off the Figma — which is the source of truth — yeah.

**Comment by TMcMeans** [comment]
lgtm

**Pull request merged**
