### PR TITLE
@alloy => Bump reaction and update paths

### PR DESCRIPTION
**Pull request by kanaabe**
Note that I've updated React to match Reaction's version bc I was seeing an error related to multiple React copies on the gene page:
```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded.
```
Also problematic was yarn's version which is now bumped to 1.x in Force.

### CODE REVIEW

**Comment by kanaabe** [comment]
💀  https://circleci.com/docs/1.0/yarn/#version-support -- brb bumping [this](https://github.com/artsy/reaction/blob/master/package.json#L18) down

**Comment by damassi** [comment]
@kanaabe / @alloy / @orta - do we _need_ to lock yarn versions?

**Comment by kanaabe** [comment]
For force there's this: https://github.com/artsy/force/pull/1674. But in reaction it's probably not necessary to specify since it's used as a dependency

**Comment by kanaabe** [comment]
Whew 🍏

**Comment by alloy** [comment]
Awesome, thanks!

**Pull request merged**
