### PR TITLE
chore: Remove Unused Coffee Imports

### PR DESCRIPTION
**Pull request by icirellik**
A quick pass to remove unused imports in old CoffeeScript files. This
reduces noise when doing dependency analysis.

### CODE REVIEW

**Comment by joeyAghion** [comment]
(Maybe naïve question:) How can you tell what's unused?

**Comment by icirellik** [comment]
@joeyAghion they aren't referenced in the file anywhere. Normally lint rules handle this.

**Comment by damassi** [comment]
@icirellik curious how you found these --  did you run `src` through coffeelint?

**Comment by icirellik** [comment]
@damassi sadly we cannot use any coffee linters because they require us to switch to CoffeeScript 2.0. I create a simple one-off script to look for unused imports. It wasn't very aggressive and only detected obvious candidates.

**Review by joeyAghion — APPROVED** [review]
Approving, but not merging so as not to make the next deploy (which is already "blocked") weightier.

Feel free to merge once things are safely moving again.

**Pull request merged**
