### PR TITLE
Add reCAPTCHA 3 scripts and fire homepage event

### PR DESCRIPTION
**Pull request by eessex**
Initial steps to use invisible captchas, related to https://artsyproduct.atlassian.net/browse/PLATFORM-1378

- Adds header script for google reCAPTCHA 3 to main layout
- Creates a new 'action' for loading the homepage
- Adds `RECAPTCHA_KEY` to sd 

The homepage action will start firing an invisible captcha whenever loaded, and operates in the background without affecting user experience. Once merged we should begin to see scores for users in our [reCAPTCHA admin](https://www.google.com/u/0/recaptcha/admin/site/346113690), which can help us set a baseline to determine what scores we want to accept or reject from the login/signup form.

The `RECAPTCHA_KEY` is a public key. We also have a private key that will be used once we start verifying scores on our server.

### CODE REVIEW

**Comment by joeyAghion** [comment]
It looks like this will need a migration for the new config, or maybe that can be set up in advance. Can you comment with the status of that?

Is the new `homepage` event just a temporary measure to help us calibrate, or would it stick around? One interesting possibility would be to be able to match these scores to the corresponding accounts when possible. That would, e.g., allow us to understand how the abusive traffic we already experience today scores via recaptcha. Is it possible to pass additional data with the new event?

**Comment by eessex** [comment]
No migration will be necessary, we can add an unlimited number of 'actions' so the login/signup event will exist in addition to the `homepage` action. I added this to help calibrate, the docs recommend leaving it in place for this reason.

As far as additional info, I'm not sure what we can send to into the google console, but we do have callback options that can be leveraged to match up users on our end.

**Comment by eessex** [comment]
Additionally we should see traffic sorted by subdomain, and sort staging from production in the admin console.

**Comment by joeyAghion** [comment]
Got it.

This is OK with me to merge once production has the necessary config.

Minor: I don't follow the `sharify` changes, but I assume those are related to this?

**Comment by eessex** [comment]
Key is now set in production. The tests are related, they were overriding the system `sd` config, but also checking that `undefined` doesn't appear in the html including the main header. Fix was to extend rather than override `sd`, so that `RECAPTCHA_KEY` does not print as undefined.

**Pull request merged**
