### PR TITLE
@damassi => [Dev] Add plug in to warn about case insensitive imports

### PR DESCRIPTION
**Pull request by mzikherman**
Let's see if this works on those occasional issues!

### CODE REVIEW

**Review by damassi — APPROVED** [review]
Thank you! LGTM 👍

**Comment by damassi** [comment]
#mergeOnGreen

**Comment by damassi** [comment]
(Still some casing issues that this caught)

**Comment by mzikherman** [comment]
Actually those are real ❌ on CI, since CI runs in a case-sensitive environment.

**Pull request merged**
