### PR TITLE
Add circle context hokusai

### PR DESCRIPTION
**Pull request by eessex**
Adds circle context hokusai.  I added it to all jobs here, but maybe it is not necessary for the `not_staging_or_release` step. 

Follow up: remove aws keys from Circle's force env.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The staging version of Metaphysics has breaking changes, this might not affect your build, but could mean your queries don't work the way you expect. See below for breaking changes:</td>
    </tr>
  </tbody>
</table>


- :warning: Field 'AnalyticsPartnerStatsType.artworksPublished' changed type from '[AnalyticsArtworksPublishedTimeSeriesStats!]' to 'AnalyticsArtworksPublishedStats'
- :warning: Argument 'period: AnalyticsQueryPeriodEnum!' added to field 'AnalyticsPartnerStatsType.artworksPublished'
- :warning: Argument 'period: AnalyticsQueryPeriodEnum!' added to field 'AnalyticsPartnerStatsType.uniqueVisitors'
- :warning: Field 'partnerId' was removed from object type 'AnalyticsArtworksPublishedTimeSeriesStats'
- :warning: Field 'partnerId' was removed from object type 'AnalyticsPartnerTimeSeriesStatsType'
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ca8e546ad0a9aff0c13ac9d9565e3a9ece55b2d4
</p>

**Comment by zephraph** [comment]
@eessex I think it's worth testing. If you remove it for `not_staging_or_release` then this PR will fail. If not, it won't. I'd be good to _not_ provide it to that job if possible.

**Comment by eessex** [comment]
@zephraph I removed context from `not_staging_or_release`, after this is merged we will see if the context is used on the `deploy_hokusai_staging` step.

**Comment by eessex** [comment]
Going to merge this so I can monitor over the staging deploy.  I made a similar change in positron and it was able to inherit context from required jobs as expected.

**Pull request merged**
