### PR TITLE
dont run detect-secrets on renovate branches

### PR DESCRIPTION
**Pull request by ovasdi**
This change prevents running `detect-secrets` in CI on renovate branches.

Test: https://app.circleci.com/pipelines/github/artsy/force?branch=renovate%2Fdetect-secrets-ci-change

### CODE REVIEW

**Comment by ovasdi** [comment]
I think Circle got confused. This is all green https://app.circleci.com/pipelines/github/artsy/force?branch=detect-secrets-ci-change

**Comment by joeyAghion** [comment]
I see! That's harder to prevent than what I was thinking. (Maybe the scanning step should apply to `master` so the failure is closer to the cause?)

Feel free to merge this if it unblocks things in the meantime.

**Comment by joeyAghion** [comment]
I was just worried if this would happen:
* renovate makes an automatic contribution that shifts some secrets [scanning is skipped]
* Joe Developer attempts an unrelated commit [scanning fails due to renovate's change]

**Comment by ovasdi** [comment]
I am going to wait on merging this. IMO the renovate PR failures were largely a result of timing, caused by a PR that was missing the `detect-secrets` commits from master.

Renovate PRs modify files that are not recorded in the baseline and thus should not trigger any changes to the `.secrets.baseline` during `detect-secrets-hook` run in CI.

**Pull request closed without merging**
