### PR TITLE
WIP Hokusaize

### PR DESCRIPTION
**Pull request by izakp**
- `(sudo) pip install --upgrade hokusai`
- `hokusai dev start` to run local dev stack - `hokusai dev run bash` in another window to get a shell in the container
- `hokusai test` to run yarn tests

Failing on `yarn start` (both locally and via `hokusai run dev`):

```
force_1  | yarn run v1.2.1
force_1  | $ sh scripts/start.sh
force_1  | + forever -c node -r dotenv/config --max_old_space_size=1024 .
force_1  | warn:    --minUptime not set. Defaulting to: 1000ms
force_1  | warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
force_1  |  1: node::Abort() [node]
force_1  |  2: 0x1218409 [node]
force_1  |  3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
force_1  |  4: 0xb8ee3c [node]
force_1  |  5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
force_1  |  6: 0x147491b8463d
force_1  | error: Forever detected script was killed by signal: SIGABRT
force_1  | error: Script restart attempt #1
force_1  |  1: node::Abort() [node]
force_1  |  2: 0x1218409 [node]
force_1  |  3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
force_1  |  4: 0xb8ee3c [node]
force_1  |  5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
force_1  |  6: 0x2ae8d1b8463d
force_1  | error: Forever detected script was killed by signal: SIGABRT
```

Failing on acceptance tests via `hokusai test` - locally tests pass:

```
force_1  | + yarn acceptance test/acceptance/artwork.js test/acceptance/auth.js test/acceptance/bidding.js test/acceptance/home.js test/acceptance/misc.js test/acceptance/partner_profile.js
force_1  | + mocha --retries 5 --compilers coffee:coffee-script/register,js:babel-core/register -r dotenv/config -r should -t 30000 test/acceptance/artwork.js test/acceptance/auth.js test/acceptance/bidding.js test/acceptance/home.js test/acceptance/misc.js test/acceptance/partner_profile.js dotenv_config_path=.env.test
force_1  | Warning: Could not find any test files matching pattern: dotenv_config_path=.env.test
force_1  |
force_1  |
force_1  |   Artwork page
force_1  | Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
force_1  | Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
force_1  |     1) renders an artwork title and artist
force_1  |
force_1  |   Authentication
force_1  |     - logs in
force_1  |     2) "after all" hook: teardown
force_1  |
force_1  |   Bidding flow
force_1  | Error: listen EADDRINUSE :::5001
force_1  |     3) "before all" hook
force_1  |
force_1  |   Home page
force_1  |     4) renders "Browse Works for Sale"
force_1  |
force_1  |   Page
force_1  |     /terms
force_1  |       5) renders a markdown page of terms and conditions
force_1  |     /tag/cow
force_1  |       6) renders a tag page for the tag cow
force_1  |     /dev/blank



force_1  |       7) renders a blank page for Eigen
force_1  |     with a mobile browser
force_1  |       8) "before all" hook
force_1  |
force_1  |   Partner profile page
force_1  |     9) "before all" hook
force_1  |
force_1  |
force_1  |   0 passing (17m)
force_1  |   1 pending
force_1  |   9 failing
force_1  |
force_1  |   1) Artwork page renders an artwork title and artist:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   2) Authentication "after all" hook: teardown:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   3) Bidding flow "before all" hook:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   4) Home page renders "Browse Works for Sale":
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   5) Page /terms renders a markdown page of terms and conditions:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   6) Page /tag/cow renders a tag page for the tag cow:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   7) Page /dev/blank renders a blank page for Eigen:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   8) Page with a mobile browser "before all" hook:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |   9) Partner profile page "before all" hook:
force_1  |      Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
force_1  |
force_1  |
force_1  |
force_1  |
force_1  | error Command failed with exit code 9.
force_1  | error Command failed with exit code 1.
force_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
hokusai_force_1 exited with code 1
```

@craigspaeth it seems the [`teardown` method in `./test/acceptance/helpers.js`](https://github.com/artsy/force/blob/master/test/acceptance/helpers/index.js#L61) does not finish closing some servers _before_ the next test attempts to launch them.  Is there a way to rewrite this method non-async, so that the test runner waits for the `teardown` method to resolve before starting the next test?

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please assign someone to your PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please assign someone to your PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by craigspaeth** [comment]
Ouch, looks like a 🍝  of environment/port conflicts exacerbated by that obscure Node abort + V8 stack trace error (@damassi I forget the root of that one—does it have anything to do with the way we [catch global errors in dev](https://github.com/artsy/express-reloadable/blob/master/index.js#L46)?). My hunch is both of these things have to do with ports being in use where the first one is stifled by that weird stack trace and the second one for whatever reason is not picking up the .env.test file.

> ` v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]`
🤷‍♂️ 

> `Could not find any test files matching pattern: dotenv_config_path=.env.test`
🔍 

> so that the test runner waits for the teardown method to resolve before starting the next test?

This is actually what why we need the teardown function to be async—to wait for the mock servers to finish [closing/accepting connections](https://nodejs.org/api/net.html#net_server_close_callback), hence why we [wrap the closings in promises and await them](https://github.com/artsy/force/blob/master/test/acceptance/helpers/index.js#L65). So I'm surprised to hear this might be causing a problem—I realized that I passed `resolve` straight in there, I wonder if it needs to handle errors e.g. `server.close((err) => err ? reject(err) : resolve()`... or maybe the way it's being used is in tests is too clever and it should explicitly be awaited there as well `afterEach(async () => await teardown())`.

Thanks for digging into this, I'll try to block out some time today to reproduce on my end and see if I learn anything new.

**Comment by izakp** [comment]
Thanks @craigspaeth - it occurred to me to try starting from an Ubuntu 14.04 (Trusty) base image, as that's what CircleCI is using.

**Comment by damassi** [comment]
@craigspaeth / @izakp 

> v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]

The Node team needs to make these errors friendlier. Somewhere along the 7-8 version spread something was updated and the errors started becoming much less user friendly. I've seen this (and variants thereof) triggered by a missing `.env` file, an already-running server, a wrong url address, memory issues surrounding compilation, etc., etc. In short, they happen all the time for hard to spot reasons and there's no easy way that I've been able to find to debug short of blind faith and trial and error.

As far as picking up test env file, I recently set this up over at Positron to make it a bit more strict: 
- https://github.com/artsy/positron/blob/master/scripts/mocha.sh#L9
- https://github.com/artsy/positron/blob/master/test/config.js

**Comment by damassi** [comment]
I'm going to close this (just for now) until we can coordinate across all of our repos and roll out to devs in a more official way. Lets reopen when we revisit.

**Pull request closed without merging**
