### PR TITLE
@kanaabe => 105 - consignments faq for mobile

### PR DESCRIPTION
**Pull request by erikdstock**
*squash commits on merge*

This is an addition to my previous PR on artsy/auctions/issues/105 that adds a mobile layout to the multi_page component. I thought it would need to go in microgravity but it turned out there is no /consign page in microgravity and that we are handling this layout with media queries and css. That means that the multipage layout is a little different here than on /how-auctions-work due to the faqs and headers being in separate containers. end result:

consignmobile

Other concern is that the photo credits aren't appearing at the bottom of the page, but i can't tell if that is supposed to be coming through the JsonPage data and I somehow messed it up or if it just doesn't appear in staging period. it should be on the template as `data` which from the looks of it would be coming from the jsonpage for consignments at `http://#{@bucket}.s3.amazonaws.com/consign/landing`. Anyhow, i'm blocked on it at this point.

So missing from my development force (and staging which already has the desktop-only faq merged in):
image

### CODE REVIEW

**Comment by kanaabe** [comment]
For the credit line, it looks like staging doesn't have the credit line built into the JSON blob since it doesn't appear here: https://staging.artsy.net/consign/edit. To quickly check, you can try `make sp` (point to production)

**Comment by erikdstock** [comment]
AH THANK YOU! @craigspaeth told me to check consign/edit and I did, but I didn't realize it was using the json blob until it was time to quit for the day- thought it was actually scraping the dom and only started to tease that idea when I made the PR.  How do you feel about the layout vs mobile www.artsy.net/how-auctions-work ?

**Comment by kanaabe** [comment]
Hmm I think we should pull in @katarinabatina for the design question. Code-wise, LGTM!

**Comment by katarinabatina** [comment]
@erikdstock I think it's a little weird that the content isn't reflected directly underneath the section that was accessed. Is that something we could adjust?

**Comment by erikdstock** [comment]
@katarinabatina @kanaabe no, at least not without a major change to the structure of the component. the issue is the structure of the component:
```
<div multi-page container
  <div titles column
    -overview
    -fees etc
  <div text column
    -overview text
    -fees text
```
In the version of this specifically for mobile in microgravity those 2 column divs aren't there- it is all mixed together. But there is no microgravity view for consignments.
I guess my one thought is that we could copy that component into force, render both versions of the multi-page faq and then hide the one that shouldn't be there. Or maybe someone else with better front end chops has a more efficient idea?

**Pull request merged**
