### PR TITLE
chore(type): Update desktop fairs landing page typography

### PR DESCRIPTION
**Pull request by anandaroop**
Addresses: https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046?p=eca675d56e3c43a3ae3c2d63b9417802

This updates the typography on the **fairs landing page** on **desktop**.

### CODE REVIEW

**Review by dzucconi — APPROVED** [review]
💯

**Comment by nicoleyeo** [comment]
@anandaroop looks great! 1 tiny thing – the "Show more" button is in Avant Garde at the very bottom. All else looks good to me 🙌

image

**Comment by anandaroop** [comment]
Good catch on the button @nicoleyeo . 

Given the other decision about buttons on mobile, wondering if we have a preference btw `text` and `mediumText`?

### `text`

Screen Shot 2020-09-16 at 2 50 08 PM


### `mediumText`

Screen Shot 2020-09-16 at 2 50 33 PM

**Comment by nicoleyeo** [comment]
`mediumText` looks great! And yes, let's stick with `mediumText` for all buttons. 

Also, reminder to use Sentence case, even for CTAs! "View more"

Thank you!!!!

**Comment by anandaroop** [comment]
Cool I'll change the copy to sentence case and then merge this 🙌

**Pull request merged**
