### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by dleve123**

### CODE REVIEW

**Comment by dleve123** [comment]
@damassi @xtina-starr could y'all get back to me in the next 2 hours if this is good to deploy or not?

**Comment by xtina-starr** [comment]
👍 from me.

**Comment by dleve123** [comment]
@xtina-starr and @damassi take a look at the [Danger CI's comment above](https://github.com/artsy/force/pull/3214#issuecomment-448328668) looks like there's meaningful incompatibility between Force's graphql schema and Metaphysics. Can you one of you take a look at this?

**Comment by damassi** [comment]
Yup, need to deploy MP! Good work danger.

**Comment by eessex** [comment]
Hoping to get this out by 11am today for EOY changes, did we get a metaphysics deploy out yet?

**Comment by damassi** [comment]
@eessex - not yet, but feel free to ping the MP channel and send it out.

**Comment by orta** [comment]
Peril / Danger are wrong here, I think the technique for doing this wrong somehow, catching maybe? Metaphysics prod is definitely showing the types referenced as not being in there.

**Comment by orta** [comment]
I think this could probably be improved by switching to the technique in 
https://github.com/artsy/peril-settings/pull/86 which will use a check with the images to detect differences with prod/staging.

**Pull request merged**
