### PR TITLE
feat(PX-4293): rename Shows tab to Events

### PR DESCRIPTION
**Pull request by kiryl-zubarau**
This PR renames **Shows** tab to **Events**

JIRA - https://artsyproduct.atlassian.net/browse/PX-4293

image

### CODE REVIEW

**Comment by sweir27** [comment]
#squashongreen

**Comment by kiryl-zubarau** [comment]
I updated only the tab title. Let me know if you want to update routing too.

**Comment by sweir27** [comment]
Oh good question @kiryl-zubarau -- would be worth asking Joh that. (And if we do update the route, do we need to change our redirect logic at all?)

**Comment by kiryl-zubarau** [comment]
@sweir27 it will require to add section to the redirection logic like this one, but for the `/shows` route https://github.com/artsy/force/blob/dd646110bfd5098b297e46fa2270398be0d92681/src/desktop/apps/partner_redirect/partnerRedirectionMiddleware.ts#L23-L27

**Pull request merged**
