### PR TITLE
Add copy explaining which browsers are compatible for identity verification

### PR DESCRIPTION
**Pull request by williardx**
## Problem

Only certain browsers are compatible with our identity verification process, and right now we don't tell users what they can and cannot use. This leads users to attempting to complete the flow in an incompatible browser, resulting in a broken experience.

## Solution

Add some copy explaining which browsers users can use.

Screen Shot 2020-05-26 at 5 11 12 PM

Jira: https://artsyproduct.atlassian.net/browse/AUCT-1038

### CODE REVIEW

**Comment by williardx** [comment]
@dleve123 We have some kind of commit hook that reformatted some unrelated code -- let me know if that's an issue.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `dangerfile.ts`.
  </td>
    </tr>
  </tbody>
</table>



## Error RangeError
```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at standardizeName (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:94:15)
    at resolveStandardizedName (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:98:28)
    at resolvePlugin (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
```
### Dangerfile
```
-----------------^
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 29a3b6ff70c3e2e4cced2abbddde2b46d75eacd0
</p>

**Comment by dleve123** [comment]
Mocha test looks like a flake -- rebuilding.

**Comment by dleve123** [comment]
Not worried about the Danger build here - merging.

**Pull request merged**
