### PR TITLE
Use sold message for on loan works too

### PR DESCRIPTION
**Pull request by jonallured**
Hi force friends, it's been such a long time!!! 👋 

Per @madeleineb on #AS-7, use the sold message for on-loan works too.

### CODE REVIEW

**Comment by jonallured** [comment]
@mzikherman The code changed here appears to be dead, what would you think about me morphing this PR into one that prunes the desktop/components/contact/default_message.coffee file entirely?

**Comment by mzikherman** [comment]
That's cool, but a quick search in Force does show this being referenced in a few places, are we sure it's unused?

**Comment by jonallured** [comment]
Is anyone really sure about anything?? 😝 

This line is what made us think that MP is used and not this code in force:

https://github.com/artsy/force/blob/a030314f238bc7c717c80511501c636c5aeeee39/desktop/apps/artwork/components/commercial/templates/inquire.jade#L26-L34

Did you find another place we missed??

**Comment by mzikherman** [comment]
Yep, the artwork page is backed by Metaphysics, so that's the exact right code that you linked.

I guess I'm trying to think if there are places that one can inquire on Force besides the desktop artwork page.

One that comes to mind is the mobile artwork page. Seems like making an inquiry on a mobile artwork page takes you to a page like: https://www.artsy.net/inquiry/yves-clerc-n-degrees-215 (as an example), and the code _seems_ to reference `default_message`, though I haven't looked too much further. Have you tested mobile artwork/inquiry pages? We should probably test that.

Besides that mobile artwork page I think you're right that we _might_ be able to nuke the code!

(Emission uses Metaphysics so we should be good there).

**Comment by jonallured** [comment]
Ok, after much thinking things through, @anandaroop and I have decided to merge this PR for now and follow up later on deleting code. So that left me with trying to prove that this PR does, in fact, correctly affect the default message. After some help from @damassi, I was able to get this screenshot as proof:

screen shot 2018-01-31 at 4 16 55 pm

So, I think this is ready to merge, but let me know if I missed anything!!

**Comment by anandaroop** [comment]
Super, thanks for following through and thanks @damassi for the assist.

**Pull request merged**
