### PR TITLE
Deploy 

### PR DESCRIPTION
**Pull request by mzikherman**

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
### This deploy contains the following PRs:

- @dblock => Add count flag to sitemap article fetch ([#996](https://github.com/artsy/force/pull/996) by @kanaabe)
- Artwork Sale Lot Sorting  ([#987](https://github.com/artsy/force/pull/987) by @damassi)


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mzikherman** [comment]
We actually never deployed on Friday b/c of a time-specific test failure, this includes the fix for that.

**Comment by mzikherman** [comment]
Also, I'm merging before the full build passes b/c the merge commit I just created is going to have a full build anyway.

**Comment by kanaabe** [comment]
Thanks for adding my PR to this deploy!!

**Pull request merged**
